/**
 * @generated by elysian-generator
 * schema: dictionary
 * path: modules/dictionary/dictionary-workspace.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import type { FrontendWorkspaceStateContext } from "@elysian/frontend-vue"
import type { ElyFormField, ElyFormValues } from "@elysian/ui-enterprise-vue"
import type { ComputedRef } from "vue"
import { computed } from "vue"

import type { DictionaryRecord } from "./dictionary.schema"

export interface DictionaryWorkspaceMainInjectedState {
  dictionaryErrorMessage: { value: string }
  dictionaryLoading: { value: boolean }
  tableItems: { value: DictionaryRecord[] }
}

export interface DictionaryWorkspacePanelInjectedState
  extends DictionaryWorkspaceMainInjectedState {
  formFields: { value: ElyFormField[] }
  formValues: { value: ElyFormValues }
  panelDescription: { value: string }
  panelTitle: { value: string }
  dictionaryDetailErrorMessage: { value: string }
  dictionaryDetailLoading: { value: boolean }
  dictionaryPanelMode: { value: "detail" | "create" | "edit" }
  selectedDictionaryType: { value: DictionaryRecord | null }
  selectedDictionaryTypeItems?: {
    value: Array<{
      id?: string
      value?: string
      label?: string
      status?: string
      sort?: number
      isDefault?: boolean
    }>
  }
}

const resolveDictionaryWorkspaceState = <TState>(
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
): TState | null => {
  if (!enabled || context?.kind !== "dictionary") {
    return null
  }

  return context.state as TState
}

export const resolveDictionaryWorkspaceMainState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveDictionaryWorkspaceState<DictionaryWorkspaceMainInjectedState>(
    context,
    enabled,
  )

export const resolveDictionaryWorkspacePanelState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveDictionaryWorkspaceState<DictionaryWorkspacePanelInjectedState>(
    context,
    enabled,
  )

export const readInjectedValue = <TValue>(
  state: ComputedRef<{ value: TValue } | null>,
  fallback: TValue,
) => computed(() => state.value?.value ?? fallback)

const normalizeText = (value: unknown) => String(value ?? "").trim()

const normalizeOptionalText = (value: unknown) => {
  const normalized = normalizeText(value)

  return normalized.length > 0 ? normalized : undefined
}

const normalizeNumber = (value: unknown, fallback = 0) => {
  const normalized =
    typeof value === "number" ? value : Number.parseInt(String(value ?? ""), 10)

  return Number.isFinite(normalized) ? normalized : fallback
}

export const createDefaultDictionaryDraft = () => ({
  code: "",
  name: "",
  description: "",
  status: "active",
})

export const filterDictionaryRecords = (
  items: DictionaryRecord[],
  query: Record<string, unknown>,
): DictionaryRecord[] => {
  const code = String(query.code ?? "")
    .trim()
    .toLowerCase()
  const name = String(query.name ?? "")
    .trim()
    .toLowerCase()
  const description = String(query.description ?? "")
    .trim()
    .toLowerCase()

  return items.filter((item) => {
    if (
      code.length > 0 &&
      !String(item.code ?? "")
        .toLowerCase()
        .includes(code)
    )
      return false
    if (
      name.length > 0 &&
      !String(item.name ?? "")
        .toLowerCase()
        .includes(name)
    )
      return false
    if (
      description.length > 0 &&
      !String(item.description ?? "")
        .toLowerCase()
        .includes(description)
    )
      return false
    if (
      query.status !== undefined &&
      query.status !== null &&
      query.status !== "" &&
      item.status !== query.status
    )
      return false

    return true
  })
}

export const resolveDictionarySelection = (
  items: Array<Pick<DictionaryRecord, "id">>,
  selectedId: string | null,
): string | null => {
  if (items.length === 0) return null

  if (selectedId && items.some((item) => item.id === selectedId)) {
    return selectedId
  }

  return items[0]?.id ?? null
}

export const normalizeDictionaryPayload = (
  values: Record<string, unknown>,
):
  | { status: "valid"; payload: Record<string, unknown> }
  | { status: "invalid"; message: string } => {
  const codeValue = String(values.code ?? "").trim()

  if (codeValue.length === 0) {
    return {
      status: "invalid" as const,
      message: "Dictionary code is required",
    }
  }

  const nameValue = String(values.name ?? "").trim()

  if (nameValue.length === 0) {
    return {
      status: "invalid" as const,
      message: "Dictionary name is required",
    }
  }

  return {
    status: "valid" as const,
    payload: {
      code: codeValue,
      name: nameValue,
      description: normalizeOptionalText(values.description),
      status: values.status ?? "active",
    },
  }
}

export const toDictionaryEditDraft = (
  record: DictionaryRecord,
): Record<string, unknown> => ({
  code: record.code ?? "",
  name: record.name ?? "",
  description: record.description ?? "",
  status: record.status ?? "active",
})
