/**
 * @generated by elysian-generator
 * schema: dictionary
 * path: modules/dictionary/dictionary.schema.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import { dictionaryModuleSchema as sourceModuleSchema } from "@elysian/schema"
import type { ModuleSchema } from "@elysian/schema"

export type DictionaryStatus = "active" | "disabled"

export interface DictionaryRecord {
  id: string
  code: string
  name: string
  description: string
  status: DictionaryStatus
  createdAt: string
  updatedAt: string
}

export const dictionaryModuleSchema: ModuleSchema = sourceModuleSchema

export const moduleSchema = dictionaryModuleSchema
