/**
 * @generated by elysian-generator
 * schema: dictionary
 * path: modules/dictionary/dictionary.page.vue
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

<script setup lang="ts">
import {
  ElyCrudWorkspace,
  type ElyCrudWorkspaceProps,
  type ElyQueryField,
  type ElyQueryValues,
  type ElyTableAction,
  type ElyTableColumn,
} from "@elysian/ui-enterprise-vue"
import { computed, inject, ref, watch } from "vue"

import { WORKSPACE_STATE_KEY } from "@elysian/frontend-vue"
import {
  readInjectedValue,
  resolveDictionaryWorkspaceMainState,
} from "./dictionary-workspace"
import type { DictionaryRecord } from "./dictionary.schema"

type DictionaryWorkspaceTranslation = (
  key: string,
  params?: Record<string, unknown>,
) => string

interface DictionaryWorkspaceMainProps {
  t: DictionaryWorkspaceTranslation
  moduleReady: boolean
  authModuleReady: boolean
  isAuthenticated: boolean
  canEnterWorkspace: boolean
  canViewDictionaries: boolean
  canCreateDictionaryTypes: boolean
  canUpdateDictionaryTypes: boolean
  queryFields: ElyQueryField[]
  tableColumns: ElyTableColumn[]
  itemCountLabel: string
  emptyTitle: string
  emptyDescription: string
  copy: ElyCrudWorkspaceProps["copy"]
  workspaceStateInjected?: boolean
}

const props = defineProps<DictionaryWorkspaceMainProps>()

const emit = defineEmits<{
  (e: "action", key: string, row: DictionaryRecord): void
  (e: "search", values: ElyQueryValues): void
  (e: "reset"): void
  (e: "row-click", row: DictionaryRecord): void
}>()

const injectedWorkspaceState = inject(
  WORKSPACE_STATE_KEY,
  computed(() => null),
)

const resolvedDictionaryWorkspaceState = computed(() =>
  resolveDictionaryWorkspaceMainState(
    injectedWorkspaceState.value,
    Boolean(props.workspaceStateInjected),
  ),
)

const resolvedLoading = readInjectedValue(
  computed(
    () => resolvedDictionaryWorkspaceState.value?.dictionaryLoading ?? null,
  ),
  false,
)
const resolvedErrorMessage = readInjectedValue(
  computed(
    () =>
      resolvedDictionaryWorkspaceState.value?.dictionaryErrorMessage ?? null,
  ),
  "",
)
const resolvedItems = readInjectedValue(
  computed(() => resolvedDictionaryWorkspaceState.value?.tableItems ?? null),
  [] as DictionaryRecord[],
)
const resolvedTableActions = computed<ElyTableAction[]>(() =>
  props.canUpdateDictionaryTypes
    ? [
        {
          key: "edit",
          label: props.t("app.dictionary.action.edit"),
        },
      ]
    : [],
)

const pageSizeOptions = [20, 50, 100]
const currentPage = ref(1)
const pageSize = ref(20)
const totalPages = computed(() =>
  Math.max(1, Math.ceil(resolvedItems.value.length / pageSize.value)),
)
const pageStart = computed(() =>
  resolvedItems.value.length === 0
    ? 0
    : (currentPage.value - 1) * pageSize.value + 1,
)
const pageEnd = computed(() =>
  Math.min(resolvedItems.value.length, currentPage.value * pageSize.value),
)
const paginatedItems = computed(() =>
  resolvedItems.value.slice(
    (currentPage.value - 1) * pageSize.value,
    currentPage.value * pageSize.value,
  ),
)
const paginationSummary = computed(() =>
  props.t("app.pagination.summary", {
    page: currentPage.value,
    totalPages: totalPages.value,
    start: pageStart.value,
    end: pageEnd.value,
    total: resolvedItems.value.length,
  }),
)

const goPreviousPage = () => {
  currentPage.value = Math.max(1, currentPage.value - 1)
}

const goNextPage = () => {
  currentPage.value = Math.min(totalPages.value, currentPage.value + 1)
}

const updatePageSize = (event: Event) => {
  const nextValue = Number((event.target as HTMLSelectElement).value)

  pageSize.value = pageSizeOptions.includes(nextValue) ? nextValue : 20
  currentPage.value = 1
}

const handleAction = (key: string, row: Record<string, unknown>) => {
  const rowId = String(row.id ?? "")
  const record = resolvedItems.value.find((item) => item.id === rowId)

  if (record) {
    emit("action", key, record)
  }
}

const handleCreate = () => {
  emit("action", "create", {} as DictionaryRecord)
}

watch(resolvedItems, () => {
  currentPage.value = Math.min(currentPage.value, totalPages.value)
})
</script>

<template>
  <div v-if="!moduleReady" class="enterprise-message enterprise-message-warning">
    {{ t("app.message.dictionaryModuleOffline") }}
  </div>

  <div
    v-else-if="authModuleReady && !isAuthenticated"
    class="enterprise-message enterprise-message-info"
  >
    {{ t("app.message.dictionarySignInToLoad") }}
  </div>

  <div
    v-else-if="canEnterWorkspace && !canViewDictionaries"
    class="enterprise-message enterprise-message-warning"
  >
    {{ t("app.message.dictionaryNoListPermission") }}
  </div>

  <div
    v-else-if="resolvedErrorMessage"
    class="enterprise-message enterprise-message-danger"
  >
    {{ resolvedErrorMessage }}
  </div>

  <ElyCrudWorkspace
    v-else
    :eyebrow="t('app.dictionary.workspaceEyebrow')"
    :title="t('app.dictionary.workspaceTitle')"
    :description="''"
    :query-fields="queryFields"
    :query-loading="resolvedLoading"
    :table-columns="tableColumns"
    :items="paginatedItems"
    :table-loading="resolvedLoading"
    :table-actions="resolvedTableActions"
    :item-count-label="itemCountLabel"
    :empty-title="emptyTitle"
    :empty-description="emptyDescription"
    :copy="copy"
    @action="handleAction"
    @search="emit('search', $event)"
    @reset="emit('reset')"
    @row-click="emit('row-click', $event as DictionaryRecord)"
  >
    <template #toolbar>
      <button
        v-if="canCreateDictionaryTypes"
        type="button"
        class="enterprise-button"
        :disabled="resolvedLoading"
        @click="handleCreate"
      >
        {{ t("app.dictionary.action.create") }}
      </button>
    </template>
    <template #footer>
      <div class="dictionary-pagination">
        <span>{{ paginationSummary }}</span>
        <label>
          <small>{{ t("app.pagination.pageSize") }}</small>
          <select :value="pageSize" @change="updatePageSize">
            <option
              v-for="option in pageSizeOptions"
              :key="option"
              :value="option"
            >
              {{ option }}
            </option>
          </select>
        </label>
        <button
          type="button"
          class="enterprise-button enterprise-button-ghost"
          :disabled="currentPage <= 1"
          @click="goPreviousPage"
        >
          {{ t("app.pagination.previous") }}
        </button>
        <button
          type="button"
          class="enterprise-button enterprise-button-ghost"
          :disabled="currentPage >= totalPages"
          @click="goNextPage"
        >
          {{ t("app.pagination.next") }}
        </button>
      </div>
    </template>
  </ElyCrudWorkspace>
</template>

<style scoped>
.dictionary-pagination {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: flex-end;
  gap: 0.65rem;
  color: #475569;
  font-size: 0.82rem;
}

.dictionary-pagination label {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
}

.dictionary-pagination small {
  color: #64748b;
}

.dictionary-pagination select {
  height: 2rem;
  border: 1px solid rgba(15, 23, 42, 0.12);
  border-radius: 4px;
  background: white;
  color: #0f172a;
}
</style>
