export const generatorPreviewErrorCodes = {
  GENERATOR_PREVIEW_CREATE_FAILED: 4191,
  GENERATOR_SESSION_LIST_READ_FAILED: 4192,
  GENERATOR_SESSION_APPLY_FAILED: 4193,
  GENERATOR_SESSION_REVIEW_FAILED: 4194,
  GENERATOR_SESSION_CONFIRMATION_FAILED: 4195,
  GENERATOR_SCHEMA_NOT_FOUND: 4101,
  GENERATOR_SESSION_NOT_FOUND: 4102,
  GENERATOR_SESSION_REPORT_READ_FAILED: 4103,
  GENERATOR_SESSION_STALE: 4104,
  GENERATOR_SESSION_APPLY_CONFLICT: 4105,
  GENERATOR_SESSION_NOT_READY: 4106,
  GENERATOR_SESSION_REJECTED: 4107,
  GENERATOR_SESSION_REVIEW_REQUIRED: 4108,
  GENERATOR_SESSION_REVIEW_NOT_PENDING: 4109,
  GENERATOR_SESSION_CONFIRMATION_REQUIRED: 4110,
  GENERATOR_SESSION_CONFIRMATION_NOT_READY: 4111,
  GENERATOR_SESSION_SQL_PROPOSAL_NOT_READY: 4112,
  GENERATOR_SESSION_CONFIRMATION_HANDOFF_MISMATCH: 4113,
  GENERATOR_SESSION_BLOCKING_CONFLICTS: 4114,
} as const

const errorCodeKeyMap = {
  ...generatorPreviewErrorCodes,
  AUTH_ACCESS_TOKEN_REQUIRED: 1001,
  AUTH_ACCESS_TOKEN_INVALID: 1002,
  AUTH_REFRESH_TOKEN_REQUIRED: 1003,
  AUTH_REFRESH_TOKEN_INVALID: 1004,
  AUTH_REFRESH_TOKEN_EXPIRED: 1005,
  AUTH_INVALID_CREDENTIALS: 1006,
  AUTH_USER_DISABLED: 1007,
  AUTH_PERMISSION_DENIED: 1008,
  AUTH_SESSION_NOT_FOUND: 1009,
  AUTH_LOGIN_LOCKED: 1010,
  AUTH_TENANT_REQUIRED: 1011,
  AUTH_TENANT_INVALID: 1012,
  INTERNAL_ERROR: 9001,
  ROUTE_NOT_FOUND: 9002,
  RATE_LIMIT_EXCEEDED: 9003,
  CONFIG_INVALID: 9004,
  MODULE_REGISTRATION_FAILED: 9005,
  MODULE_FAILURE: 9006,
} as const

const errorCodeMessageMap = Object.fromEntries(
  Object.entries(errorCodeKeyMap).map(([key, value]) => [value, key]),
) as Record<number, string>

export const resolveApiErrorCode = (value: unknown): number | null => {
  if (typeof value === "number" && Number.isInteger(value)) {
    return value
  }

  if (
    typeof value === "string" &&
    value in errorCodeKeyMap
  ) {
    return errorCodeKeyMap[value as keyof typeof errorCodeKeyMap]
  }

  return null
}

export const resolveApiErrorCodeLabel = (value: number | null) =>
  value === null ? null : errorCodeMessageMap[value] ?? null
