// Canonical frontend record/status types still come from schema.
// OpenAPI-generated parallel types live under ./generated and are refreshed by
// `bun run openapi:types:generate` until 6C-3 is ready to switch the gateway.
export type {
  CustomerRecord,
  CustomerStatus,
  DepartmentDetailRecord,
  DepartmentRecord,
  DepartmentStatus,
  DictionaryItemRecord,
  DictionaryStatus,
  DictionaryTypeDetailRecord,
  DictionaryTypeRecord,
  FileRecord,
  MenuDetailRecord,
  MenuRecord,
  MenuStatus,
  MenuType,
  NotificationLevel,
  NotificationRecord,
  NotificationStatus,
  OperationLogRecord,
  OperationLogResult,
  PostRecord,
  PostStatus,
  RoleDataScope,
  RoleDetailRecord,
  RoleRecord,
  RoleStatus,
  SettingRecord,
  SettingStatus,
  TenantRecord,
  TenantStatus,
  UserRecord,
  UserStatus,
  WorkflowDefinitionRecord,
} from "@elysian/schema"
