/**
 * @generated by elysian-generator
 * schema: setting
 * path: modules/setting/setting-panel.vue
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

<script setup lang="ts">
import {
  ElyContextPanel,
  type ElyContextPanelCopy,
  ElyForm,
  type ElyFormCopy,
  type ElyFormField,
  type ElyFormValues,
} from "@elysian/ui-enterprise-vue"
import { computed, inject } from "vue"

import { WORKSPACE_STATE_KEY } from "@elysian/frontend-vue"
import {
  readInjectedValue,
  resolveSettingWorkspacePanelState,
} from "./setting-workspace"
import type { SettingRecord } from "./setting.schema"

type SettingWorkspaceTranslation = (
  key: string,
  params?: Record<string, unknown>,
) => string

interface SettingWorkspacePanelProps {
  t: SettingWorkspaceTranslation
  moduleReady: boolean
  authModuleReady: boolean
  isAuthenticated: boolean
  canEnterWorkspace: boolean
  canViewSettings: boolean
  canCreateSettings: boolean
  canUpdateSettings: boolean
  formCopy: ElyFormCopy
  contextPanelCopy?: ElyContextPanelCopy
  workspaceStateInjected?: boolean
}

const props = defineProps<SettingWorkspacePanelProps>()

const emit = defineEmits<{
  (e: "start-edit", setting: SettingRecord): void
  (e: "submit-form", values: ElyFormValues): void
  (e: "cancel-panel"): void
  (e: "confirm-delete", setting: SettingRecord): void
  (e: "cancel-delete"): void
}>()

const injectedWorkspaceState = inject(
  WORKSPACE_STATE_KEY,
  computed(() => null),
)

const resolvedSettingWorkspaceState = computed(() =>
  resolveSettingWorkspacePanelState(
    injectedWorkspaceState.value,
    Boolean(props.workspaceStateInjected),
  ),
)

const resolvedLoading = readInjectedValue(
  computed(() => resolvedSettingWorkspaceState.value?.settingLoading ?? null),
  false,
)
const resolvedDetailLoading = readInjectedValue(
  computed(
    () => resolvedSettingWorkspaceState.value?.settingDetailLoading ?? null,
  ),
  false,
)
const resolvedErrorMessage = readInjectedValue(
  computed(
    () => resolvedSettingWorkspaceState.value?.settingErrorMessage ?? null,
  ),
  "",
)
const resolvedDetailErrorMessage = readInjectedValue(
  computed(
    () =>
      resolvedSettingWorkspaceState.value?.settingDetailErrorMessage ?? null,
  ),
  "",
)
const resolvedPanelMode = readInjectedValue(
  computed(() => resolvedSettingWorkspaceState.value?.settingPanelMode ?? null),
  "detail" as "detail" | "create" | "edit",
)
const resolvedPanelTitle = readInjectedValue(
  computed(() => resolvedSettingWorkspaceState.value?.panelTitle ?? null),
  "",
)
const resolvedSelectedSetting = readInjectedValue(
  computed(() => resolvedSettingWorkspaceState.value?.selectedSetting ?? null),
  null as SettingRecord | null,
)
const resolvedFormFields = readInjectedValue(
  computed(() => resolvedSettingWorkspaceState.value?.formFields ?? null),
  [] as ElyFormField[],
)
const resolvedFormValues = readInjectedValue(
  computed(() => resolvedSettingWorkspaceState.value?.formValues ?? null),
  {} as ElyFormValues,
)

const resolvedPanelStatus = computed(() => {
  if (!props.moduleReady) return "module-offline"
  if (props.authModuleReady && !props.isAuthenticated)
    return "not-authenticated"
  if (props.canEnterWorkspace && !props.canViewSettings) return "no-permission"
  if (resolvedErrorMessage.value) return "error"
  if (resolvedDetailLoading.value && resolvedSelectedSetting.value)
    return "loading"
  if (resolvedDetailErrorMessage.value) return "detail-error"
  return "ready"
})

const resolvedPanelStatusMessage = computed(() => {
  switch (resolvedPanelStatus.value) {
    case "module-offline":
      return t("app.message.settingModuleOffline")
    case "not-authenticated":
      return t("app.message.settingSignInToLoad")
    case "no-permission":
      return t("app.message.settingNoListPermission")
    case "error":
      return resolvedErrorMessage.value
    case "loading":
      return t("app.setting.detailLoading")
    case "detail-error":
      return resolvedDetailErrorMessage.value
    default:
      return ""
  }
})

const panelVisible = computed(() => {
  if (resolvedPanelStatus.value !== "ready") return true
  return (
    resolvedPanelMode.value === "detail" ||
    resolvedPanelMode.value === "create" ||
    resolvedPanelMode.value === "edit" ||
    resolvedPanelMode.value === "delete-confirm"
  )
})

const resolvedPanelModeForContext = computed<
  "detail" | "edit" | "create" | "delete-confirm"
>(() => {
  if (resolvedPanelMode.value === "delete-confirm") return "delete-confirm"
  if (resolvedPanelMode.value === "edit") return "edit"
  if (resolvedPanelMode.value === "create") return "create"
  return "detail"
})
</script>

<template>
  <ElyContextPanel
    :visible="panelVisible"
    :title="resolvedPanelTitle"
    :mode="resolvedPanelModeForContext"
    :loading="resolvedLoading || resolvedDetailLoading"
    :copy="contextPanelCopy"
    @close="emit('cancel-panel')"
    @cancel="emit('cancel-panel')"
    @save="emit('submit-form', resolvedFormValues)"
    @delete="resolvedSelectedSetting && emit('confirm-delete', resolvedSelectedSetting)"
  >
    <template v-if="resolvedPanelStatus !== 'ready'">
      <div class="ely-panel-status">{{ resolvedPanelStatusMessage }}</div>
    </template>

    <template v-else-if="resolvedPanelMode === 'detail' && resolvedSelectedSetting">
      <ElyForm
        :fields="resolvedFormFields"
        :values="resolvedFormValues"
        readonly
        :loading="resolvedLoading || resolvedDetailLoading"
        :copy="formCopy"
      />
    </template>

    <template v-else-if="resolvedPanelMode === 'create' || resolvedPanelMode === 'edit'">
      <ElyForm
        :fields="resolvedFormFields"
        :values="resolvedFormValues"
        :loading="resolvedLoading || resolvedDetailLoading"
        :copy="formCopy"
        @submit="emit('submit-form', $event)"
        @cancel="emit('cancel-panel')"
      />
    </template>

    <template v-else-if="resolvedPanelMode === 'delete-confirm' && resolvedSelectedSetting">
      <p>{{ t("app.setting.deleteConfirmMessage", { name: resolvedSelectedSetting.name ?? resolvedSelectedSetting.id }) }}</p>
    </template>

    <template v-else>
      <p>{{ t("app.setting.detailEmptyDescription") }}</p>
    </template>
  </ElyContextPanel>
  </template>
