/**
 * @generated by elysian-generator
 * schema: setting
 * path: modules/setting/setting.schema.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import { settingModuleSchema as sourceModuleSchema } from "@elysian/schema"
import type { ModuleSchema } from "@elysian/schema"

export type SettingStatus = "active" | "disabled"

export interface SettingRecord {
  id: string
  key: string
  value: string
  description: string
  status: SettingStatus
  createdAt: string
  updatedAt: string
}

export const settingModuleSchema: ModuleSchema = sourceModuleSchema

export const moduleSchema = settingModuleSchema
