/**
 * @generated by elysian-generator
 * schema: setting
 * path: modules/setting/setting-workspace.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import type { FrontendWorkspaceStateContext } from "@elysian/frontend-vue"
import type { ElyFormField, ElyFormValues } from "@elysian/ui-enterprise-vue"
import type { ComputedRef } from "vue"
import { computed } from "vue"

import type { SettingRecord } from "./setting.schema"

export interface SettingWorkspaceMainInjectedState {
  settingErrorMessage: { value: string }
  settingLoading: { value: boolean }
  tableItems: { value: SettingRecord[] }
}

export interface SettingWorkspacePanelInjectedState
  extends SettingWorkspaceMainInjectedState {
  formFields: { value: ElyFormField[] }
  formValues: { value: ElyFormValues }
  panelDescription: { value: string }
  panelTitle: { value: string }
  settingDetailErrorMessage: { value: string }
  settingDetailLoading: { value: boolean }
  settingPanelMode: { value: "detail" | "create" | "edit" }
  selectedSetting: { value: SettingRecord | null }
}

const resolveSettingWorkspaceState = <TState>(
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
): TState | null => {
  if (!enabled || context?.kind !== "setting") {
    return null
  }

  return context.state as TState
}

export const resolveSettingWorkspaceMainState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveSettingWorkspaceState<SettingWorkspaceMainInjectedState>(
    context,
    enabled,
  )

export const resolveSettingWorkspacePanelState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveSettingWorkspaceState<SettingWorkspacePanelInjectedState>(
    context,
    enabled,
  )

export const readInjectedValue = <TValue>(
  state: ComputedRef<{ value: TValue } | null>,
  fallback: TValue,
) => computed(() => state.value?.value ?? fallback)

const normalizeText = (value: unknown) => String(value ?? "").trim()

const normalizeOptionalText = (value: unknown) => {
  const normalized = normalizeText(value)

  return normalized.length > 0 ? normalized : undefined
}

const normalizeNumber = (value: unknown, fallback = 0) => {
  const normalized =
    typeof value === "number" ? value : Number.parseInt(String(value ?? ""), 10)

  return Number.isFinite(normalized) ? normalized : fallback
}

export const createDefaultSettingDraft = () => ({
  key: "",
  value: "",
  description: "",
  status: "active",
})

export const filterSettingRecords = (
  items: SettingRecord[],
  query: Record<string, unknown>,
): SettingRecord[] => {
  const key = String(query.key ?? "")
    .trim()
    .toLowerCase()
  const value = String(query.value ?? "")
    .trim()
    .toLowerCase()
  const description = String(query.description ?? "")
    .trim()
    .toLowerCase()

  return items.filter((item) => {
    if (
      key.length > 0 &&
      !String(item.key ?? "")
        .toLowerCase()
        .includes(key)
    )
      return false
    if (
      value.length > 0 &&
      !String(item.value ?? "")
        .toLowerCase()
        .includes(value)
    )
      return false
    if (
      description.length > 0 &&
      !String(item.description ?? "")
        .toLowerCase()
        .includes(description)
    )
      return false
    if (
      query.status !== undefined &&
      query.status !== null &&
      query.status !== "" &&
      item.status !== query.status
    )
      return false

    return true
  })
}

export const resolveSettingSelection = (
  items: Array<Pick<SettingRecord, "id">>,
  selectedId: string | null,
): string | null => {
  if (items.length === 0) return null

  if (selectedId && items.some((item) => item.id === selectedId)) {
    return selectedId
  }

  return items[0]?.id ?? null
}

export const normalizeSettingPayload = (
  values: Record<string, unknown>,
):
  | { status: "valid"; payload: Record<string, unknown> }
  | { status: "invalid"; message: string } => {
  const keyValue = String(values.key ?? "").trim()

  if (keyValue.length === 0) {
    return { status: "invalid" as const, message: "Setting key is required" }
  }

  const valueValue = String(values.value ?? "").trim()

  if (valueValue.length === 0) {
    return { status: "invalid" as const, message: "Setting value is required" }
  }

  return {
    status: "valid" as const,
    payload: {
      key: keyValue,
      value: valueValue,
      description: normalizeOptionalText(values.description),
      status: values.status ?? "active",
    },
  }
}

export const toSettingEditDraft = (
  record: SettingRecord,
): Record<string, unknown> => ({
  key: record.key ?? "",
  value: record.value ?? "",
  description: record.description ?? "",
  status: record.status ?? "active",
})
