/**
 * @generated by elysian-generator
 * schema: post
 * path: modules/post/post-workspace.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import type { FrontendWorkspaceStateContext } from "@elysian/frontend-vue"
import type { ElyFormField, ElyFormValues } from "@elysian/ui-enterprise-vue"
import type { ComputedRef } from "vue"
import { computed } from "vue"

import type { PostRecord } from "./post.schema"

export interface PostWorkspaceMainInjectedState {
  postErrorMessage: { value: string }
  postLoading: { value: boolean }
  tableItems: { value: PostRecord[] }
}

export interface PostWorkspacePanelInjectedState
  extends PostWorkspaceMainInjectedState {
  formFields: { value: ElyFormField[] }
  formValues: { value: ElyFormValues }
  panelDescription: { value: string }
  panelTitle: { value: string }
  postDetailErrorMessage: { value: string }
  postDetailLoading: { value: boolean }
  postPanelMode: { value: "detail" | "create" | "edit" }
  selectedPost: { value: PostRecord | null }
}

const resolvePostWorkspaceState = <TState>(
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
): TState | null => {
  if (!enabled || context?.kind !== "post") {
    return null
  }

  return context.state as TState
}

export const resolvePostWorkspaceMainState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) => resolvePostWorkspaceState<PostWorkspaceMainInjectedState>(context, enabled)

export const resolvePostWorkspacePanelState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolvePostWorkspaceState<PostWorkspacePanelInjectedState>(context, enabled)

export const readInjectedValue = <TValue>(
  state: ComputedRef<{ value: TValue } | null>,
  fallback: TValue,
) => computed(() => state.value?.value ?? fallback)

const normalizeText = (value: unknown) => String(value ?? "").trim()

const normalizeOptionalText = (value: unknown) => {
  const normalized = normalizeText(value)

  return normalized.length > 0 ? normalized : undefined
}

const normalizeNumber = (value: unknown, fallback = 0) => {
  const normalized =
    typeof value === "number" ? value : Number.parseInt(String(value ?? ""), 10)

  return Number.isFinite(normalized) ? normalized : fallback
}

export const createDefaultPostDraft = () => ({
  code: "",
  name: "",
  sort: 0,
  status: "active",
  remark: "",
})

export const filterPostRecords = (
  items: PostRecord[],
  query: Record<string, unknown>,
): PostRecord[] => {
  const code = String(query.code ?? "")
    .trim()
    .toLowerCase()
  const name = String(query.name ?? "")
    .trim()
    .toLowerCase()

  return items.filter((item) => {
    if (
      code.length > 0 &&
      !String(item.code ?? "")
        .toLowerCase()
        .includes(code)
    )
      return false
    if (
      name.length > 0 &&
      !String(item.name ?? "")
        .toLowerCase()
        .includes(name)
    )
      return false
    if (
      query.status !== undefined &&
      query.status !== null &&
      query.status !== "" &&
      item.status !== query.status
    )
      return false

    return true
  })
}

export const resolvePostSelection = (
  items: Array<Pick<PostRecord, "id">>,
  selectedId: string | null,
): string | null => {
  if (items.length === 0) return null

  if (selectedId && items.some((item) => item.id === selectedId)) {
    return selectedId
  }

  return items[0]?.id ?? null
}

export const normalizePostPayload = (
  values: Record<string, unknown>,
):
  | { status: "valid"; payload: Record<string, unknown> }
  | { status: "invalid"; message: string } => {
  const codeValue = String(values.code ?? "").trim()

  if (codeValue.length === 0) {
    return { status: "invalid" as const, message: "Post code is required" }
  }

  const nameValue = String(values.name ?? "").trim()

  if (nameValue.length === 0) {
    return { status: "invalid" as const, message: "Post name is required" }
  }

  return {
    status: "valid" as const,
    payload: {
      code: codeValue,
      name: nameValue,
      sort: normalizeNumber(values.sort, 0),
      status: values.status ?? "active",
      remark: normalizeOptionalText(values.remark),
    },
  }
}

export const toPostEditDraft = (
  record: PostRecord,
): Record<string, unknown> => ({
  code: record.code ?? "",
  name: record.name ?? "",
  sort: record.sort ?? 0,
  status: record.status ?? "active",
  remark: record.remark ?? "",
})
