/**
 * @generated by elysian-generator
 * schema: post
 * path: modules/post/post.schema.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import { postModuleSchema as sourceModuleSchema } from "@elysian/schema"
import type { ModuleSchema } from "@elysian/schema"

export type PostStatus = "active" | "disabled"

export interface PostRecord {
  id: string
  code: string
  name: string
  sort: number
  status: PostStatus
  remark: string
  createdAt: string
  updatedAt: string
}

export const postModuleSchema: ModuleSchema = sourceModuleSchema

export const moduleSchema = postModuleSchema
