/**
 * @generated by elysian-generator
 * schema: post
 * path: modules/post/post-panel.vue
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

<script setup lang="ts">
import {
  ElyContextPanel,
  type ElyContextPanelCopy,
  ElyForm,
  type ElyFormCopy,
  type ElyFormField,
  type ElyFormValues,
} from "@elysian/ui-enterprise-vue"
import { computed, inject } from "vue"

import { WORKSPACE_STATE_KEY } from "@elysian/frontend-vue"
import {
  readInjectedValue,
  resolvePostWorkspacePanelState,
} from "./post-workspace"
import type { PostRecord } from "./post.schema"

type PostWorkspaceTranslation = (
  key: string,
  params?: Record<string, unknown>,
) => string

interface PostWorkspacePanelProps {
  t: PostWorkspaceTranslation
  moduleReady: boolean
  authModuleReady: boolean
  isAuthenticated: boolean
  canEnterWorkspace: boolean
  canViewPosts: boolean
  canCreatePosts: boolean
  canUpdatePosts: boolean
  formCopy: ElyFormCopy
  contextPanelCopy?: ElyContextPanelCopy
  workspaceStateInjected?: boolean
}

const props = defineProps<PostWorkspacePanelProps>()

const emit = defineEmits<{
  (e: "start-edit", post: PostRecord): void
  (e: "submit-form", values: ElyFormValues): void
  (e: "cancel-panel"): void
  (e: "confirm-delete", post: PostRecord): void
  (e: "cancel-delete"): void
}>()

const injectedWorkspaceState = inject(
  WORKSPACE_STATE_KEY,
  computed(() => null),
)

const resolvedPostWorkspaceState = computed(() =>
  resolvePostWorkspacePanelState(
    injectedWorkspaceState.value,
    Boolean(props.workspaceStateInjected),
  ),
)

const resolvedLoading = readInjectedValue(
  computed(() => resolvedPostWorkspaceState.value?.postLoading ?? null),
  false,
)
const resolvedDetailLoading = readInjectedValue(
  computed(() => resolvedPostWorkspaceState.value?.postDetailLoading ?? null),
  false,
)
const resolvedErrorMessage = readInjectedValue(
  computed(() => resolvedPostWorkspaceState.value?.postErrorMessage ?? null),
  "",
)
const resolvedDetailErrorMessage = readInjectedValue(
  computed(
    () => resolvedPostWorkspaceState.value?.postDetailErrorMessage ?? null,
  ),
  "",
)
const resolvedPanelMode = readInjectedValue(
  computed(() => resolvedPostWorkspaceState.value?.postPanelMode ?? null),
  "detail" as "detail" | "create" | "edit",
)
const resolvedPanelTitle = readInjectedValue(
  computed(() => resolvedPostWorkspaceState.value?.panelTitle ?? null),
  "",
)
const resolvedSelectedPost = readInjectedValue(
  computed(() => resolvedPostWorkspaceState.value?.selectedPost ?? null),
  null as PostRecord | null,
)
const resolvedFormFields = readInjectedValue(
  computed(() => resolvedPostWorkspaceState.value?.formFields ?? null),
  [] as ElyFormField[],
)
const resolvedFormValues = readInjectedValue(
  computed(() => resolvedPostWorkspaceState.value?.formValues ?? null),
  {} as ElyFormValues,
)

const resolvedPanelStatus = computed(() => {
  if (!props.moduleReady) return "module-offline"
  if (props.authModuleReady && !props.isAuthenticated)
    return "not-authenticated"
  if (props.canEnterWorkspace && !props.canViewPosts) return "no-permission"
  if (resolvedErrorMessage.value) return "error"
  if (resolvedDetailLoading.value && resolvedSelectedPost.value)
    return "loading"
  if (resolvedDetailErrorMessage.value) return "detail-error"
  return "ready"
})

const resolvedPanelStatusMessage = computed(() => {
  switch (resolvedPanelStatus.value) {
    case "module-offline":
      return t("app.message.postModuleOffline")
    case "not-authenticated":
      return t("app.message.postSignInToLoad")
    case "no-permission":
      return t("app.message.postNoListPermission")
    case "error":
      return resolvedErrorMessage.value
    case "loading":
      return t("app.post.detailLoading")
    case "detail-error":
      return resolvedDetailErrorMessage.value
    default:
      return ""
  }
})

const panelVisible = computed(() => {
  if (resolvedPanelStatus.value !== "ready") return true
  return (
    resolvedPanelMode.value === "detail" ||
    resolvedPanelMode.value === "create" ||
    resolvedPanelMode.value === "edit" ||
    resolvedPanelMode.value === "delete-confirm"
  )
})

const resolvedPanelModeForContext = computed<
  "detail" | "edit" | "create" | "delete-confirm"
>(() => {
  if (resolvedPanelMode.value === "delete-confirm") return "delete-confirm"
  if (resolvedPanelMode.value === "edit") return "edit"
  if (resolvedPanelMode.value === "create") return "create"
  return "detail"
})
</script>

<template>
  <ElyContextPanel
    :visible="panelVisible"
    :title="resolvedPanelTitle"
    :mode="resolvedPanelModeForContext"
    :loading="resolvedLoading || resolvedDetailLoading"
    :copy="contextPanelCopy"
    @close="emit('cancel-panel')"
    @cancel="emit('cancel-panel')"
    @save="emit('submit-form', resolvedFormValues)"
    @delete="resolvedSelectedPost && emit('confirm-delete', resolvedSelectedPost)"
  >
    <template v-if="resolvedPanelStatus !== 'ready'">
      <div class="ely-panel-status">{{ resolvedPanelStatusMessage }}</div>
    </template>

    <template v-else-if="resolvedPanelMode === 'detail' && resolvedSelectedPost">
      <ElyForm
        :fields="resolvedFormFields"
        :values="resolvedFormValues"
        readonly
        :loading="resolvedLoading || resolvedDetailLoading"
        :copy="formCopy"
      />
    </template>

    <template v-else-if="resolvedPanelMode === 'create' || resolvedPanelMode === 'edit'">
      <ElyForm
        :fields="resolvedFormFields"
        :values="resolvedFormValues"
        :loading="resolvedLoading || resolvedDetailLoading"
        :copy="formCopy"
        @submit="emit('submit-form', $event)"
        @cancel="emit('cancel-panel')"
      />
    </template>

    <template v-else-if="resolvedPanelMode === 'delete-confirm' && resolvedSelectedPost">
      <p>{{ t("app.post.deleteConfirmMessage", { name: resolvedSelectedPost.name ?? resolvedSelectedPost.id }) }}</p>
    </template>

    <template v-else>
      <p>{{ t("app.post.detailEmptyDescription") }}</p>
    </template>
  </ElyContextPanel>
  </template>
