/**
 * @generated by elysian-generator
 * schema: tenant
 * path: modules/tenant/tenant.schema.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import { tenantModuleSchema as sourceModuleSchema } from "@elysian/schema"
import type { ModuleSchema } from "@elysian/schema"

export type TenantStatus = "active" | "suspended"

export interface TenantRecord {
  id: string
  code: string
  name: string
  status: TenantStatus
  createdAt: string
  updatedAt: string
}

export const tenantModuleSchema: ModuleSchema = sourceModuleSchema

export const moduleSchema = tenantModuleSchema
