/**
 * @generated by elysian-generator
 * schema: tenant
 * path: modules/tenant/tenant-workspace.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import type { FrontendWorkspaceStateContext } from "@elysian/frontend-vue"
import type { ElyFormField, ElyFormValues } from "@elysian/ui-enterprise-vue"
import type { ComputedRef } from "vue"
import { computed } from "vue"

import type { TenantRecord } from "./tenant.schema"

export interface TenantWorkspaceMainInjectedState {
  tenantErrorMessage: { value: string }
  tenantLoading: { value: boolean }
  tableItems: { value: TenantRecord[] }
}

export interface TenantWorkspacePanelInjectedState
  extends TenantWorkspaceMainInjectedState {
  formFields: { value: ElyFormField[] }
  formValues: { value: ElyFormValues }
  panelDescription: { value: string }
  panelTitle: { value: string }
  tenantDetailErrorMessage: { value: string }
  tenantDetailLoading: { value: boolean }
  tenantPanelMode: { value: "detail" | "create" | "edit" }
  selectedTenant: { value: TenantRecord | null }
}

const resolveTenantWorkspaceState = <TState>(
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
): TState | null => {
  if (!enabled || context?.kind !== "tenant") {
    return null
  }

  return context.state as TState
}

export const resolveTenantWorkspaceMainState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveTenantWorkspaceState<TenantWorkspaceMainInjectedState>(
    context,
    enabled,
  )

export const resolveTenantWorkspacePanelState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveTenantWorkspaceState<TenantWorkspacePanelInjectedState>(
    context,
    enabled,
  )

export const readInjectedValue = <TValue>(
  state: ComputedRef<{ value: TValue } | null>,
  fallback: TValue,
) => computed(() => state.value?.value ?? fallback)

const normalizeText = (value: unknown) => String(value ?? "").trim()

const normalizeOptionalText = (value: unknown) => {
  const normalized = normalizeText(value)

  return normalized.length > 0 ? normalized : undefined
}

const normalizeNumber = (value: unknown, fallback = 0) => {
  const normalized =
    typeof value === "number" ? value : Number.parseInt(String(value ?? ""), 10)

  return Number.isFinite(normalized) ? normalized : fallback
}

export const createDefaultTenantDraft = () => ({
  code: "",
  name: "",
  status: "active",
})

export const filterTenantRecords = (
  items: TenantRecord[],
  query: Record<string, unknown>,
): TenantRecord[] => {
  const code = String(query.code ?? "")
    .trim()
    .toLowerCase()
  const name = String(query.name ?? "")
    .trim()
    .toLowerCase()

  return items.filter((item) => {
    if (
      code.length > 0 &&
      !String(item.code ?? "")
        .toLowerCase()
        .includes(code)
    )
      return false
    if (
      name.length > 0 &&
      !String(item.name ?? "")
        .toLowerCase()
        .includes(name)
    )
      return false
    if (
      query.status !== undefined &&
      query.status !== null &&
      query.status !== "" &&
      item.status !== query.status
    )
      return false

    return true
  })
}

export const resolveTenantSelection = (
  items: Array<Pick<TenantRecord, "id">>,
  selectedId: string | null,
): string | null => {
  if (items.length === 0) return null

  if (selectedId && items.some((item) => item.id === selectedId)) {
    return selectedId
  }

  return items[0]?.id ?? null
}

export const normalizeTenantPayload = (
  values: Record<string, unknown>,
):
  | { status: "valid"; payload: Record<string, unknown> }
  | { status: "invalid"; message: string } => {
  const codeValue = String(values.code ?? "").trim()

  if (codeValue.length === 0) {
    return { status: "invalid" as const, message: "Tenant code is required" }
  }

  const nameValue = String(values.name ?? "").trim()

  if (nameValue.length === 0) {
    return { status: "invalid" as const, message: "Tenant name is required" }
  }

  return {
    status: "valid" as const,
    payload: {
      code: codeValue,
      name: nameValue,
      status: values.status ?? "active",
    },
  }
}

export const toTenantEditDraft = (
  record: TenantRecord,
): Record<string, unknown> => ({
  code: record.code ?? "",
  name: record.name ?? "",
  status: record.status ?? "active",
})
