/**
 * @generated by elysian-generator
 * schema: tenant
 * path: modules/tenant/tenant.page.vue
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

<script setup lang="ts">
import {
  ElyCrudWorkbench,
  type ElyCrudWorkspaceCopy,
  type ElyTableColumn,
} from "@elysian/ui-enterprise-vue"
import { computed, inject } from "vue"

import { WORKSPACE_STATE_KEY } from "@elysian/frontend-vue"
import {
  readInjectedValue,
  resolveTenantWorkspaceMainState,
} from "./tenant-workspace"
import type { TenantRecord } from "./tenant.schema"

type TenantWorkspaceTranslation = (
  key: string,
  params?: Record<string, unknown>,
) => string

interface TenantWorkspaceMainProps {
  t: TenantWorkspaceTranslation
  tableColumns: ElyTableColumn[]
  emptyTitle: string
  emptyDescription: string
  copy: ElyCrudWorkspaceCopy
  workspaceStateInjected?: boolean
}

const props = defineProps<TenantWorkspaceMainProps>()

const emit = defineEmits<{
  (e: "row-click", row: TenantRecord): void
  (e: "search", value: string): void
}>()

const injectedWorkspaceState = inject(
  WORKSPACE_STATE_KEY,
  computed(() => null),
)

const resolvedTenantWorkspaceState = computed(() =>
  resolveTenantWorkspaceMainState(
    injectedWorkspaceState.value,
    Boolean(props.workspaceStateInjected),
  ),
)

const resolvedLoading = readInjectedValue(
  computed(() => resolvedTenantWorkspaceState.value?.tenantLoading ?? null),
  false,
)
const resolvedItems = readInjectedValue(
  computed(() => resolvedTenantWorkspaceState.value?.tableItems ?? null),
  [] as TenantRecord[],
)

const panelTitle = computed(() => props.t("app.tenant.workspaceTitle"))

const handleSearch = (value: string) => {
  emit("search", value)
}

const handleRowClick = (row: Record<string, unknown>) => {
  const rowId = String(row.id ?? "")
  const tenant = resolvedItems.value.find(
    (item: TenantRecord) => item.id === rowId,
  )
  if (tenant) {
    emit("row-click", tenant)
  }
}
</script>

<template>
  <ElyCrudWorkbench
    :title="panelTitle"
    :table-columns="tableColumns"
    :items="resolvedItems"
    :table-loading="resolvedLoading"
    :table-actions="[]"
    :search-placeholder="t('app.tenant.searchPlaceholder', '搜索租户...')"
    :empty-title="emptyTitle"
    :empty-description="emptyDescription"
    :copy="copy"
    row-key="id"
    @search="handleSearch"
    @row-click="handleRowClick"
  />
</template>
