export const errorCodes = {
  AUTH_ACCESS_TOKEN_REQUIRED: 1001,
  AUTH_ACCESS_TOKEN_INVALID: 1002,
  AUTH_REFRESH_TOKEN_REQUIRED: 1003,
  AUTH_REFRESH_TOKEN_INVALID: 1004,
  AUTH_REFRESH_TOKEN_EXPIRED: 1005,
  AUTH_INVALID_CREDENTIALS: 1006,
  AUTH_USER_DISABLED: 1007,
  AUTH_PERMISSION_DENIED: 1008,
  AUTH_SESSION_NOT_FOUND: 1009,
  AUTH_LOGIN_LOCKED: 1010,
  AUTH_TENANT_REQUIRED: 1011,
  AUTH_TENANT_INVALID: 1012,

  CUSTOMER_NOT_FOUND: 2001,
  CUSTOMER_NAME_REQUIRED: 2002,

  USER_NOT_FOUND: 3001,
  USER_USERNAME_REQUIRED: 3002,
  USER_DISPLAY_NAME_REQUIRED: 3003,
  USER_PASSWORD_REQUIRED: 3004,
  USER_USERNAME_CONFLICT: 3005,

  ROLE_NOT_FOUND: 3101,
  ROLE_CODE_REQUIRED: 3102,
  ROLE_NAME_REQUIRED: 3103,
  ROLE_CODE_CONFLICT: 3104,
  ROLE_SYSTEM_IMMUTABLE: 3105,
  ROLE_PERMISSION_CODES_INVALID: 3106,
  ROLE_USER_IDS_INVALID: 3107,
  ROLE_DEPARTMENT_IDS_INVALID: 3108,
  ROLE_DATA_SCOPE_INVALID: 3109,

  MENU_NOT_FOUND: 3201,
  MENU_CODE_REQUIRED: 3202,
  MENU_NAME_REQUIRED: 3203,
  MENU_CODE_CONFLICT: 3204,
  MENU_PARENT_INVALID: 3205,
  MENU_PERMISSION_CODE_INVALID: 3206,
  MENU_ROLE_IDS_INVALID: 3207,

  DEPARTMENT_NOT_FOUND: 3301,
  DEPARTMENT_CODE_REQUIRED: 3302,
  DEPARTMENT_NAME_REQUIRED: 3303,
  DEPARTMENT_CODE_CONFLICT: 3304,
  DEPARTMENT_PARENT_INVALID: 3305,
  DEPARTMENT_USER_IDS_INVALID: 3306,

  POST_NOT_FOUND: 3401,
  POST_CODE_REQUIRED: 3402,
  POST_NAME_REQUIRED: 3403,
  POST_CODE_CONFLICT: 3404,

  DICTIONARY_TYPE_NOT_FOUND: 3501,
  DICTIONARY_TYPE_CODE_REQUIRED: 3502,
  DICTIONARY_TYPE_NAME_REQUIRED: 3503,
  DICTIONARY_TYPE_CODE_CONFLICT: 3504,
  DICTIONARY_ITEM_NOT_FOUND: 3511,
  DICTIONARY_ITEM_TYPE_REQUIRED: 3512,
  DICTIONARY_ITEM_VALUE_REQUIRED: 3513,
  DICTIONARY_ITEM_LABEL_REQUIRED: 3514,
  DICTIONARY_ITEM_VALUE_CONFLICT: 3515,
  DICTIONARY_ITEM_TYPE_INVALID: 3516,

  SETTING_NOT_FOUND: 3601,
  SETTING_KEY_REQUIRED: 3602,
  SETTING_VALUE_REQUIRED: 3603,
  SETTING_KEY_CONFLICT: 3604,

  TENANT_NOT_FOUND: 3701,
  TENANT_CODE_REQUIRED: 3702,
  TENANT_NAME_REQUIRED: 3703,
  TENANT_CODE_CONFLICT: 3704,
  TENANT_SUPER_ADMIN_REQUIRED: 3705,

  OPERATION_LOG_NOT_FOUND: 3801,

  FILE_NOT_FOUND: 3901,
  FILE_UPLOAD_REQUIRED: 3902,
  FILE_CONTENT_NOT_FOUND: 3903,

  NOTIFICATION_NOT_FOUND: 3951,
  NOTIFICATION_RECIPIENT_REQUIRED: 3952,
  NOTIFICATION_TITLE_REQUIRED: 3953,
  NOTIFICATION_CONTENT_REQUIRED: 3954,
  NOTIFICATION_RECIPIENT_INVALID: 3955,

  WORKFLOW_TENANT_CONTEXT_REQUIRED: 4001,
  WORKFLOW_DEFINITION_NOT_FOUND: 4002,
  WORKFLOW_DEFINITION_KEY_REQUIRED: 4003,
  WORKFLOW_DEFINITION_NAME_REQUIRED: 4004,
  WORKFLOW_DEFINITION_INVALID: 4005,
  WORKFLOW_DEFINITION_KEY_CONFLICT: 4006,
  WORKFLOW_DEFINITION_DISABLED: 4007,
  WORKFLOW_INSTANCE_NOT_FOUND: 4011,
  WORKFLOW_INSTANCE_DEFINITION_REQUIRED: 4012,
  WORKFLOW_INSTANCE_NOT_RUNNING: 4013,
  WORKFLOW_INSTANCE_VARIABLES_INVALID: 4014,
  WORKFLOW_TASK_NOT_FOUND: 4021,
  WORKFLOW_TASK_NOT_TODO: 4022,
  WORKFLOW_TASK_ALREADY_CLAIMED: 4023,
  WORKFLOW_TASK_CLAIM_FORBIDDEN: 4024,
  WORKFLOW_TASK_ASSIGNEE_MISMATCH: 4025,
  WORKFLOW_DEFINITION_RUNTIME_UNSUPPORTED: 4091,

  GENERATOR_SCHEMA_NOT_FOUND: 4101,
  GENERATOR_SESSION_NOT_FOUND: 4102,
  GENERATOR_SESSION_REPORT_READ_FAILED: 4103,
  GENERATOR_SESSION_STALE: 4104,
  GENERATOR_SESSION_APPLY_CONFLICT: 4105,
  GENERATOR_SESSION_NOT_READY: 4106,
  GENERATOR_SESSION_REJECTED: 4107,
  GENERATOR_SESSION_REVIEW_REQUIRED: 4108,
  GENERATOR_SESSION_REVIEW_NOT_PENDING: 4109,
  GENERATOR_SESSION_CONFIRMATION_REQUIRED: 4110,
  GENERATOR_SESSION_CONFIRMATION_NOT_READY: 4111,
  GENERATOR_SESSION_SQL_PROPOSAL_NOT_READY: 4112,
  GENERATOR_SESSION_CONFIRMATION_HANDOFF_MISMATCH: 4113,
  GENERATOR_SESSION_BLOCKING_CONFLICTS: 4114,

  INTERNAL_ERROR: 9001,
  ROUTE_NOT_FOUND: 9002,
  RATE_LIMIT_EXCEEDED: 9003,
  CONFIG_INVALID: 9004,
  MODULE_REGISTRATION_FAILED: 9005,
  MODULE_FAILURE: 9006,
} as const

export type AppErrorCodeKey = keyof typeof errorCodes
export type AppErrorCode = (typeof errorCodes)[AppErrorCodeKey]

const isFourDigitAppErrorCode = (value: number) =>
  Number.isInteger(value) && value >= 1000 && value <= 9999

const assertValidErrorCodeRegistry = () => {
  const entries = Object.entries(errorCodes)
  const seenCodes = new Map<number, string>()

  for (const [key, code] of entries) {
    if (!isFourDigitAppErrorCode(code)) {
      throw new Error(`Invalid app error code for ${key}: ${String(code)}`)
    }

    const existingKey = seenCodes.get(code)
    if (existingKey) {
      throw new Error(
        `Duplicate app error code ${String(code)} for ${existingKey} and ${key}`,
      )
    }

    seenCodes.set(code, key)
  }
}

assertValidErrorCodeRegistry()
