/**
 * @generated by elysian-generator
 * schema: menu
 * path: modules/menu/menu.schema.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import { menuModuleSchema as sourceModuleSchema } from "@elysian/schema"
import type { ModuleSchema } from "@elysian/schema"

export type MenuType = "directory" | "menu" | "button"

export type MenuStatus = "active" | "disabled"

export interface MenuRecord {
  id: string
  parentId: string
  type: MenuType
  code: string
  name: string
  path: string
  component: string
  icon: string
  sort: number
  isVisible: boolean
  status: MenuStatus
  permissionCode: string
  createdAt: string
  updatedAt: string
}

export const menuModuleSchema: ModuleSchema = sourceModuleSchema

export const moduleSchema = menuModuleSchema
