/**
 * @generated by elysian-generator
 * schema: menu
 * path: modules/menu/menu-workspace.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import type { FrontendWorkspaceStateContext } from "@elysian/frontend-vue"
import type { ElyFormField, ElyFormValues } from "@elysian/ui-enterprise-vue"
import type { ComputedRef } from "vue"
import { computed } from "vue"

import type { MenuRecord } from "./menu.schema"

export interface MenuWorkspaceMainInjectedState {
  menuErrorMessage: { value: string }
  menuLoading: { value: boolean }
  tableItems: { value: MenuRecord[] }
}

export interface MenuWorkspacePanelInjectedState
  extends MenuWorkspaceMainInjectedState {
  formFields: { value: ElyFormField[] }
  formValues: { value: ElyFormValues }
  panelDescription: { value: string }
  panelTitle: { value: string }
  menuDetailErrorMessage: { value: string }
  menuDetailLoading: { value: boolean }
  menuPanelMode: { value: "detail" | "create" | "edit" }
  selectedMenu: { value: MenuRecord | null }
  parentLookup?: { value: Map<string, unknown> }
  selectedMenuDetail?: { value: { roleIds?: string[] } | null }
}

const resolveMenuWorkspaceState = <TState>(
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
): TState | null => {
  if (!enabled || context?.kind !== "menu") {
    return null
  }

  return context.state as TState
}

export const resolveMenuWorkspaceMainState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) => resolveMenuWorkspaceState<MenuWorkspaceMainInjectedState>(context, enabled)

export const resolveMenuWorkspacePanelState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveMenuWorkspaceState<MenuWorkspacePanelInjectedState>(context, enabled)

export const readInjectedValue = <TValue>(
  state: ComputedRef<{ value: TValue } | null>,
  fallback: TValue,
) => computed(() => state.value?.value ?? fallback)

const normalizeText = (value: unknown) => String(value ?? "").trim()

const normalizeOptionalText = (value: unknown) => {
  const normalized = normalizeText(value)

  return normalized.length > 0 ? normalized : undefined
}

const normalizeNumber = (value: unknown, fallback = 0) => {
  const normalized =
    typeof value === "number" ? value : Number.parseInt(String(value ?? ""), 10)

  return Number.isFinite(normalized) ? normalized : fallback
}

const normalizeJsonInput = (
  value: unknown,
):
  | { status: "valid"; value: Record<string, unknown> | null }
  | { status: "invalid" } => {
  if (value === null || value === undefined) {
    return { status: "valid", value: null }
  }

  if (typeof value === "string") {
    const normalized = value.trim()

    if (normalized.length === 0) {
      return { status: "valid", value: null }
    }

    try {
      const parsed: unknown = JSON.parse(normalized)

      if (
        typeof parsed === "object" &&
        parsed !== null &&
        !Array.isArray(parsed)
      ) {
        return {
          status: "valid",
          value: parsed as Record<string, unknown>,
        }
      }

      return { status: "invalid" }
    } catch {
      return { status: "invalid" }
    }
  }

  if (typeof value === "object" && !Array.isArray(value)) {
    return {
      status: "valid",
      value: value as Record<string, unknown>,
    }
  }

  return { status: "invalid" }
}

const stringifyJsonValue = (value: unknown) => {
  if (value === null || value === undefined) {
    return ""
  }

  return JSON.stringify(value, null, 2)
}

export const createDefaultMenuDraft = () => ({
  parentId: "",
  type: "directory",
  code: "",
  name: "",
  path: "",
  component: "",
  icon: "",
  sort: 0,
  isVisible: false,
  status: "active",
  permissionCode: "",
})

export const filterMenuRecords = (
  items: MenuRecord[],
  query: Record<string, unknown>,
): MenuRecord[] => {
  const code = String(query.code ?? "")
    .trim()
    .toLowerCase()
  const name = String(query.name ?? "")
    .trim()
    .toLowerCase()
  const path = String(query.path ?? "")
    .trim()
    .toLowerCase()
  const component = String(query.component ?? "")
    .trim()
    .toLowerCase()
  const icon = String(query.icon ?? "")
    .trim()
    .toLowerCase()
  const permissionCode = String(query.permissionCode ?? "")
    .trim()
    .toLowerCase()

  return items.filter((item) => {
    if (
      query.type !== undefined &&
      query.type !== null &&
      query.type !== "" &&
      item.type !== query.type
    )
      return false
    if (
      code.length > 0 &&
      !String(item.code ?? "")
        .toLowerCase()
        .includes(code)
    )
      return false
    if (
      name.length > 0 &&
      !String(item.name ?? "")
        .toLowerCase()
        .includes(name)
    )
      return false
    if (
      path.length > 0 &&
      !String(item.path ?? "")
        .toLowerCase()
        .includes(path)
    )
      return false
    if (
      component.length > 0 &&
      !String(item.component ?? "")
        .toLowerCase()
        .includes(component)
    )
      return false
    if (
      icon.length > 0 &&
      !String(item.icon ?? "")
        .toLowerCase()
        .includes(icon)
    )
      return false
    if (
      query.status !== undefined &&
      query.status !== null &&
      query.status !== "" &&
      item.status !== query.status
    )
      return false
    if (
      permissionCode.length > 0 &&
      !String(item.permissionCode ?? "")
        .toLowerCase()
        .includes(permissionCode)
    )
      return false

    return true
  })
}

export const resolveMenuSelection = (
  items: Array<Pick<MenuRecord, "id">>,
  selectedId: string | null,
): string | null => {
  if (items.length === 0) return null

  if (selectedId && items.some((item) => item.id === selectedId)) {
    return selectedId
  }

  return items[0]?.id ?? null
}

export const normalizeMenuPayload = (
  values: Record<string, unknown>,
):
  | { status: "valid"; payload: Record<string, unknown> }
  | { status: "invalid"; message: string } => {
  const codeValue = String(values.code ?? "").trim()

  if (codeValue.length === 0) {
    return { status: "invalid" as const, message: "Menu code is required" }
  }

  const nameValue = String(values.name ?? "").trim()

  if (nameValue.length === 0) {
    return { status: "invalid" as const, message: "Menu name is required" }
  }

  return {
    status: "valid" as const,
    payload: {
      parentId: normalizeOptionalText(values.parentId),
      type: values.type ?? "directory",
      code: codeValue,
      name: nameValue,
      path: normalizeOptionalText(values.path),
      component: normalizeOptionalText(values.component),
      icon: normalizeOptionalText(values.icon),
      sort: normalizeNumber(values.sort, 0),
      isVisible: values.isVisible ?? false,
      status: values.status ?? "active",
      permissionCode: normalizeOptionalText(values.permissionCode),
    },
  }
}

export const toMenuEditDraft = (
  record: MenuRecord,
): Record<string, unknown> => ({
  parentId: record.parentId ?? "",
  type: record.type ?? "directory",
  code: record.code ?? "",
  name: record.name ?? "",
  path: record.path ?? "",
  component: record.component ?? "",
  icon: record.icon ?? "",
  sort: record.sort ?? 0,
  isVisible: record.isVisible ?? false,
  status: record.status ?? "active",
  permissionCode: record.permissionCode ?? "",
})
