import { computed } from "vue"

import { read, type UseExampleShellBindingsOptions } from "./use-example-shell-binding-types"

export const useExampleShellWorkspaceSecondaryBindings = ({
  t,
  locale,
  currentWorkspaceKind,
  isRuntimeShellTab,
  selectedNavigationItemName,
  currentNavigationPath,
  authStatusLabel,
  currentModuleCodeLabel,
  dictionaryModuleReady,
  authModuleReady,
  isAuthenticated,
  canEnterDictionaryWorkspace,
  canViewDictionaries,
  canCreateDictionaryTypes,
  canUpdateDictionaryTypes,
  dictionaryLoading,
  dictionaryDetailLoading,
  dictionaryErrorMessage,
  dictionaryDetailErrorMessage,
  dictionaryPanelMode,
  dictionaryPanelTitle,
  dictionaryPanelDescription,
  selectedDictionaryType,
  selectedDictionaryTypeItems,
  enterpriseDictionaryFormFields,
  enterpriseDictionaryFormValues,
  enterpriseFormCopy,
  localizeDictionaryStatus,
  departmentModuleReady,
  canEnterDepartmentWorkspace,
  canViewDepartments,
  canCreateDepartments,
  canUpdateDepartments,
  departmentLoading,
  departmentDetailLoading,
  departmentErrorMessage,
  departmentDetailErrorMessage,
  departmentPanelMode,
  departmentPanelTitle,
  departmentPanelDescription,
  selectedDepartment,
  selectedDepartmentDetail,
  enterpriseDepartmentFormFields,
  enterpriseDepartmentFormValues,
  departmentParentLookup,
  menuModuleReady,
  canEnterMenuWorkspace,
  canViewMenus,
  canCreateMenus,
  canUpdateMenus,
  menuLoading,
  menuDetailLoading,
  menuErrorMessage,
  menuDetailErrorMessage,
  menuPanelMode,
  menuPanelTitle,
  menuPanelDescription,
  selectedMenu,
  selectedMenuDetail,
  enterpriseMenuFormFields,
  enterpriseMenuFormValues,
  menuParentLookup,
  notificationModuleReady,
  canEnterNotificationWorkspace,
  canViewNotifications,
  canCreateNotifications,
  canUpdateNotifications,
  notificationLoading,
  notificationDetailLoading,
  notificationErrorMessage,
  notificationDetailErrorMessage,
  notificationPanelMode,
  notificationPanelTitle,
  notificationPanelDescription,
  selectedNotification,
  enterpriseNotificationFormFields,
  enterpriseNotificationFormValues,
  localizeNotificationStatus,
  localizeNotificationLevel,
  operationLogModuleReady,
  canEnterOperationLogWorkspace,
  canViewOperationLogs,
  operationLogLoading,
  operationLogDetailLoading,
  operationLogErrorMessage,
  operationLogDetailErrorMessage,
  operationLogPanelTitle,
  operationLogPanelDescription,
  selectedOperationLog,
  enterpriseOperationLogDetailFields,
  enterpriseOperationLogDetailValues,
  operationLogDetailsText,
  roleModuleReady,
  canEnterRoleWorkspace,
  canViewRoles,
  canCreateRoles,
  canUpdateRoles,
  roleLoading,
  roleDetailLoading,
  roleErrorMessage,
  roleDetailErrorMessage,
  rolePanelMode,
  rolePanelTitle,
  rolePanelDescription,
  selectedRole,
  selectedRoleDetail,
  enterpriseRoleFormFields,
  enterpriseRoleFormValues,
  settingModuleReady,
  canEnterSettingWorkspace,
  canViewSettings,
  canCreateSettings,
  canUpdateSettings,
  settingLoading,
  settingDetailLoading,
  settingErrorMessage,
  settingDetailErrorMessage,
  settingPanelMode,
  settingPanelTitle,
  settingPanelDescription,
  selectedSetting,
  enterpriseSettingFormFields,
  enterpriseSettingFormValues,
  tenantModuleReady,
  authIdentity,
  canEnterTenantWorkspace,
  canViewTenants,
  canCreateTenants,
  canUpdateTenants,
  tenantLoading,
  tenantDetailLoading,
  tenantErrorMessage,
  tenantDetailErrorMessage,
  tenantPanelMode,
  tenantPanelTitle,
  tenantPanelDescription,
  selectedTenant,
  enterpriseTenantFormFields,
  enterpriseTenantFormValues,
  userModuleReady,
  canEnterUserWorkspace,
  canViewUsers,
  canCreateUsers,
  canUpdateUsers,
  canResetUserPasswords,
  userLoading,
  userErrorMessage,
  userPanelMode,
  userPanelTitle,
  userPanelDescription,
  selectedUser,
  enterpriseUserFormFields,
  enterpriseUserFormValues,
  userPasswordInput,
  workflowDetailLoading,
  workflowDetailErrorMessage,
  selectedWorkflowDefinition,
  selectedWorkflowDefinitionId,
  workflowVersionHistoryCards,
  workflowDefinitionDetailCards,
  localizeWorkflowStatus,
  fileModuleReady,
  canViewFiles,
  canUploadFiles,
  canDownloadFiles,
  canDeleteFiles,
  fileLoading,
  fileDetailLoading,
  fileActionLoading,
  fileErrorMessage,
  fileDetailErrorMessage,
  filePanelMode,
  selectedFile,
  pendingUploadFile,
  selectedGeneratorPreviewSchema,
  selectedGeneratorPreviewSchemaName,
  selectedGeneratorPreviewFrontendTarget,
  selectedGeneratorPreviewFile,
  generatorPreviewSqlPreview,
  generatorPreviewSession,
  generatorPreviewDiffSummary,
  customerModuleReady,
  canCreateCustomers,
  canUpdateCustomers,
  canDeleteCustomers,
  customerLoading,
  enterpriseFormMode,
  enterprisePanelTitle,
  enterprisePanelDescription,
  deleteConfirmId,
  selectedCustomer,
  enterpriseFormFields,
  enterpriseFormValues,
  platform,
  localizePlatformStatus,
  envName,
  permissionCodes,
  authLoading,
  loginForm,
  authErrorMessage,
  startDictionaryEdit,
  openDictionaryCreatePanel,
  submitDictionaryForm,
  cancelDictionaryPanel,
  startDepartmentEdit,
  openDepartmentCreatePanel,
  submitDepartmentForm,
  cancelDepartmentPanel,
  startMenuEdit,
  openMenuCreatePanel,
  submitMenuForm,
  cancelMenuPanel,
  markSelectedNotificationAsRead,
  openNotificationCreatePanel,
  submitNotificationForm,
  cancelNotificationPanel,
  startRoleEdit,
  openRoleCreatePanel,
  submitRoleForm,
  cancelRolePanel,
  startSettingEdit,
  openSettingCreatePanel,
  submitSettingForm,
  cancelSettingPanel,
  startTenantEdit,
  toggleSelectedTenantStatus,
  openTenantCreatePanel,
  submitTenantForm,
  cancelTenantPanel,
  startUserEdit,
  startUserPasswordReset,
  openUserCreatePanel,
  submitUserForm,
  cancelUserPanel,
  submitUserPasswordReset,
  handleWorkflowDefinitionSelect,
  setPendingUploadFile,
  submitFileUpload,
  downloadSelectedFile,
  openFileDeletePanel,
  confirmFileDelete,
  cancelFilePanel,
  confirmDelete,
  cancelDelete,
  startEdit,
  requestDelete,
  openCreatePanel,
  handleEnterpriseFormSubmit,
  handleEnterpriseFormCancel,
  submitLogout,
  submitLogin,
}: UseExampleShellBindingsOptions) => {
  const platformStatusLabel = computed(() =>
    localizePlatformStatus(platform.value?.manifest.status),
  )

  const shellWorkspaceSecondaryProps = computed(() => ({
    t,
    locale: locale.value,
    currentWorkspaceKind: read(currentWorkspaceKind),
    isRuntimeShellTab: read(isRuntimeShellTab),
    selectedNavigationItemName: read(selectedNavigationItemName),
    currentNavigationPath: read(currentNavigationPath),
    authStatusLabel: read(authStatusLabel),
    currentModuleCodeLabel: read(currentModuleCodeLabel),
    dictionaryModuleReady: read(dictionaryModuleReady),
    authModuleReady: authModuleReady.value,
    isAuthenticated: read(isAuthenticated),
    canEnterDictionaryWorkspace: read(canEnterDictionaryWorkspace),
    canViewDictionaries: read(canViewDictionaries),
    canCreateDictionaryTypes: read(canCreateDictionaryTypes),
    canUpdateDictionaryTypes: read(canUpdateDictionaryTypes),
    dictionaryLoading: read(dictionaryLoading),
    dictionaryDetailLoading: read(dictionaryDetailLoading),
    dictionaryErrorMessage: read(dictionaryErrorMessage),
    dictionaryDetailErrorMessage: read(dictionaryDetailErrorMessage),
    dictionaryPanelMode: read(dictionaryPanelMode),
    dictionaryPanelTitle: read(dictionaryPanelTitle),
    dictionaryPanelDescription: read(dictionaryPanelDescription),
    selectedDictionaryType: read(selectedDictionaryType),
    selectedDictionaryTypeItems: read(selectedDictionaryTypeItems),
    enterpriseDictionaryFormFields: read(enterpriseDictionaryFormFields),
    enterpriseDictionaryFormValues: read(enterpriseDictionaryFormValues),
    enterpriseFormCopy: read(enterpriseFormCopy),
    localizeDictionaryStatus,
    departmentModuleReady: read(departmentModuleReady),
    canEnterDepartmentWorkspace: read(canEnterDepartmentWorkspace),
    canViewDepartments: read(canViewDepartments),
    canCreateDepartments: read(canCreateDepartments),
    canUpdateDepartments: read(canUpdateDepartments),
    departmentLoading: read(departmentLoading),
    departmentDetailLoading: read(departmentDetailLoading),
    departmentErrorMessage: read(departmentErrorMessage),
    departmentDetailErrorMessage: read(departmentDetailErrorMessage),
    departmentPanelMode: read(departmentPanelMode),
    departmentPanelTitle: read(departmentPanelTitle),
    departmentPanelDescription: read(departmentPanelDescription),
    selectedDepartment: read(selectedDepartment),
    selectedDepartmentDetail: read(selectedDepartmentDetail),
    enterpriseDepartmentFormFields: read(enterpriseDepartmentFormFields),
    enterpriseDepartmentFormValues: read(enterpriseDepartmentFormValues),
    departmentParentLookup: read(departmentParentLookup),
    menuModuleReady: read(menuModuleReady),
    canEnterMenuWorkspace: read(canEnterMenuWorkspace),
    canViewMenus: read(canViewMenus),
    canCreateMenus: read(canCreateMenus),
    canUpdateMenus: read(canUpdateMenus),
    menuLoading: read(menuLoading),
    menuDetailLoading: read(menuDetailLoading),
    menuErrorMessage: read(menuErrorMessage),
    menuDetailErrorMessage: read(menuDetailErrorMessage),
    menuPanelMode: read(menuPanelMode),
    menuPanelTitle: read(menuPanelTitle),
    menuPanelDescription: read(menuPanelDescription),
    selectedMenu: read(selectedMenu),
    selectedMenuDetail: read(selectedMenuDetail),
    enterpriseMenuFormFields: read(enterpriseMenuFormFields),
    enterpriseMenuFormValues: read(enterpriseMenuFormValues),
    menuParentLookup: read(menuParentLookup),
    notificationModuleReady: read(notificationModuleReady),
    canEnterNotificationWorkspace: read(canEnterNotificationWorkspace),
    canViewNotifications: read(canViewNotifications),
    canCreateNotifications: read(canCreateNotifications),
    canUpdateNotifications: read(canUpdateNotifications),
    notificationLoading: read(notificationLoading),
    notificationDetailLoading: read(notificationDetailLoading),
    notificationErrorMessage: read(notificationErrorMessage),
    notificationDetailErrorMessage: read(notificationDetailErrorMessage),
    notificationPanelMode: read(notificationPanelMode),
    notificationPanelTitle: read(notificationPanelTitle),
    notificationPanelDescription: read(notificationPanelDescription),
    selectedNotification: read(selectedNotification),
    enterpriseNotificationFormFields: read(enterpriseNotificationFormFields),
    enterpriseNotificationFormValues: read(enterpriseNotificationFormValues),
    localizeNotificationStatus,
    localizeNotificationLevel,
    operationLogModuleReady: read(operationLogModuleReady),
    canEnterOperationLogWorkspace: read(canEnterOperationLogWorkspace),
    canViewOperationLogs: read(canViewOperationLogs),
    operationLogLoading: read(operationLogLoading),
    operationLogDetailLoading: read(operationLogDetailLoading),
    operationLogErrorMessage: read(operationLogErrorMessage),
    operationLogDetailErrorMessage: read(operationLogDetailErrorMessage),
    operationLogPanelTitle: read(operationLogPanelTitle),
    operationLogPanelDescription: read(operationLogPanelDescription),
    selectedOperationLog: read(selectedOperationLog),
    enterpriseOperationLogDetailFields: read(enterpriseOperationLogDetailFields),
    enterpriseOperationLogDetailValues: read(enterpriseOperationLogDetailValues),
    operationLogDetailsText: read(operationLogDetailsText),
    roleModuleReady: read(roleModuleReady),
    canEnterRoleWorkspace: read(canEnterRoleWorkspace),
    canViewRoles: read(canViewRoles),
    canCreateRoles: read(canCreateRoles),
    canUpdateRoles: read(canUpdateRoles),
    roleLoading: read(roleLoading),
    roleDetailLoading: read(roleDetailLoading),
    roleErrorMessage: read(roleErrorMessage),
    roleDetailErrorMessage: read(roleDetailErrorMessage),
    rolePanelMode: read(rolePanelMode),
    rolePanelTitle: read(rolePanelTitle),
    rolePanelDescription: read(rolePanelDescription),
    selectedRole: read(selectedRole),
    selectedRoleDetail: read(selectedRoleDetail),
    enterpriseRoleFormFields: read(enterpriseRoleFormFields),
    enterpriseRoleFormValues: read(enterpriseRoleFormValues),
    settingModuleReady: read(settingModuleReady),
    canEnterSettingWorkspace: read(canEnterSettingWorkspace),
    canViewSettings: read(canViewSettings),
    canCreateSettings: read(canCreateSettings),
    canUpdateSettings: read(canUpdateSettings),
    settingLoading: read(settingLoading),
    settingDetailLoading: read(settingDetailLoading),
    settingErrorMessage: read(settingErrorMessage),
    settingDetailErrorMessage: read(settingDetailErrorMessage),
    settingPanelMode: read(settingPanelMode),
    settingPanelTitle: read(settingPanelTitle),
    settingPanelDescription: read(settingPanelDescription),
    selectedSetting: read(selectedSetting),
    enterpriseSettingFormFields: read(enterpriseSettingFormFields),
    enterpriseSettingFormValues: read(enterpriseSettingFormValues),
    tenantModuleReady: read(tenantModuleReady),
    tenantIsSuperAdmin: Boolean(authIdentity.value?.user.isSuperAdmin),
    canEnterTenantWorkspace: read(canEnterTenantWorkspace),
    canViewTenants: read(canViewTenants),
    canCreateTenants: read(canCreateTenants),
    canUpdateTenants: read(canUpdateTenants),
    tenantLoading: read(tenantLoading),
    tenantDetailLoading: read(tenantDetailLoading),
    tenantErrorMessage: read(tenantErrorMessage),
    tenantDetailErrorMessage: read(tenantDetailErrorMessage),
    tenantPanelMode: read(tenantPanelMode),
    tenantPanelTitle: read(tenantPanelTitle),
    tenantPanelDescription: read(tenantPanelDescription),
    selectedTenant: read(selectedTenant),
    enterpriseTenantFormFields: read(enterpriseTenantFormFields),
    enterpriseTenantFormValues: read(enterpriseTenantFormValues),
    userModuleReady: read(userModuleReady),
    canEnterUserWorkspace: read(canEnterUserWorkspace),
    canViewUsers: read(canViewUsers),
    canCreateUsers: read(canCreateUsers),
    canUpdateUsers: read(canUpdateUsers),
    canResetUserPasswords: read(canResetUserPasswords),
    userLoading: read(userLoading),
    userErrorMessage: read(userErrorMessage),
    userPanelMode: read(userPanelMode),
    userPanelTitle: read(userPanelTitle),
    userPanelDescription: read(userPanelDescription),
    selectedUser: read(selectedUser),
    enterpriseUserFormFields: read(enterpriseUserFormFields),
    enterpriseUserFormValues: read(enterpriseUserFormValues),
    userPasswordInput: userPasswordInput.value,
    workflowDetailLoading: read(workflowDetailLoading),
    workflowDetailErrorMessage: read(workflowDetailErrorMessage),
    selectedWorkflowDefinition: read(selectedWorkflowDefinition),
    selectedWorkflowDefinitionId: read(selectedWorkflowDefinitionId),
    workflowVersionHistoryCards: read(workflowVersionHistoryCards),
    workflowDefinitionDetailCards: read(workflowDefinitionDetailCards),
    localizeWorkflowStatus,
    fileModuleReady: read(fileModuleReady),
    canViewFiles: read(canViewFiles),
    canUploadFiles: read(canUploadFiles),
    canDownloadFiles: read(canDownloadFiles),
    canDeleteFiles: read(canDeleteFiles),
    fileLoading: read(fileLoading),
    fileDetailLoading: read(fileDetailLoading),
    fileActionLoading: read(fileActionLoading),
    fileErrorMessage: read(fileErrorMessage),
    fileDetailErrorMessage: read(fileDetailErrorMessage),
    filePanelMode: read(filePanelMode),
    selectedFile: read(selectedFile),
    pendingUploadFile: pendingUploadFile.value,
    selectedGeneratorPreviewSchemaName:
      read(selectedGeneratorPreviewSchema)?.name ??
      selectedGeneratorPreviewSchemaName.value,
    selectedGeneratorPreviewFrontendTarget:
      selectedGeneratorPreviewFrontendTarget.value,
    selectedGeneratorPreviewFile: read(selectedGeneratorPreviewFile),
    generatorPreviewSqlPreview: read(generatorPreviewSqlPreview),
    generatorPreviewSession: read(generatorPreviewSession),
    generatorPreviewDiffSummary: read(generatorPreviewDiffSummary),
    generatorPreviewApplyEvidence:
      read(generatorPreviewSession)?.applyEvidence ?? null,
    customerModuleReady: read(customerModuleReady),
    canCreateCustomers: read(canCreateCustomers),
    canUpdateCustomers: read(canUpdateCustomers),
    canDeleteCustomers: read(canDeleteCustomers),
    customerLoading: read(customerLoading),
    enterpriseFormMode: read(enterpriseFormMode),
    enterprisePanelTitle: read(enterprisePanelTitle),
    enterprisePanelDescription: read(enterprisePanelDescription),
    deleteConfirmId: read(deleteConfirmId),
    selectedCustomer: read(selectedCustomer),
    enterpriseFormFields: read(enterpriseFormFields),
    enterpriseFormValues: read(enterpriseFormValues),
    platformDisplayName:
      platform.value?.manifest.displayName ?? t("app.platform.title"),
    platformVersion: platform.value?.manifest.version ?? "-",
    platformStatusLabel: platformStatusLabel.value,
    authDisplayName: authIdentity.value?.user.displayName ?? "",
    authUsername: authIdentity.value?.user.username ?? "",
    authRolesLabel: authIdentity.value?.roles.join(", ") ?? "",
    envName: envName.value,
    permissionCount: permissionCodes.value.length,
    authLoading: authLoading.value,
    loginUsername: loginForm.value.username,
    loginPassword: loginForm.value.password,
    authErrorMessage: authErrorMessage.value,
  }))

  const shellWorkspaceSecondaryListeners = {
    "start-dictionary-edit": startDictionaryEdit,
    "open-dictionary-create": openDictionaryCreatePanel,
    "submit-dictionary-form": submitDictionaryForm,
    "cancel-dictionary-panel": cancelDictionaryPanel,
    "start-department-edit": startDepartmentEdit,
    "open-department-create": openDepartmentCreatePanel,
    "submit-department-form": submitDepartmentForm,
    "cancel-department-panel": cancelDepartmentPanel,
    "start-menu-edit": startMenuEdit,
    "open-menu-create": openMenuCreatePanel,
    "submit-menu-form": submitMenuForm,
    "cancel-menu-panel": cancelMenuPanel,
    "mark-selected-notification-as-read": markSelectedNotificationAsRead,
    "open-notification-create": openNotificationCreatePanel,
    "submit-notification-form": submitNotificationForm,
    "cancel-notification-panel": cancelNotificationPanel,
    "start-role-edit": startRoleEdit,
    "open-role-create": openRoleCreatePanel,
    "submit-role-form": submitRoleForm,
    "cancel-role-panel": cancelRolePanel,
    "start-setting-edit": startSettingEdit,
    "open-setting-create": openSettingCreatePanel,
    "submit-setting-form": submitSettingForm,
    "cancel-setting-panel": cancelSettingPanel,
    "start-tenant-edit": startTenantEdit,
    "toggle-selected-tenant-status": toggleSelectedTenantStatus,
    "open-tenant-create": openTenantCreatePanel,
    "submit-tenant-form": submitTenantForm,
    "cancel-tenant-panel": cancelTenantPanel,
    "start-user-edit": startUserEdit,
    "start-user-password-reset": startUserPasswordReset,
    "open-user-create": openUserCreatePanel,
    "submit-user-form": submitUserForm,
    "cancel-user-panel": cancelUserPanel,
    "update:user-password-input": (value: string) => {
      userPasswordInput.value = value
    },
    "submit-user-password-reset": submitUserPasswordReset,
    "select-workflow-definition": handleWorkflowDefinitionSelect,
    "set-pending-upload-file": setPendingUploadFile,
    "submit-file-upload": submitFileUpload,
    "download-selected-file": downloadSelectedFile,
    "open-file-delete-panel": openFileDeletePanel,
    "confirm-file-delete": confirmFileDelete,
    "cancel-file-panel": cancelFilePanel,
    "confirm-delete": confirmDelete,
    "cancel-delete": cancelDelete,
    "start-customer-edit": startEdit,
    "request-customer-delete": requestDelete,
    "open-customer-create": openCreatePanel,
    "submit-customer-form": handleEnterpriseFormSubmit,
    "cancel-customer-form": handleEnterpriseFormCancel,
    "submit-logout": submitLogout,
    "update:login-username": (value: string) => {
      loginForm.value.username = value
    },
    "update:login-password": (value: string) => {
      loginForm.value.password = value
    },
    "submit-login": submitLogin,
  }

  return {
    shellWorkspaceSecondaryProps,
    shellWorkspaceSecondaryListeners,
  }
}
