import { computed } from "vue"

import {
  type UseExampleShellBindingsOptions,
  read,
} from "./use-example-shell-binding-types"

export const useExampleShellHeaderBindings = ({
  t,
  isRuntimeShellTab,
  isAuthenticated,
  authLoading,
  isRoleWorkspace,
  roleLoading,
  canCreateRoles,
  canViewRoles,
  isCustomerWorkspace,
  customerLoading,
  canCreateCustomers,
  canViewCustomers,
  isDictionaryWorkspace,
  dictionaryLoading,
  canCreateDictionaryTypes,
  canViewDictionaries,
  isDepartmentWorkspace,
  departmentLoading,
  canCreateDepartments,
  canViewDepartments,
  isMenuWorkspace,
  menuLoading,
  canCreateMenus,
  canViewMenus,
  isNotificationWorkspace,
  notificationLoading,
  canCreateNotifications,
  canViewNotifications,
  isOperationLogWorkspace,
  operationLogLoading,
  canViewOperationLogs,
  isUserWorkspace,
  userLoading,
  canCreateUsers,
  canViewUsers,
  isSettingWorkspace,
  settingLoading,
  canCreateSettings,
  canViewSettings,
  isTenantWorkspace,
  tenantLoading,
  canCreateTenants,
  canViewTenants,
  isFileWorkspace,
  fileLoading,
  canViewFiles,
  canUploadFiles,
  isWorkflowDefinitionsWorkspace,
  workflowLoading,
  canViewWorkflowDefinitions,
  openRoleCreatePanel,
  reloadRoles,
  openCreatePanel,
  reloadCustomers,
  openDictionaryCreatePanel,
  reloadDictionaries,
  openDepartmentCreatePanel,
  reloadDepartments,
  openMenuCreatePanel,
  reloadMenus,
  openNotificationCreatePanel,
  reloadNotifications,
  reloadOperationLogs,
  openUserCreatePanel,
  reloadUsers,
  openSettingCreatePanel,
  reloadSettings,
  openTenantCreatePanel,
  reloadTenants,
  reloadFiles,
  reloadWorkflowDefinitions,
  openCurrentWorkspaceTab,
  submitLogout,
}: UseExampleShellBindingsOptions) => {
  const shellHeaderActionProps = computed(() => ({
    t,
    isRuntimeShellTab: read(isRuntimeShellTab),
    isAuthenticated: read(isAuthenticated),
    authLoading: authLoading.value,
    isRoleWorkspace: read(isRoleWorkspace),
    roleLoading: read(roleLoading),
    canCreateRoles: read(canCreateRoles),
    canViewRoles: read(canViewRoles),
    isCustomerWorkspace: read(isCustomerWorkspace),
    customerLoading: read(customerLoading),
    canCreateCustomers: read(canCreateCustomers),
    canViewCustomers: read(canViewCustomers),
    isDictionaryWorkspace: read(isDictionaryWorkspace),
    dictionaryLoading: read(dictionaryLoading),
    canCreateDictionaryTypes: read(canCreateDictionaryTypes),
    canViewDictionaries: read(canViewDictionaries),
    isDepartmentWorkspace: read(isDepartmentWorkspace),
    departmentLoading: read(departmentLoading),
    canCreateDepartments: read(canCreateDepartments),
    canViewDepartments: read(canViewDepartments),
    isMenuWorkspace: read(isMenuWorkspace),
    menuLoading: read(menuLoading),
    canCreateMenus: read(canCreateMenus),
    canViewMenus: read(canViewMenus),
    isNotificationWorkspace: read(isNotificationWorkspace),
    notificationLoading: read(notificationLoading),
    canCreateNotifications: read(canCreateNotifications),
    canViewNotifications: read(canViewNotifications),
    isOperationLogWorkspace: read(isOperationLogWorkspace),
    operationLogLoading: read(operationLogLoading),
    canViewOperationLogs: read(canViewOperationLogs),
    isUserWorkspace: read(isUserWorkspace),
    userLoading: read(userLoading),
    canCreateUsers: read(canCreateUsers),
    canViewUsers: read(canViewUsers),
    isSettingWorkspace: read(isSettingWorkspace),
    settingLoading: read(settingLoading),
    canCreateSettings: read(canCreateSettings),
    canViewSettings: read(canViewSettings),
    isTenantWorkspace: read(isTenantWorkspace),
    tenantLoading: read(tenantLoading),
    canCreateTenants: read(canCreateTenants),
    canViewTenants: read(canViewTenants),
    isFileWorkspace: read(isFileWorkspace),
    fileLoading: read(fileLoading),
    canViewFiles: read(canViewFiles),
    canUploadFiles: read(canUploadFiles),
    isWorkflowDefinitionsWorkspace: read(isWorkflowDefinitionsWorkspace),
    workflowLoading: read(workflowLoading),
    canViewWorkflowDefinitions: read(canViewWorkflowDefinitions),
  }))

  const shellHeaderActionListeners = {
    "open-role-create": openRoleCreatePanel,
    "reload-roles": reloadRoles,
    "open-customer-create": openCreatePanel,
    "reload-customers": reloadCustomers,
    "open-dictionary-create": openDictionaryCreatePanel,
    "reload-dictionaries": reloadDictionaries,
    "open-department-create": openDepartmentCreatePanel,
    "reload-departments": reloadDepartments,
    "open-menu-create": openMenuCreatePanel,
    "reload-menus": reloadMenus,
    "open-notification-create": openNotificationCreatePanel,
    "reload-notifications": reloadNotifications,
    "reload-operation-logs": reloadOperationLogs,
    "open-user-create": openUserCreatePanel,
    "reload-users": reloadUsers,
    "open-setting-create": openSettingCreatePanel,
    "reload-settings": reloadSettings,
    "open-tenant-create": openTenantCreatePanel,
    "reload-tenants": reloadTenants,
    "reload-files": reloadFiles,
    "reload-workflow-definitions": reloadWorkflowDefinitions,
    "open-current-workspace-tab": openCurrentWorkspaceTab,
    "submit-logout": submitLogout,
  }

  return {
    shellHeaderActionProps,
    shellHeaderActionListeners,
  }
}
