import { computed } from "vue"

import {
  type UseExampleShellBindingsOptions,
  read,
} from "./use-example-shell-binding-types"

export const createExampleShellWorkspaceMainBindings = ({
  t,
  enterpriseSelectedTabKey,
  currentWorkspaceKind,
  selectedNavigationItemName,
  currentNavigationPath,
  authStatusLabel,
  currentModuleStatusLabel,
  currentModuleCodeLabel,
  placeholderWorkspaceCopy,
  customerNavigationItem,
  permissionCodes,
  workflowModuleReady,
  authModuleReady,
  isAuthenticated,
  canEnterWorkflowWorkspace,
  canViewWorkflowDefinitions,
  workflowErrorMessage,
  workflowLoading,
  workflowQuery,
  workflowStatusFilter,
  workflowFilterSummary,
  workflowDefinitionCards,
  workflowDefinitions,
  selectedWorkflowDefinitionId,
  fileModuleReady,
  canEnterFileWorkspace,
  canViewFiles,
  canUploadFiles,
  fileErrorMessage,
  fileLoading,
  fileQuery,
  fileFilterSummary,
  fileCountLabel,
  fileTableItems,
  selectedFileId,
  generatorPreviewLoading,
  generatorPreviewApplyLoading,
  generatorPreviewErrorMessage,
  generatorPreviewSchemaOptions,
  selectedGeneratorPreviewSchemaName,
  selectedGeneratorPreviewFrontendTarget,
  generatorPreviewQuery,
  generatorPreviewFilterSummary,
  generatorPreviewFiles,
  selectedGeneratorPreviewFilePath,
  canApplyGeneratorPreview,
  generatorPreviewDiffSummary,
  generatorPreviewSession,
  dictionaryModuleReady,
  canEnterDictionaryWorkspace,
  canViewDictionaries,
  dictionaryLoading,
  dictionaryErrorMessage,
  enterpriseDictionaryQueryFields,
  enterpriseDictionaryTableColumns,
  enterpriseDictionaryTableItems,
  dictionaryCountLabel,
  departmentModuleReady,
  canEnterDepartmentWorkspace,
  canViewDepartments,
  departmentLoading,
  departmentErrorMessage,
  enterpriseDepartmentQueryFields,
  enterpriseDepartmentTableColumns,
  enterpriseDepartmentTableItems,
  departmentCountLabel,
  isSessionWorkspace,
  sessionLoading,
  canEnterSessionWorkspace,
  sessionErrorMessage,
  enterpriseSessionQueryFields,
  enterpriseSessionTableColumns,
  enterpriseSessionTableItems,
  sessionCountLabel,
  postModuleReady,
  canEnterPostWorkspace,
  canViewPosts,
  postLoading,
  postErrorMessage,
  enterprisePostQueryFields,
  enterprisePostTableColumns,
  enterprisePostTableItems,
  postCountLabel,
  menuModuleReady,
  canEnterMenuWorkspace,
  canViewMenus,
  menuLoading,
  menuErrorMessage,
  enterpriseMenuQueryFields,
  enterpriseMenuTableColumns,
  enterpriseMenuTableItems,
  menuCountLabel,
  notificationModuleReady,
  canEnterNotificationWorkspace,
  canViewNotifications,
  notificationLoading,
  notificationErrorMessage,
  enterpriseNotificationQueryFields,
  enterpriseNotificationTableColumns,
  enterpriseNotificationTableItems,
  notificationCountLabel,
  operationLogModuleReady,
  canEnterOperationLogWorkspace,
  canViewOperationLogs,
  operationLogLoading,
  operationLogErrorMessage,
  enterpriseOperationLogQueryFields,
  enterpriseOperationLogTableColumns,
  enterpriseOperationLogTableItems,
  operationLogCountLabel,
  roleModuleReady,
  canEnterRoleWorkspace,
  canViewRoles,
  roleLoading,
  roleErrorMessage,
  enterpriseRoleQueryFields,
  enterpriseRoleTableColumns,
  enterpriseRoleTableItems,
  roleCountLabel,
  settingModuleReady,
  canEnterSettingWorkspace,
  canViewSettings,
  settingLoading,
  settingErrorMessage,
  enterpriseSettingQueryFields,
  enterpriseSettingTableColumns,
  enterpriseSettingTableItems,
  settingCountLabel,
  tenantModuleReady,
  authIdentity,
  canEnterTenantWorkspace,
  canViewTenants,
  tenantLoading,
  tenantErrorMessage,
  enterpriseTenantQueryFields,
  enterpriseTenantTableColumns,
  enterpriseTenantTableItems,
  tenantCountLabel,
  userModuleReady,
  canEnterUserWorkspace,
  canViewUsers,
  userLoading,
  userErrorMessage,
  enterpriseUserQueryFields,
  enterpriseUserTableColumns,
  enterpriseUserTableItems,
  userCountLabel,
  customerModuleReady,
  canEnterCustomerWorkspace,
  canViewCustomers,
  customerLoading,
  customerErrorMessage,
  enterpriseQueryFields,
  enterpriseTableColumns,
  enterpriseTableItems,
  enterpriseTableActions,
  customerCountLabel,
  currentQuerySummary,
  enterpriseCrudCopy,
  localizePlatformStatus,
  customerPaginationSummary,
  customerListPageSize,
  customerListSortValue,
  customerPageInputValue,
  customerPageSizeOptions,
  customerSortOptions,
  canGoToPreviousCustomerPage,
  canGoToNextCustomerPage,
  canJumpToCustomerPage,
  handleWorkflowDefinitionSelect,
  setWorkflowStatusFilter,
  resetWorkflowFilters,
  updateFileQuery,
  resetFileQuery,
  fileItems,
  selectFile,
  openFileUploadPanel,
  resetGeneratorPreviewFilters,
  refreshGeneratorPreview,
  applyGeneratorPreview,
  handleDictionarySearch,
  handleDictionaryReset,
  handleDictionaryRowClick,
  handleDepartmentSearch,
  handleDepartmentReset,
  handleDepartmentRowClick,
  handleSessionSearch,
  handleSessionReset,
  handleSessionRowClick,
  handlePostSearch,
  handlePostReset,
  handlePostRowClick,
  handleMenuSearch,
  handleMenuReset,
  handleMenuRowClick,
  handleNotificationSearch,
  handleNotificationReset,
  handleNotificationRowClick,
  handleOperationLogSearch,
  handleOperationLogReset,
  handleOperationLogRowClick,
  handleRoleSearch,
  handleRoleReset,
  handleRoleRowClick,
  handleSettingSearch,
  handleSettingReset,
  handleSettingRowClick,
  handleTenantSearch,
  handleTenantReset,
  handleTenantRowClick,
  handleUserSearch,
  handleUserReset,
  handleUserRowClick,
  openCustomerWorkspace,
  handleEnterpriseSearch,
  handleEnterpriseReset,
  handleEnterpriseAction,
  handleEnterpriseRowClick,
  handleCustomerPageSizeChange,
  handleCustomerSortChange,
  goToFirstCustomerPage,
  goToPreviousCustomerPage,
  goToNextCustomerPage,
  goToLastCustomerPage,
  updateCustomerPageInput,
  submitCustomerPageJump,
  vueEnterprisePresetStatus,
}: UseExampleShellBindingsOptions) => {
  const shellWorkspaceMainProps = computed(() => ({
    t,
    enterpriseSelectedTabKey: read(enterpriseSelectedTabKey),
    currentWorkspaceKind: read(currentWorkspaceKind),
    selectedNavigationItemName: read(selectedNavigationItemName),
    currentNavigationPath: read(currentNavigationPath),
    authStatusLabel: read(authStatusLabel),
    currentModuleStatusLabel: read(currentModuleStatusLabel),
    permissionCount: permissionCodes.value.length,
    currentModuleCodeLabel: read(currentModuleCodeLabel),
    placeholderWorkspaceCopy: read(placeholderWorkspaceCopy),
    showPlaceholderBackButton: Boolean(read(customerNavigationItem)),
    workflowModuleReady: read(workflowModuleReady),
    authModuleReady: authModuleReady.value,
    isAuthenticated: read(isAuthenticated),
    canEnterWorkflowWorkspace: read(canEnterWorkflowWorkspace),
    canViewWorkflowDefinitions: read(canViewWorkflowDefinitions),
    workflowErrorMessage: read(workflowErrorMessage),
    workflowLoading: read(workflowLoading),
    workflowQuery: workflowQuery.value,
    workflowStatusFilter: read(workflowStatusFilter),
    workflowFilterSummary: read(workflowFilterSummary),
    workflowDefinitionCards: read(workflowDefinitionCards),
    workflowDefinitionCount: read(workflowDefinitions).length,
    selectedWorkflowDefinitionId: read(selectedWorkflowDefinitionId),
    fileModuleReady: read(fileModuleReady),
    canEnterFileWorkspace: read(canEnterFileWorkspace),
    canViewFiles: read(canViewFiles),
    canUploadFiles: read(canUploadFiles),
    fileErrorMessage: read(fileErrorMessage),
    fileLoading: read(fileLoading),
    fileQuery: fileQuery.value,
    fileFilterSummary: read(fileFilterSummary),
    fileCountLabel: read(fileCountLabel),
    fileTableItems: read(fileTableItems),
    selectedFileId: read(selectedFileId),
    generatorPreviewLoading: read(generatorPreviewLoading),
    generatorPreviewApplyLoading: read(generatorPreviewApplyLoading),
    generatorPreviewErrorMessage: read(generatorPreviewErrorMessage),
    generatorPreviewSchemaOptions: read(generatorPreviewSchemaOptions),
    selectedGeneratorPreviewSchemaName:
      selectedGeneratorPreviewSchemaName.value,
    selectedGeneratorPreviewFrontendTarget:
      selectedGeneratorPreviewFrontendTarget.value,
    generatorPreviewQuery: generatorPreviewQuery.value,
    generatorPreviewFilterSummary: read(generatorPreviewFilterSummary),
    generatorPreviewFiles: read(generatorPreviewFiles),
    selectedGeneratorPreviewFilePath: selectedGeneratorPreviewFilePath.value,
    canApplyGeneratorPreview: read(canApplyGeneratorPreview),
    generatorPreviewDiffSummary: read(generatorPreviewDiffSummary),
    generatorPreviewSession: read(generatorPreviewSession),
    dictionaryModuleReady: read(dictionaryModuleReady),
    canEnterDictionaryWorkspace: read(canEnterDictionaryWorkspace),
    canViewDictionaries: read(canViewDictionaries),
    dictionaryLoading: read(dictionaryLoading),
    dictionaryErrorMessage: read(dictionaryErrorMessage),
    enterpriseDictionaryQueryFields: read(enterpriseDictionaryQueryFields),
    enterpriseDictionaryTableColumns: read(enterpriseDictionaryTableColumns),
    enterpriseDictionaryTableItems: read(enterpriseDictionaryTableItems),
    dictionaryCountLabel: read(dictionaryCountLabel),
    departmentModuleReady: read(departmentModuleReady),
    canEnterDepartmentWorkspace: read(canEnterDepartmentWorkspace),
    canViewDepartments: read(canViewDepartments),
    departmentLoading: read(departmentLoading),
    departmentErrorMessage: read(departmentErrorMessage),
    enterpriseDepartmentQueryFields: read(enterpriseDepartmentQueryFields),
    enterpriseDepartmentTableColumns: read(enterpriseDepartmentTableColumns),
    enterpriseDepartmentTableItems: read(enterpriseDepartmentTableItems),
    departmentCountLabel: read(departmentCountLabel),
    isSessionWorkspace: read(isSessionWorkspace),
    sessionModuleReady: authModuleReady.value,
    canEnterSessionWorkspace: read(canEnterSessionWorkspace),
    sessionLoading: read(sessionLoading),
    sessionErrorMessage: read(sessionErrorMessage),
    enterpriseSessionQueryFields: read(enterpriseSessionQueryFields),
    enterpriseSessionTableColumns: read(enterpriseSessionTableColumns),
    enterpriseSessionTableItems: read(enterpriseSessionTableItems),
    sessionCountLabel: read(sessionCountLabel),
    postModuleReady: read(postModuleReady),
    canEnterPostWorkspace: read(canEnterPostWorkspace),
    canViewPosts: read(canViewPosts),
    postLoading: read(postLoading),
    postErrorMessage: read(postErrorMessage),
    enterprisePostQueryFields: read(enterprisePostQueryFields),
    enterprisePostTableColumns: read(enterprisePostTableColumns),
    enterprisePostTableItems: read(enterprisePostTableItems),
    postCountLabel: read(postCountLabel),
    menuModuleReady: read(menuModuleReady),
    canEnterMenuWorkspace: read(canEnterMenuWorkspace),
    canViewMenus: read(canViewMenus),
    menuLoading: read(menuLoading),
    menuErrorMessage: read(menuErrorMessage),
    enterpriseMenuQueryFields: read(enterpriseMenuQueryFields),
    enterpriseMenuTableColumns: read(enterpriseMenuTableColumns),
    enterpriseMenuTableItems: read(enterpriseMenuTableItems),
    menuCountLabel: read(menuCountLabel),
    notificationModuleReady: read(notificationModuleReady),
    canEnterNotificationWorkspace: read(canEnterNotificationWorkspace),
    canViewNotifications: read(canViewNotifications),
    notificationLoading: read(notificationLoading),
    notificationErrorMessage: read(notificationErrorMessage),
    enterpriseNotificationQueryFields: read(enterpriseNotificationQueryFields),
    enterpriseNotificationTableColumns: read(
      enterpriseNotificationTableColumns,
    ),
    enterpriseNotificationTableItems: read(enterpriseNotificationTableItems),
    notificationCountLabel: read(notificationCountLabel),
    operationLogModuleReady: read(operationLogModuleReady),
    canEnterOperationLogWorkspace: read(canEnterOperationLogWorkspace),
    canViewOperationLogs: read(canViewOperationLogs),
    operationLogLoading: read(operationLogLoading),
    operationLogErrorMessage: read(operationLogErrorMessage),
    enterpriseOperationLogQueryFields: read(enterpriseOperationLogQueryFields),
    enterpriseOperationLogTableColumns: read(
      enterpriseOperationLogTableColumns,
    ),
    enterpriseOperationLogTableItems: read(enterpriseOperationLogTableItems),
    operationLogCountLabel: read(operationLogCountLabel),
    roleModuleReady: read(roleModuleReady),
    canEnterRoleWorkspace: read(canEnterRoleWorkspace),
    canViewRoles: read(canViewRoles),
    roleLoading: read(roleLoading),
    roleErrorMessage: read(roleErrorMessage),
    enterpriseRoleQueryFields: read(enterpriseRoleQueryFields),
    enterpriseRoleTableColumns: read(enterpriseRoleTableColumns),
    enterpriseRoleTableItems: read(enterpriseRoleTableItems),
    roleCountLabel: read(roleCountLabel),
    settingModuleReady: read(settingModuleReady),
    canEnterSettingWorkspace: read(canEnterSettingWorkspace),
    canViewSettings: read(canViewSettings),
    settingLoading: read(settingLoading),
    settingErrorMessage: read(settingErrorMessage),
    enterpriseSettingQueryFields: read(enterpriseSettingQueryFields),
    enterpriseSettingTableColumns: read(enterpriseSettingTableColumns),
    enterpriseSettingTableItems: read(enterpriseSettingTableItems),
    settingCountLabel: read(settingCountLabel),
    tenantModuleReady: read(tenantModuleReady),
    tenantIsSuperAdmin: Boolean(authIdentity.value?.user.isSuperAdmin),
    canEnterTenantWorkspace: read(canEnterTenantWorkspace),
    canViewTenants: read(canViewTenants),
    tenantLoading: read(tenantLoading),
    tenantErrorMessage: read(tenantErrorMessage),
    enterpriseTenantQueryFields: read(enterpriseTenantQueryFields),
    enterpriseTenantTableColumns: read(enterpriseTenantTableColumns),
    enterpriseTenantTableItems: read(enterpriseTenantTableItems),
    tenantCountLabel: read(tenantCountLabel),
    userModuleReady: read(userModuleReady),
    canEnterUserWorkspace: read(canEnterUserWorkspace),
    canViewUsers: read(canViewUsers),
    userLoading: read(userLoading),
    userErrorMessage: read(userErrorMessage),
    enterpriseUserQueryFields: read(enterpriseUserQueryFields),
    enterpriseUserTableColumns: read(enterpriseUserTableColumns),
    enterpriseUserTableItems: read(enterpriseUserTableItems),
    userCountLabel: read(userCountLabel),
    customerModuleReady: read(customerModuleReady),
    canEnterCustomerWorkspace: read(canEnterCustomerWorkspace),
    canViewCustomers: read(canViewCustomers),
    customerLoading: read(customerLoading),
    customerErrorMessage: read(customerErrorMessage),
    enterpriseQueryFields: read(enterpriseQueryFields),
    enterpriseTableColumns: read(enterpriseTableColumns),
    enterpriseTableItems: read(enterpriseTableItems),
    enterpriseTableActions: read(enterpriseTableActions),
    customerCountLabel: read(customerCountLabel),
    currentQuerySummary: read(currentQuerySummary),
    enterpriseCrudCopy: read(enterpriseCrudCopy),
    customerFooterStatusLabel: localizePlatformStatus(
      vueEnterprisePresetStatus,
    ),
    customerPaginationSummary: read(customerPaginationSummary),
    customerListPageSize: read(customerListPageSize),
    customerListSortValue: read(customerListSortValue),
    customerPageInputValue: read(customerPageInputValue),
    customerPageSizeOptions: read(customerPageSizeOptions),
    customerSortOptions: read(customerSortOptions),
    canGoToPreviousCustomerPage: read(canGoToPreviousCustomerPage),
    canGoToNextCustomerPage: read(canGoToNextCustomerPage),
    canJumpToCustomerPage: read(canJumpToCustomerPage),
  }))

  const shellWorkspaceMainListeners = {
    "workflow-update-query": (value: string) => {
      workflowQuery.value = value
    },
    "select-workflow-definition": handleWorkflowDefinitionSelect,
    "select-workflow-status-filter": setWorkflowStatusFilter,
    "reset-workflow-filters": resetWorkflowFilters,
    "update-file-query": updateFileQuery,
    "reset-file-filters": resetFileQuery,
    "select-file": (fileId: string) => {
      const nextFile = fileItems.value.find((item) => item.id === fileId)

      if (nextFile) {
        void selectFile(nextFile)
      }
    },
    "open-file-upload": openFileUploadPanel,
    "update-generator-schema-name": (value: string) => {
      selectedGeneratorPreviewSchemaName.value = value
    },
    "update-generator-frontend-target": (value: string) => {
      selectedGeneratorPreviewFrontendTarget.value = value
    },
    "update-generator-query": (value: string) => {
      generatorPreviewQuery.value = value
    },
    "select-generator-file": (value: string) => {
      selectedGeneratorPreviewFilePath.value = value
    },
    "reset-generator-filters": resetGeneratorPreviewFilters,
    "refresh-generator-preview": refreshGeneratorPreview,
    "apply-generator-preview": applyGeneratorPreview,
    "dictionary-search": handleDictionarySearch,
    "dictionary-reset": handleDictionaryReset,
    "dictionary-row-click": handleDictionaryRowClick,
    "department-search": handleDepartmentSearch,
    "department-reset": handleDepartmentReset,
    "department-row-click": handleDepartmentRowClick,
    "session-search": handleSessionSearch,
    "session-reset": handleSessionReset,
    "session-row-click": handleSessionRowClick,
    "post-search": handlePostSearch,
    "post-reset": handlePostReset,
    "post-row-click": handlePostRowClick,
    "menu-search": handleMenuSearch,
    "menu-reset": handleMenuReset,
    "menu-row-click": handleMenuRowClick,
    "notification-search": handleNotificationSearch,
    "notification-reset": handleNotificationReset,
    "notification-row-click": handleNotificationRowClick,
    "operation-log-search": handleOperationLogSearch,
    "operation-log-reset": handleOperationLogReset,
    "operation-log-row-click": handleOperationLogRowClick,
    "role-search": handleRoleSearch,
    "role-reset": handleRoleReset,
    "role-row-click": handleRoleRowClick,
    "setting-search": handleSettingSearch,
    "setting-reset": handleSettingReset,
    "setting-row-click": handleSettingRowClick,
    "tenant-search": handleTenantSearch,
    "tenant-reset": handleTenantReset,
    "tenant-row-click": handleTenantRowClick,
    "user-search": handleUserSearch,
    "user-reset": handleUserReset,
    "user-row-click": handleUserRowClick,
    "back-to-customer": openCustomerWorkspace,
    "customer-search": handleEnterpriseSearch,
    "customer-reset": handleEnterpriseReset,
    "customer-action": handleEnterpriseAction,
    "customer-row-click": handleEnterpriseRowClick,
    "change-customer-page-size": handleCustomerPageSizeChange,
    "change-customer-sort": handleCustomerSortChange,
    "go-first-customer-page": goToFirstCustomerPage,
    "go-previous-customer-page": goToPreviousCustomerPage,
    "go-next-customer-page": goToNextCustomerPage,
    "go-last-customer-page": goToLastCustomerPage,
    "update-customer-page-input": updateCustomerPageInput,
    "submit-customer-page-jump": submitCustomerPageJump,
  }

  return {
    shellWorkspaceMainProps,
    shellWorkspaceMainListeners,
  }
}
