import type { useCustomerWorkspace } from "../workspaces/use-customer-workspace"

export type ExampleCustomerWorkspace = ReturnType<typeof useCustomerWorkspace>

export const useExampleCustomerWorkspaceBindings = (
  customerWorkspace: ExampleCustomerWorkspace,
) => {
  const {
    canGoToNextCustomerPage,
    canGoToPreviousCustomerPage,
    canJumpToCustomerPage,
    cancelDelete,
    clearWorkspace: clearCustomerWorkspace,
    confirmDelete,
    customerCountLabel,
    customerErrorMessage,
    customerFormMode: enterpriseFormMode,
    customerItems,
    customerListPage,
    customerListPageSize,
    customerListSortValue,
    customerListTotal,
    customerListTotalPages,
    customerLoading,
    customerPageInputValue,
    customerPageSizeOptions,
    customerPaginationSummary,
    customerQuerySummary,
    customerQueryValues: enterpriseQueryValues,
    customerSortOptions,
    deleteConfirmId,
    formFields: enterpriseFormFields,
    formValues: enterpriseFormValues,
    goToFirstCustomerPage,
    goToLastCustomerPage,
    goToNextCustomerPage,
    goToPreviousCustomerPage,
    handleAction: handleEnterpriseAction,
    handleFormCancel: handleEnterpriseFormCancel,
    handleFormSubmit: handleEnterpriseFormSubmit,
    handlePageSizeChange: handleCustomerPageSizeChange,
    handleReset: handleEnterpriseReset,
    handleRowClick: handleEnterpriseRowClick,
    handleSearch: handleEnterpriseSearch,
    handleSortChange: handleCustomerSortChange,
    openCreatePanel,
    panelDescription: enterprisePanelDescription,
    panelTitle: enterprisePanelTitle,
    queryFields: enterpriseQueryFields,
    reloadCustomers,
    requestDelete,
    selectedCustomer,
    selectedCustomerId,
    startEdit,
    submitCustomerPageJump,
    tableActions: enterpriseTableActions,
    tableColumns: enterpriseTableColumns,
    tableItems: enterpriseTableItems,
    updateCustomerPageInput,
  } = customerWorkspace

  return {
    canGoToNextCustomerPage,
    canGoToPreviousCustomerPage,
    canJumpToCustomerPage,
    cancelDelete,
    clearCustomerWorkspace,
    confirmDelete,
    customerCountLabel,
    customerErrorMessage,
    enterpriseFormMode,
    customerItems,
    customerListPage,
    customerListPageSize,
    customerListSortValue,
    customerListTotal,
    customerListTotalPages,
    customerLoading,
    customerPageInputValue,
    customerPageSizeOptions,
    customerPaginationSummary,
    customerQuerySummary,
    enterpriseQueryValues,
    customerSortOptions,
    deleteConfirmId,
    enterpriseFormFields,
    enterpriseFormValues,
    goToFirstCustomerPage,
    goToLastCustomerPage,
    goToNextCustomerPage,
    goToPreviousCustomerPage,
    handleEnterpriseAction,
    handleEnterpriseFormCancel,
    handleEnterpriseFormSubmit,
    handleCustomerPageSizeChange,
    handleEnterpriseReset,
    handleEnterpriseRowClick,
    handleEnterpriseSearch,
    handleCustomerSortChange,
    openCreatePanel,
    enterprisePanelDescription,
    enterprisePanelTitle,
    enterpriseQueryFields,
    reloadCustomers,
    requestDelete,
    selectedCustomer,
    selectedCustomerId,
    startEdit,
    submitCustomerPageJump,
    enterpriseTableActions,
    enterpriseTableColumns,
    enterpriseTableItems,
    updateCustomerPageInput,
  }
}
