import { computed } from "vue"

import {
  type UseExampleShellBindingsOptions,
  read,
} from "./use-example-shell-binding-types"

export const createExampleShellWorkspaceMainBindings = ({
  t,
  enterpriseSelectedTabKey,
  currentWorkspaceKind,
  selectedNavigationItemName,
  currentNavigationPath,
  authStatusLabel,
  currentModuleStatusLabel,
  currentModuleCodeLabel,
  placeholderWorkspaceCopy,
  customerNavigationItem,
  permissionCodes,
  workflowModuleReady,
  authModuleReady,
  isAuthenticated,
  canEnterWorkflowWorkspace,
  canViewWorkflowDefinitions,
  workflowErrorMessage,
  workflowLoading,
  workflowQuery,
  workflowDefinitionCards,
  workflowDefinitions,
  workflowPaginationSummary,
  workflowCanGoToPreviousPage,
  workflowCanGoToNextPage,
  workflowDetailDialogOpen,
  selectedWorkflowDefinitionId,
  workflowDetailLoading,
  workflowDetailErrorMessage,
  selectedWorkflowDefinition,
  localizeWorkflowStatus,
  fileModuleReady,
  canEnterFileWorkspace,
  canViewFiles,
  canUploadFiles,
  fileErrorMessage,
  fileLoading,
  fileQuery,
  fileFilterSummary,
  fileCountLabel,
  fileTableItems,
  selectedFileId,
  generatorPreviewLoading,
  generatorPreviewReviewLoading,
  generatorPreviewApplyLoading,
  generatorPreviewErrorMessage,
  generatorPreviewInputModeOptions,
  generatorPreviewSchemaOptions,
  generatorPreviewConflictStrategyOptions,
  generatorPreviewRecentSessionOptions,
  loadSelectedSchemaDraft,
  selectedGeneratorPreviewInputMode,
  selectedGeneratorPreviewConflictStrategy,
  selectedGeneratorPreviewRecentSessionId,
  selectedGeneratorPreviewSchemaName,
  selectedGeneratorPreviewFrontendTarget,
  generatorPreviewCurrentStep,
  generatorPreviewManualSchemaDraft,
  generatorPreviewManualSchemaDraftError,
  generatorPreviewManualSchemaDraftErrorDetails,
  loadGeneratorSchemaTemplate,
  generatorPreviewQuery,
  generatorPreviewFiles,
  selectedGeneratorPreviewFilePath,
  canApproveGeneratorPreview,
  canRejectGeneratorPreview,
  canApplyGeneratorPreview,
  canConfirmGeneratorPreview,
  generatorPreviewDiffSummary,
  generatorPreviewSession,
  dictionaryModuleReady,
  canEnterDictionaryWorkspace,
  canViewDictionaries,
  canCreateDictionaryTypes,
  canUpdateDictionaryTypes,
  dictionaryLoading,
  dictionaryErrorMessage,
  dictionaryWorkspaceState,
  enterpriseDictionaryQueryFields,
  enterpriseDictionaryTableColumns,
  dictionaryCountLabel,
  handleDictionaryAction,
  departmentModuleReady,
  canEnterDepartmentWorkspace,
  canViewDepartments,
  canCreateDepartments,
  canUpdateDepartments,
  departmentWorkspaceState,
  departmentLoading,
  departmentErrorMessage,
  enterpriseDepartmentQueryFields,
  enterpriseDepartmentTableActions,
  enterpriseDepartmentTableColumns,
  enterpriseDepartmentTableItems,
  departmentCountLabel,
  handleDepartmentAction,
  isSessionWorkspace,
  sessionLoading,
  canEnterSessionWorkspace,
  sessionErrorMessage,
  enterpriseSessionQueryFields,
  enterpriseSessionTableColumns,
  enterpriseSessionTableItems,
  sessionCountLabel,
  postModuleReady,
  canEnterPostWorkspace,
  canViewPosts,
  canCreatePosts,
  canUpdatePosts,
  postWorkspaceState,
  postLoading,
  postErrorMessage,
  enterprisePostQueryFields,
  enterprisePostTableColumns,
  postCountLabel,
  handlePostAction,
  menuModuleReady,
  canEnterMenuWorkspace,
  canViewMenus,
  canCreateMenus,
  canUpdateMenus,
  menuWorkspaceState,
  menuLoading,
  menuErrorMessage,
  enterpriseMenuQueryFields,
  enterpriseMenuTableColumns,
  menuCountLabel,
  handleMenuAction,
  notificationModuleReady,
  canEnterNotificationWorkspace,
  canViewNotifications,
  canCreateNotifications,
  canUpdateNotifications,
  notificationWorkspaceState,
  enterpriseNotificationQueryFields,
  enterpriseNotificationTableColumns,
  notificationCountLabel,
  handleNotificationAction,
  operationLogModuleReady,
  canEnterOperationLogWorkspace,
  canViewOperationLogs,
  operationLogLoading,
  operationLogErrorMessage,
  enterpriseOperationLogQueryFields,
  enterpriseOperationLogTableColumns,
  enterpriseOperationLogTableItems,
  operationLogCountLabel,
  roleModuleReady,
  canEnterRoleWorkspace,
  canViewRoles,
  canCreateRoles,
  canUpdateRoles,
  roleLoading,
  roleErrorMessage,
  roleWorkspaceState,
  enterpriseRoleQueryFields,
  enterpriseRoleTableColumns,
  roleCountLabel,
  handleRoleAction,
  settingModuleReady,
  canEnterSettingWorkspace,
  canViewSettings,
  canCreateSettings,
  canUpdateSettings,
  settingWorkspaceState,
  enterpriseSettingQueryFields,
  enterpriseSettingTableColumns,
  settingCountLabel,
  handleSettingAction,
  tenantModuleReady,
  authIdentity,
  canEnterTenantWorkspace,
  canViewTenants,
  canCreateTenants,
  canUpdateTenants,
  tenantWorkspaceState,
  enterpriseTenantQueryFields,
  enterpriseTenantTableColumns,
  tenantCountLabel,
  handleTenantAction,
  userModuleReady,
  canEnterUserWorkspace,
  canViewUsers,
  canCreateUsers,
  canUpdateUsers,
  userWorkspaceState,
  enterpriseUserQueryFields,
  enterpriseUserTableColumns,
  userCountLabel,
  handleUserAction,
  customerModuleReady,
  canEnterCustomerWorkspace,
  canViewCustomers,
  customerLoading,
  customerErrorMessage,
  customerWorkspaceState,
  enterpriseQueryFields,
  enterpriseTableColumns,
  enterpriseTableActions,
  customerCountLabel,
  currentQuerySummary,
  enterpriseCrudCopy,
  localizePlatformStatus,
  customerPaginationSummary,
  customerListPageSize,
  customerListSortValue,
  customerPageInputValue,
  customerPageSizeOptions,
  customerSortOptions,
  canGoToPreviousCustomerPage,
  canGoToNextCustomerPage,
  canJumpToCustomerPage,
  handleWorkflowDefinitionSelect,
  closeWorkflowDefinitionDetail,
  setWorkflowQuery,
  resetWorkflowFilters,
  goToPreviousWorkflowPage,
  goToNextWorkflowPage,
  updateFileQuery,
  resetFileQuery,
  fileItems,
  selectFile,
  openFileUploadPanel,
  resetGeneratorPreviewFilters,
  refreshGeneratorPreview,
  resetGeneratorPreviewState,
  restoreGeneratorPreviewSession,
  reviewGeneratorPreview,
  confirmGeneratorPreview,
  applyGeneratorPreview,
  handleDictionarySearch,
  handleDictionaryReset,
  handleDictionaryRowClick,
  handleDepartmentSearch,
  handleDepartmentReset,
  handleDepartmentRowClick,
  handleSessionSearch,
  handleSessionReset,
  handleSessionRowClick,
  handlePostSearch,
  handlePostReset,
  handlePostRowClick,
  handleMenuSearch,
  handleMenuReset,
  handleMenuRowClick,
  handleNotificationSearch,
  handleNotificationReset,
  handleNotificationRowClick,
  handleOperationLogSearch,
  handleOperationLogReset,
  handleOperationLogRowClick,
  handleRoleSearch,
  handleRoleReset,
  handleRoleRowClick,
  handleSettingSearch,
  handleSettingReset,
  handleSettingRowClick,
  handleTenantSearch,
  handleTenantReset,
  handleTenantRowClick,
  handleUserSearch,
  handleUserReset,
  handleUserRowClick,
  openCustomerWorkspace,
  handleEnterpriseSearch,
  handleEnterpriseReset,
  handleEnterpriseAction,
  handleEnterpriseRowClick,
  handleCustomerPageSizeChange,
  handleCustomerSortChange,
  goToFirstCustomerPage,
  goToPreviousCustomerPage,
  goToNextCustomerPage,
  goToLastCustomerPage,
  updateCustomerPageInput,
  submitCustomerPageJump,
  vueEnterprisePresetStatus,
}: UseExampleShellBindingsOptions) => {
  const forwardCrudAction =
    (handler: (key: string, row: Record<string, unknown>) => void) =>
    (payload: unknown) => {
      const actionPayload = payload as {
        key?: string
        row?: Record<string, unknown>
      }

      handler(
        String(actionPayload.key ?? ""),
        actionPayload.row ?? ({} as Record<string, unknown>),
      )
    }

  const shellWorkspaceMainProps = computed(() => ({
    t,
    enterpriseSelectedTabKey: read(enterpriseSelectedTabKey),
    currentWorkspaceKind: read(currentWorkspaceKind),
    selectedNavigationItemName: read(selectedNavigationItemName),
    currentNavigationPath: read(currentNavigationPath),
    authStatusLabel: read(authStatusLabel),
    currentModuleStatusLabel: read(currentModuleStatusLabel),
    permissionCount: permissionCodes.value.length,
    currentModuleCodeLabel: read(currentModuleCodeLabel),
    placeholderWorkspaceCopy: read(placeholderWorkspaceCopy),
    showPlaceholderBackButton: Boolean(read(customerNavigationItem)),
    workflowModuleReady: read(workflowModuleReady),
    authModuleReady: authModuleReady.value,
    isAuthenticated: read(isAuthenticated),
    canEnterWorkflowWorkspace: read(canEnterWorkflowWorkspace),
    canViewWorkflowDefinitions: read(canViewWorkflowDefinitions),
    workflowErrorMessage: read(workflowErrorMessage),
    workflowLoading: read(workflowLoading),
    workflowQuery: workflowQuery.value,
    workflowDefinitionCards: read(workflowDefinitionCards),
    workflowDefinitionCount: read(workflowDefinitions).length,
    workflowPaginationSummary: read(workflowPaginationSummary),
    workflowCanGoToPreviousPage: read(workflowCanGoToPreviousPage),
    workflowCanGoToNextPage: read(workflowCanGoToNextPage),
    workflowDetailDialogOpen: read(workflowDetailDialogOpen),
    selectedWorkflowDefinitionId: read(selectedWorkflowDefinitionId),
    workflowDetailLoading: read(workflowDetailLoading),
    workflowDetailErrorMessage: read(workflowDetailErrorMessage),
    selectedWorkflowDefinition: read(selectedWorkflowDefinition),
    localizeWorkflowStatus,
    fileModuleReady: read(fileModuleReady),
    canEnterFileWorkspace: read(canEnterFileWorkspace),
    canViewFiles: read(canViewFiles),
    canUploadFiles: read(canUploadFiles),
    fileErrorMessage: read(fileErrorMessage),
    fileLoading: read(fileLoading),
    fileQuery: fileQuery.value,
    fileFilterSummary: read(fileFilterSummary),
    fileCountLabel: read(fileCountLabel),
    fileTableItems: read(fileTableItems),
    selectedFileId: read(selectedFileId),
    generatorPreviewLoading: read(generatorPreviewLoading),
    generatorPreviewReviewLoading: read(generatorPreviewReviewLoading),
    generatorPreviewApplyLoading: read(generatorPreviewApplyLoading),
    generatorPreviewErrorMessage: read(generatorPreviewErrorMessage),
    generatorPreviewInputModeOptions: read(generatorPreviewInputModeOptions),
    generatorPreviewSchemaOptions: read(generatorPreviewSchemaOptions),
    generatorPreviewConflictStrategyOptions: read(
      generatorPreviewConflictStrategyOptions,
    ),
    generatorPreviewRecentSessionOptions: read(
      generatorPreviewRecentSessionOptions,
    ),
    selectedGeneratorPreviewInputMode: selectedGeneratorPreviewInputMode.value,
    selectedGeneratorPreviewConflictStrategy:
      selectedGeneratorPreviewConflictStrategy.value,
    selectedGeneratorPreviewRecentSessionId:
      selectedGeneratorPreviewRecentSessionId.value,
    selectedGeneratorPreviewSchemaName:
      selectedGeneratorPreviewSchemaName.value,
    selectedGeneratorPreviewFrontendTarget:
      selectedGeneratorPreviewFrontendTarget.value,
    generatorPreviewCurrentStep: read(generatorPreviewCurrentStep),
    generatorPreviewManualSchemaDraft: generatorPreviewManualSchemaDraft.value,
    generatorPreviewManualSchemaDraftError: read(
      generatorPreviewManualSchemaDraftError,
    ),
    generatorPreviewManualSchemaDraftErrorDetails: read(
      generatorPreviewManualSchemaDraftErrorDetails,
    ),
    loadSelectedSchemaDraft,
    loadGeneratorSchemaTemplate,
    generatorPreviewQuery: generatorPreviewQuery.value,
    generatorPreviewFiles: read(generatorPreviewFiles),
    selectedGeneratorPreviewFilePath: selectedGeneratorPreviewFilePath.value,
    canApproveGeneratorPreview: read(canApproveGeneratorPreview),
    canRejectGeneratorPreview: read(canRejectGeneratorPreview),
    canApplyGeneratorPreview: read(canApplyGeneratorPreview),
    canConfirmGeneratorPreview: read(canConfirmGeneratorPreview),
    generatorPreviewDiffSummary: read(generatorPreviewDiffSummary),
    generatorPreviewSession: read(generatorPreviewSession),
    dictionaryModuleReady: read(dictionaryModuleReady),
    canEnterDictionaryWorkspace: read(canEnterDictionaryWorkspace),
    canViewDictionaries: read(canViewDictionaries),
    canCreateDictionaryTypes: read(canCreateDictionaryTypes),
    canUpdateDictionaryTypes: read(canUpdateDictionaryTypes),
    dictionaryLoading: read(dictionaryLoading),
    dictionaryErrorMessage: read(dictionaryErrorMessage),
    dictionaryWorkspaceState,
    enterpriseDictionaryQueryFields: read(enterpriseDictionaryQueryFields),
    enterpriseDictionaryTableColumns: read(enterpriseDictionaryTableColumns),
    dictionaryCountLabel: read(dictionaryCountLabel),
    departmentModuleReady: read(departmentModuleReady),
    canEnterDepartmentWorkspace: read(canEnterDepartmentWorkspace),
    canViewDepartments: read(canViewDepartments),
    canCreateDepartments: read(canCreateDepartments),
    canUpdateDepartments: read(canUpdateDepartments),
    departmentWorkspaceState,
    departmentLoading: read(departmentLoading),
    departmentErrorMessage: read(departmentErrorMessage),
    enterpriseDepartmentQueryFields: read(enterpriseDepartmentQueryFields),
    enterpriseDepartmentTableColumns: read(enterpriseDepartmentTableColumns),
    enterpriseDepartmentTableActions: read(enterpriseDepartmentTableActions),
    enterpriseDepartmentTableItems: read(enterpriseDepartmentTableItems),
    departmentCountLabel: read(departmentCountLabel),
    isSessionWorkspace: read(isSessionWorkspace),
    sessionModuleReady: authModuleReady.value,
    canEnterSessionWorkspace: read(canEnterSessionWorkspace),
    sessionLoading: read(sessionLoading),
    sessionErrorMessage: read(sessionErrorMessage),
    enterpriseSessionQueryFields: read(enterpriseSessionQueryFields),
    enterpriseSessionTableColumns: read(enterpriseSessionTableColumns),
    enterpriseSessionTableItems: read(enterpriseSessionTableItems),
    sessionCountLabel: read(sessionCountLabel),
    postModuleReady: read(postModuleReady),
    canEnterPostWorkspace: read(canEnterPostWorkspace),
    canViewPosts: read(canViewPosts),
    canCreatePosts: read(canCreatePosts),
    canUpdatePosts: read(canUpdatePosts),
    postWorkspaceState,
    postLoading: read(postLoading),
    postErrorMessage: read(postErrorMessage),
    enterprisePostQueryFields: read(enterprisePostQueryFields),
    enterprisePostTableColumns: read(enterprisePostTableColumns),
    postCountLabel: read(postCountLabel),
    menuModuleReady: read(menuModuleReady),
    canEnterMenuWorkspace: read(canEnterMenuWorkspace),
    canViewMenus: read(canViewMenus),
    canCreateMenus: read(canCreateMenus),
    canUpdateMenus: read(canUpdateMenus),
    menuWorkspaceState,
    menuLoading: read(menuLoading),
    menuErrorMessage: read(menuErrorMessage),
    enterpriseMenuQueryFields: read(enterpriseMenuQueryFields),
    enterpriseMenuTableColumns: read(enterpriseMenuTableColumns),
    menuCountLabel: read(menuCountLabel),
    notificationModuleReady: read(notificationModuleReady),
    canEnterNotificationWorkspace: read(canEnterNotificationWorkspace),
    canViewNotifications: read(canViewNotifications),
    canCreateNotifications: read(canCreateNotifications),
    canUpdateNotifications: read(canUpdateNotifications),
    notificationWorkspaceState,
    enterpriseNotificationQueryFields: read(enterpriseNotificationQueryFields),
    enterpriseNotificationTableColumns: read(
      enterpriseNotificationTableColumns,
    ),
    notificationCountLabel: read(notificationCountLabel),
    operationLogModuleReady: read(operationLogModuleReady),
    canEnterOperationLogWorkspace: read(canEnterOperationLogWorkspace),
    canViewOperationLogs: read(canViewOperationLogs),
    operationLogLoading: read(operationLogLoading),
    operationLogErrorMessage: read(operationLogErrorMessage),
    enterpriseOperationLogQueryFields: read(enterpriseOperationLogQueryFields),
    enterpriseOperationLogTableColumns: read(
      enterpriseOperationLogTableColumns,
    ),
    enterpriseOperationLogTableItems: read(enterpriseOperationLogTableItems),
    operationLogCountLabel: read(operationLogCountLabel),
    roleModuleReady: read(roleModuleReady),
    canEnterRoleWorkspace: read(canEnterRoleWorkspace),
    canViewRoles: read(canViewRoles),
    canCreateRoles: read(canCreateRoles),
    canUpdateRoles: read(canUpdateRoles),
    roleLoading: read(roleLoading),
    roleErrorMessage: read(roleErrorMessage),
    roleWorkspaceState,
    enterpriseRoleQueryFields: read(enterpriseRoleQueryFields),
    enterpriseRoleTableColumns: read(enterpriseRoleTableColumns),
    roleCountLabel: read(roleCountLabel),
    settingModuleReady: read(settingModuleReady),
    canEnterSettingWorkspace: read(canEnterSettingWorkspace),
    canViewSettings: read(canViewSettings),
    canCreateSettings: read(canCreateSettings),
    canUpdateSettings: read(canUpdateSettings),
    settingWorkspaceState,
    enterpriseSettingQueryFields: read(enterpriseSettingQueryFields),
    enterpriseSettingTableColumns: read(enterpriseSettingTableColumns),
    settingCountLabel: read(settingCountLabel),
    tenantModuleReady: read(tenantModuleReady),
    tenantIsSuperAdmin: Boolean(authIdentity.value?.user.isSuperAdmin),
    canEnterTenantWorkspace: read(canEnterTenantWorkspace),
    canViewTenants: read(canViewTenants),
    canCreateTenants: read(canCreateTenants),
    canUpdateTenants: read(canUpdateTenants),
    tenantWorkspaceState,
    enterpriseTenantQueryFields: read(enterpriseTenantQueryFields),
    enterpriseTenantTableColumns: read(enterpriseTenantTableColumns),
    tenantCountLabel: read(tenantCountLabel),
    userModuleReady: read(userModuleReady),
    canEnterUserWorkspace: read(canEnterUserWorkspace),
    canViewUsers: read(canViewUsers),
    canCreateUsers: read(canCreateUsers),
    canUpdateUsers: read(canUpdateUsers),
    userWorkspaceState,
    enterpriseUserQueryFields: read(enterpriseUserQueryFields),
    enterpriseUserTableColumns: read(enterpriseUserTableColumns),
    userCountLabel: read(userCountLabel),
    customerModuleReady: read(customerModuleReady),
    canEnterCustomerWorkspace: read(canEnterCustomerWorkspace),
    canViewCustomers: read(canViewCustomers),
    customerLoading: read(customerLoading),
    customerErrorMessage: read(customerErrorMessage),
    customerWorkspaceState,
    enterpriseQueryFields: read(enterpriseQueryFields),
    enterpriseTableColumns: read(enterpriseTableColumns),
    enterpriseTableActions: read(enterpriseTableActions),
    customerCountLabel: read(customerCountLabel),
    currentQuerySummary: read(currentQuerySummary),
    enterpriseCrudCopy: read(enterpriseCrudCopy),
    customerFooterStatusLabel: localizePlatformStatus(
      vueEnterprisePresetStatus,
    ),
    customerPaginationSummary: read(customerPaginationSummary),
    customerListPageSize: read(customerListPageSize),
    customerListSortValue: read(customerListSortValue),
    customerPageInputValue: read(customerPageInputValue),
    customerPageSizeOptions: read(customerPageSizeOptions),
    customerSortOptions: read(customerSortOptions),
    canGoToPreviousCustomerPage: read(canGoToPreviousCustomerPage),
    canGoToNextCustomerPage: read(canGoToNextCustomerPage),
    canJumpToCustomerPage: read(canJumpToCustomerPage),
  }))

  const shellWorkspaceMainListeners = {
    "workflow-update-query": (value: string) => {
      void setWorkflowQuery(value)
    },
    "select-workflow-definition": handleWorkflowDefinitionSelect,
    "close-workflow-definition-detail": closeWorkflowDefinitionDetail,
    "reset-workflow-filters": resetWorkflowFilters,
    "go-previous-workflow-page": goToPreviousWorkflowPage,
    "go-next-workflow-page": goToNextWorkflowPage,
    "update-file-query": updateFileQuery,
    "reset-file-filters": resetFileQuery,
    "select-file": (fileId: string) => {
      const nextFile = fileItems.value.find((item) => item.id === fileId)

      if (nextFile) {
        void selectFile(nextFile)
      }
    },
    "open-file-upload": openFileUploadPanel,
    "update-generator-input-mode": (value: string) => {
      selectedGeneratorPreviewInputMode.value = value as
        | "registered-schema"
        | "manual-schema-json"
    },
    "update-generator-schema-name": (value: string) => {
      selectedGeneratorPreviewSchemaName.value = value
    },
    "update-generator-conflict-strategy": (value: string) => {
      selectedGeneratorPreviewConflictStrategy.value = value
    },
    "update-generator-frontend-target": (value: string) => {
      selectedGeneratorPreviewFrontendTarget.value = value
    },
    "update-generator-manual-schema-draft": (value: string) => {
      generatorPreviewManualSchemaDraft.value = value
    },
    "update-generator-query": (value: string) => {
      generatorPreviewQuery.value = value
    },
    "load-generator-current-schema-draft": loadSelectedSchemaDraft,
    "load-generator-schema-template": loadGeneratorSchemaTemplate,
    "restore-generator-session": restoreGeneratorPreviewSession,
    "select-generator-file": (value: string) => {
      selectedGeneratorPreviewFilePath.value = value
    },
    "reset-generator-filters": resetGeneratorPreviewFilters,
    "refresh-generator-preview": refreshGeneratorPreview,
    "go-to-generator-step": (step: "configure") => {
      if (step === "configure") {
        resetGeneratorPreviewState()
      }
    },
    "review-generator-preview": reviewGeneratorPreview,
    "confirm-generator-preview": confirmGeneratorPreview,
    "apply-generator-preview": applyGeneratorPreview,
    "dictionary-search": handleDictionarySearch,
    "dictionary-action": forwardCrudAction(handleDictionaryAction),
    "dictionary-reset": handleDictionaryReset,
    "dictionary-row-click": handleDictionaryRowClick,
    "department-search": handleDepartmentSearch,
    "department-action": forwardCrudAction(handleDepartmentAction),
    "department-reset": handleDepartmentReset,
    "department-row-click": handleDepartmentRowClick,
    "session-search": handleSessionSearch,
    "session-reset": handleSessionReset,
    "session-row-click": handleSessionRowClick,
    "post-search": handlePostSearch,
    "post-action": forwardCrudAction(handlePostAction),
    "post-reset": handlePostReset,
    "post-row-click": handlePostRowClick,
    "menu-search": handleMenuSearch,
    "menu-action": forwardCrudAction(handleMenuAction),
    "menu-reset": handleMenuReset,
    "menu-row-click": handleMenuRowClick,
    "notification-search": handleNotificationSearch,
    "notification-action": forwardCrudAction(handleNotificationAction),
    "notification-reset": handleNotificationReset,
    "notification-row-click": handleNotificationRowClick,
    "operation-log-search": handleOperationLogSearch,
    "operation-log-reset": handleOperationLogReset,
    "operation-log-row-click": handleOperationLogRowClick,
    "role-search": handleRoleSearch,
    "role-action": forwardCrudAction(handleRoleAction),
    "role-reset": handleRoleReset,
    "role-row-click": handleRoleRowClick,
    "setting-search": handleSettingSearch,
    "setting-action": forwardCrudAction(handleSettingAction),
    "setting-reset": handleSettingReset,
    "setting-row-click": handleSettingRowClick,
    "tenant-search": handleTenantSearch,
    "tenant-action": forwardCrudAction(handleTenantAction),
    "tenant-reset": handleTenantReset,
    "tenant-row-click": handleTenantRowClick,
    "user-search": handleUserSearch,
    "user-action": forwardCrudAction(handleUserAction),
    "user-reset": handleUserReset,
    "user-row-click": handleUserRowClick,
    "back-to-customer": openCustomerWorkspace,
    "customer-search": handleEnterpriseSearch,
    "customer-reset": handleEnterpriseReset,
    "customer-action": handleEnterpriseAction,
    "customer-row-click": handleEnterpriseRowClick,
    "change-customer-page-size": handleCustomerPageSizeChange,
    "change-customer-sort": handleCustomerSortChange,
    "go-first-customer-page": goToFirstCustomerPage,
    "go-previous-customer-page": goToPreviousCustomerPage,
    "go-next-customer-page": goToNextCustomerPage,
    "go-last-customer-page": goToLastCustomerPage,
    "update-customer-page-input": updateCustomerPageInput,
    "submit-customer-page-jump": submitCustomerPageJump,
  }

  return {
    shellWorkspaceMainProps,
    shellWorkspaceMainListeners,
  }
}
