import type { useFileWorkspace } from "../workspaces/use-file-workspace"

export type ExampleFileWorkspace = ReturnType<typeof useFileWorkspace>

export const useExampleFileWorkspaceBindings = (
  fileWorkspace: ExampleFileWorkspace,
) => {
  const {
    cancelPanel: cancelFilePanel,
    clearWorkspace: clearFileWorkspace,
    confirmDelete: confirmFileDelete,
    countLabel: fileCountLabel,
    downloadSelectedFile,
    fileActionLoading,
    fileDetailErrorMessage,
    fileDetailLoading,
    fileErrorMessage,
    fileItems,
    fileLoading,
    filePanelMode,
    fileQuery,
    filterSummary: fileFilterSummary,
    filteredFileItems,
    listQuery: fileListQuery,
    openDeletePanel: openFileDeletePanel,
    openUploadPanel: openFileUploadPanel,
    pendingUploadFile,
    reloadFiles,
    resetQuery: resetFileQuery,
    selectFile,
    selectedFile,
    selectedFileId,
    setPendingUploadFile,
    submitUpload: submitFileUpload,
    tableItems: fileTableItems,
    updateQuery: updateFileQuery,
  } = fileWorkspace

  return {
    cancelFilePanel,
    clearFileWorkspace,
    confirmFileDelete,
    fileCountLabel,
    downloadSelectedFile,
    fileActionLoading,
    fileDetailErrorMessage,
    fileDetailLoading,
    fileErrorMessage,
    fileItems,
    fileLoading,
    filePanelMode,
    fileQuery,
    fileFilterSummary,
    filteredFileItems,
    fileListQuery,
    openFileDeletePanel,
    openFileUploadPanel,
    pendingUploadFile,
    reloadFiles,
    resetFileQuery,
    selectFile,
    selectedFile,
    selectedFileId,
    setPendingUploadFile,
    submitFileUpload,
    fileTableItems,
    updateFileQuery,
  }
}
