/**
 * @generated by elysian-generator
 * schema: department
 * path: modules/department/department.schema.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import { departmentModuleSchema as sourceModuleSchema } from "@elysian/schema"
import type { ModuleSchema } from "@elysian/schema"

export type DepartmentStatus = "active" | "disabled"

export interface DepartmentRecord {
  id: string
  parentId: string
  code: string
  name: string
  sort: number
  status: DepartmentStatus
  createdAt: string
  updatedAt: string
}

export const departmentModuleSchema: ModuleSchema = sourceModuleSchema

export const moduleSchema = departmentModuleSchema
