/**
 * @generated by elysian-generator
 * schema: department
 * path: modules/department/department-workspace.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import type { FrontendWorkspaceStateContext } from "@elysian/frontend-vue"
import type { ElyFormField, ElyFormValues } from "@elysian/ui-enterprise-vue"
import type { ComputedRef } from "vue"
import { computed } from "vue"

import type { DepartmentRecord } from "./department.schema"

export interface DepartmentWorkspaceMainInjectedState {
  departmentErrorMessage: { value: string }
  departmentLoading: { value: boolean }
  tableItems: { value: DepartmentRecord[] }
}

export interface DepartmentWorkspacePanelInjectedState
  extends DepartmentWorkspaceMainInjectedState {
  formFields: { value: ElyFormField[] }
  formValues: { value: ElyFormValues }
  panelDescription: { value: string }
  panelTitle: { value: string }
  departmentDetailErrorMessage: { value: string }
  departmentDetailLoading: { value: boolean }
  departmentPanelMode: { value: "detail" | "create" | "edit" }
  selectedDepartment: { value: DepartmentRecord | null }
  parentLookup?: { value: Map<string, unknown> }
  selectedDepartmentDetail?: { value: { userIds?: string[] } | null }
}

const resolveDepartmentWorkspaceState = <TState>(
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
): TState | null => {
  if (!enabled || context?.kind !== "department") {
    return null
  }

  return context.state as TState
}

export const resolveDepartmentWorkspaceMainState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveDepartmentWorkspaceState<DepartmentWorkspaceMainInjectedState>(
    context,
    enabled,
  )

export const resolveDepartmentWorkspacePanelState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveDepartmentWorkspaceState<DepartmentWorkspacePanelInjectedState>(
    context,
    enabled,
  )

export const readInjectedValue = <TValue>(
  state: ComputedRef<{ value: TValue } | null>,
  fallback: TValue,
) => computed(() => state.value?.value ?? fallback)

const normalizeText = (value: unknown) => String(value ?? "").trim()

const normalizeOptionalText = (value: unknown) => {
  const normalized = normalizeText(value)

  return normalized.length > 0 ? normalized : undefined
}

const normalizeNumber = (value: unknown, fallback = 0) => {
  const normalized =
    typeof value === "number" ? value : Number.parseInt(String(value ?? ""), 10)

  return Number.isFinite(normalized) ? normalized : fallback
}

const normalizeJsonInput = (
  value: unknown,
):
  | { status: "valid"; value: Record<string, unknown> | null }
  | { status: "invalid" } => {
  if (value === null || value === undefined) {
    return { status: "valid", value: null }
  }

  if (typeof value === "string") {
    const normalized = value.trim()

    if (normalized.length === 0) {
      return { status: "valid", value: null }
    }

    try {
      const parsed: unknown = JSON.parse(normalized)

      if (
        typeof parsed === "object" &&
        parsed !== null &&
        !Array.isArray(parsed)
      ) {
        return {
          status: "valid",
          value: parsed as Record<string, unknown>,
        }
      }

      return { status: "invalid" }
    } catch {
      return { status: "invalid" }
    }
  }

  if (typeof value === "object" && !Array.isArray(value)) {
    return {
      status: "valid",
      value: value as Record<string, unknown>,
    }
  }

  return { status: "invalid" }
}

const stringifyJsonValue = (value: unknown) => {
  if (value === null || value === undefined) {
    return ""
  }

  return JSON.stringify(value, null, 2)
}

export const createDefaultDepartmentDraft = () => ({
  parentId: "",
  code: "",
  name: "",
  sort: 0,
  status: "active",
})

export const filterDepartmentRecords = (
  items: DepartmentRecord[],
  query: Record<string, unknown>,
): DepartmentRecord[] => {
  const code = String(query.code ?? "")
    .trim()
    .toLowerCase()
  const name = String(query.name ?? "")
    .trim()
    .toLowerCase()

  return items.filter((item) => {
    if (
      code.length > 0 &&
      !String(item.code ?? "")
        .toLowerCase()
        .includes(code)
    )
      return false
    if (
      name.length > 0 &&
      !String(item.name ?? "")
        .toLowerCase()
        .includes(name)
    )
      return false
    if (
      query.status !== undefined &&
      query.status !== null &&
      query.status !== "" &&
      item.status !== query.status
    )
      return false

    return true
  })
}

export const resolveDepartmentSelection = (
  items: Array<Pick<DepartmentRecord, "id">>,
  selectedId: string | null,
): string | null => {
  if (items.length === 0) return null

  if (selectedId && items.some((item) => item.id === selectedId)) {
    return selectedId
  }

  return items[0]?.id ?? null
}

export const normalizeDepartmentPayload = (
  values: Record<string, unknown>,
):
  | { status: "valid"; payload: Record<string, unknown> }
  | { status: "invalid"; message: string } => {
  const codeValue = String(values.code ?? "").trim()

  if (codeValue.length === 0) {
    return {
      status: "invalid" as const,
      message: "Department code is required",
    }
  }

  const nameValue = String(values.name ?? "").trim()

  if (nameValue.length === 0) {
    return {
      status: "invalid" as const,
      message: "Department name is required",
    }
  }

  return {
    status: "valid" as const,
    payload: {
      parentId: normalizeOptionalText(values.parentId),
      code: codeValue,
      name: nameValue,
      sort: normalizeNumber(values.sort, 0),
      status: values.status ?? "active",
    },
  }
}

export const toDepartmentEditDraft = (
  record: DepartmentRecord,
): Record<string, unknown> => ({
  parentId: record.parentId ?? "",
  code: record.code ?? "",
  name: record.name ?? "",
  sort: record.sort ?? 0,
  status: record.status ?? "active",
})
