/**
 * @generated by elysian-generator
 * schema: department
 * path: modules/department/department.page.vue
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

<script setup lang="ts">
import {
  ElyCrudWorkspace,
  type ElyCrudWorkspaceProps,
  type ElyQueryField,
  type ElyQueryValues,
  type ElyTableColumn,
} from "@elysian/ui-enterprise-vue"
import { computed, inject, ref, watch } from "vue"

import { WORKSPACE_STATE_KEY } from "@elysian/frontend-vue"
import {
  readInjectedValue,
  resolveDepartmentWorkspaceMainState,
} from "./department-workspace"
import type { DepartmentRecord } from "./department.schema"

type DepartmentWorkspaceTranslation = (
  key: string,
  params?: Record<string, unknown>,
) => string

interface DepartmentWorkspaceMainProps {
  t: DepartmentWorkspaceTranslation
  moduleReady: boolean
  authModuleReady: boolean
  isAuthenticated: boolean
  canEnterWorkspace: boolean
  canViewDepartments: boolean
  queryFields: ElyQueryField[]
  tableColumns: ElyTableColumn[]
  itemCountLabel: string
  emptyTitle: string
  emptyDescription: string
  currentQuerySummary: string
  copy: ElyCrudWorkspaceProps["copy"]
  workspaceStateInjected?: boolean
}

const props = defineProps<DepartmentWorkspaceMainProps>()

const emit = defineEmits<{
  (e: "search", values: ElyQueryValues): void
  (e: "reset"): void
  (e: "row-click", row: DepartmentRecord): void
}>()

const injectedWorkspaceState = inject(
  WORKSPACE_STATE_KEY,
  computed(() => null),
)

const resolvedDepartmentWorkspaceState = computed(() =>
  resolveDepartmentWorkspaceMainState(
    injectedWorkspaceState.value,
    Boolean(props.workspaceStateInjected),
  ),
)

const resolvedLoading = readInjectedValue(
  computed(
    () => resolvedDepartmentWorkspaceState.value?.departmentLoading ?? null,
  ),
  false,
)
const resolvedErrorMessage = readInjectedValue(
  computed(
    () =>
      resolvedDepartmentWorkspaceState.value?.departmentErrorMessage ?? null,
  ),
  "",
)
const resolvedItems = readInjectedValue(
  computed(() => resolvedDepartmentWorkspaceState.value?.tableItems ?? null),
  [] as DepartmentRecord[],
)

const pageSizeOptions = [20, 50, 100]
const currentPage = ref(1)
const pageSize = ref(20)
const totalPages = computed(() =>
  Math.max(1, Math.ceil(resolvedItems.value.length / pageSize.value)),
)
const pageStart = computed(() =>
  resolvedItems.value.length === 0
    ? 0
    : (currentPage.value - 1) * pageSize.value + 1,
)
const pageEnd = computed(() =>
  Math.min(resolvedItems.value.length, currentPage.value * pageSize.value),
)
const paginatedItems = computed(() =>
  resolvedItems.value.slice(
    (currentPage.value - 1) * pageSize.value,
    currentPage.value * pageSize.value,
  ),
)
const paginationSummary = computed(() =>
  props.t("app.pagination.summary", {
    page: currentPage.value,
    totalPages: totalPages.value,
    start: pageStart.value,
    end: pageEnd.value,
    total: resolvedItems.value.length,
  }),
)

const goPreviousPage = () => {
  currentPage.value = Math.max(1, currentPage.value - 1)
}

const goNextPage = () => {
  currentPage.value = Math.min(totalPages.value, currentPage.value + 1)
}

const updatePageSize = (event: Event) => {
  const nextValue = Number((event.target as HTMLSelectElement).value)

  pageSize.value = pageSizeOptions.includes(nextValue) ? nextValue : 20
  currentPage.value = 1
}

watch(resolvedItems, () => {
  currentPage.value = Math.min(currentPage.value, totalPages.value)
})
</script>

<template>
  <section class="enterprise-card enterprise-main-card">
    <div v-if="!moduleReady" class="enterprise-message enterprise-message-warning">
      {{ t("app.message.departmentModuleOffline") }}
    </div>

    <div
      v-else-if="authModuleReady && !isAuthenticated"
      class="enterprise-message enterprise-message-info"
    >
      {{ t("app.message.departmentSignInToLoad") }}
    </div>

    <div
      v-else-if="canEnterWorkspace && !canViewDepartments"
      class="enterprise-message enterprise-message-warning"
    >
      {{ t("app.message.departmentNoListPermission") }}
    </div>

    <div
      v-else-if="resolvedErrorMessage"
      class="enterprise-message enterprise-message-danger"
    >
      {{ resolvedErrorMessage }}
    </div>

    <ElyCrudWorkspace
      v-else
      :eyebrow="t('app.department.workspaceEyebrow')"
      :title="t('app.department.workspaceTitle')"
      :description="''"
      :query-fields="queryFields"
      :query-loading="resolvedLoading"
      :table-columns="tableColumns"
      :items="paginatedItems"
      :table-loading="resolvedLoading"
      :table-actions="[]"
      :item-count-label="itemCountLabel"
      :empty-title="emptyTitle"
      :empty-description="emptyDescription"
      :copy="copy"
      @search="emit('search', $event)"
      @reset="emit('reset')"
      @row-click="emit('row-click', $event as DepartmentRecord)"
    >
      <template #toolbar>
        <span class="enterprise-toolbar-pill">
          {{ currentQuerySummary }}
        </span>
      </template>
      <template #footer>
        <div class="department-pagination">
          <span>{{ paginationSummary }}</span>
          <label>
            <small>{{ t("app.pagination.pageSize") }}</small>
            <select :value="pageSize" @change="updatePageSize">
              <option
                v-for="option in pageSizeOptions"
                :key="option"
                :value="option"
              >
                {{ option }}
              </option>
            </select>
          </label>
          <button
            type="button"
            class="enterprise-button enterprise-button-ghost"
            :disabled="currentPage <= 1"
            @click="goPreviousPage"
          >
            {{ t("app.pagination.previous") }}
          </button>
          <button
            type="button"
            class="enterprise-button enterprise-button-ghost"
            :disabled="currentPage >= totalPages"
            @click="goNextPage"
          >
            {{ t("app.pagination.next") }}
          </button>
        </div>
      </template>
    </ElyCrudWorkspace>
  </section>
  </template>

<style scoped>
.department-pagination {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: flex-end;
  gap: 0.65rem;
  color: #475569;
  font-size: 0.82rem;
}

.department-pagination label {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
}

.department-pagination small {
  color: #64748b;
}

.department-pagination select {
  height: 2rem;
  border: 1px solid rgba(15, 23, 42, 0.12);
  border-radius: 4px;
  background: white;
  color: #0f172a;
}
</style>
