import { describe, expect, it } from "bun:test"

import type { ModuleSchema } from "@elysian/schema"
import {
  customerModuleSchema,
  dictionaryModuleSchema,
  notificationModuleSchema,
  postModuleSchema,
  productModuleSchema,
  roleModuleSchema,
  tenantModuleSchema,
  userModuleSchema,
} from "@elysian/schema"

import { planModuleFiles, renderModuleFiles } from "./index"

const ticketModuleSchema: ModuleSchema = {
  name: "ticket",
  label: "Ticket",
  fields: [
    { key: "id", label: "ID", kind: "id", required: true },
    { key: "title", label: "Title", kind: "string", required: true },
    { key: "priority", label: "Priority", kind: "number", required: true },
    { key: "status", label: "Status", kind: "enum", required: true },
  ],
} as const

describe("planModuleFiles", () => {
  it("plans vue page output by default", () => {
    expect(planModuleFiles(customerModuleSchema)).toEqual([
      {
        path: "modules/customer/customer.schema.ts",
        reason:
          "Persist the module schema alongside generated module artifacts.",
        mergeStrategy: "replace-whole-file",
      },
      {
        path: "modules/customer/customer.repository.ts",
        reason: "Provide the persistence-facing module repository boundary.",
        mergeStrategy: "replace-whole-file",
      },
      {
        path: "modules/customer/customer.service.ts",
        reason: "Host the generated application service entry for the module.",
        mergeStrategy: "replace-whole-file",
      },
      {
        path: "modules/customer/customer.routes.ts",
        reason:
          "Expose the server-side route registration entry for the module.",
        mergeStrategy: "replace-whole-file",
      },
      {
        path: "modules/customer/customer.frontend.ts",
        reason:
          "Emit a static frontend registration artifact for generated module integration.",
        mergeStrategy: "replace-whole-file",
      },
      {
        path: "modules/customer/customer.page.vue",
        reason:
          "Provide a generated management page implementation for the selected frontend target.",
        mergeStrategy: "replace-whole-file",
      },
    ])
  })
})

describe("renderModuleFiles", () => {
  it("renders customer artifacts with matching paths", () => {
    const files = renderModuleFiles(customerModuleSchema)
    const frontendFile = files.find((file) =>
      file.path.endsWith(".frontend.ts"),
    )
    const pageFile = files.find((file) => file.path.endsWith(".page.vue"))

    expect(files).toHaveLength(6)
    expect(files[0]?.contents).toContain("@generated by elysian-generator")
    expect(files[0]?.contents).toContain(
      'import { customerModuleSchema as sourceModuleSchema } from "@elysian/schema"',
    )
    expect(files[0]?.contents).toContain("export interface CustomerRecord")
    expect(files[1]?.contents).toContain("export interface CustomerRepository")
    expect(files[1]?.contents).toContain(
      'import type { CustomerRecord, CustomerStatus } from "./customer.schema"',
    )
    expect(files[2]?.contents).toContain("createCustomerService")
    expect(files[3]?.contents).toContain('"/customers"')
    expect(frontendFile?.contents).toContain(
      "export interface GeneratedFrontendModuleArtifact",
    )
    expect(frontendFile?.contents).toContain('moduleCode: "customer"')
    expect(frontendFile?.contents).toContain('workspaceDomain: "business"')
    expect(frontendFile?.contents).toContain('kind: "customer"')
    expect(frontendFile?.contents).toContain('surfaceKind: "page-only"')
    expect(frontendFile?.contents).toContain("panelComponentPath: null")
    expect(frontendFile?.contents).toContain('"list": "customer:customer:list"')
    expect(frontendFile?.contents).toContain(
      '"sectionTitle": "app.customer.sectionTitle"',
    )
    expect(pageFile?.path).toBe("modules/customer/customer.page.vue")
    expect(pageFile?.contents).toContain(
      'import type { CustomerRecord } from "./customer.schema"',
    )
    expect(pageFile?.contents).toContain("<template>")
  })

  it("renders react page output when requested", () => {
    const files = renderModuleFiles(customerModuleSchema, {
      frontendTarget: "react",
    })

    const frontendFile = files.find((file) =>
      file.path.endsWith(".frontend.ts"),
    )
    const pageFile = files.find((file) => file.path.endsWith(".page.tsx"))

    expect(pageFile?.path).toBe("modules/customer/customer.page.tsx")
    expect(pageFile?.contents).toContain("CustomerPage")
    expect(frontendFile?.contents).toContain('frontendTarget: "react"')
  })

  it("inlines schema artifacts when the source is an external schema file", () => {
    const files = renderModuleFiles(ticketModuleSchema, {
      schemaArtifactSource: "inline",
    })

    expect(files[0]?.contents).toContain(
      'import type { ModuleSchema } from "@elysian/schema"',
    )
    expect(files[0]?.contents).toContain(
      "export const ticketModuleSchema: ModuleSchema = {",
    )
    expect(files[0]?.contents).not.toContain(
      'import { ticketModuleSchema } from "@elysian/schema"',
    )
  })

  it("renders explicit frontend registration metadata when the schema provides it", () => {
    const files = renderModuleFiles({
      ...ticketModuleSchema,
      frontend: {
        workspaceDomain: "system",
        routePath: "/system/tickets",
        permissionPrefix: "system:ticket",
      },
    })
    const frontendFile = files.find((file) =>
      file.path.endsWith(".frontend.ts"),
    )

    expect(frontendFile?.contents).toContain('workspaceDomain: "system"')
    expect(frontendFile?.contents).toContain('routePath: "/system/tickets"')
    expect(frontendFile?.contents).toContain(
      'permissionPrefix: "system:ticket"',
    )
  })

  it("renders product routes without customer-specific status literals", () => {
    const files = renderModuleFiles(productModuleSchema)
    const routeFile = files.find((file) => file.path.endsWith(".routes.ts"))
    const repositoryFile = files.find((file) =>
      file.path.endsWith(".repository.ts"),
    )

    expect(routeFile?.contents).toContain("status: t.String({ minLength: 1 })")
    expect(routeFile?.contents).not.toContain('t.Literal("active")')
    expect(repositoryFile?.contents).toContain("sku: string")
    expect(repositoryFile?.contents).toContain("price: number")
  })

  it("uses the first meaningful string field when a schema has no name field", () => {
    const files = renderModuleFiles(ticketModuleSchema)
    const frontendFile = files.find((file) =>
      file.path.endsWith(".frontend.ts"),
    )
    const pageFile = files.find((file) => file.path.endsWith(".page.vue"))

    expect(pageFile?.contents).toContain("item.title")
    expect(pageFile?.contents).not.toContain("item.name")
    expect(frontendFile?.contents).toContain('primaryFieldKey: "title"')
  })
})

describe("enterprise CRUD templates", () => {
  it("plans 8 files for standard CRUD schemas with vue target", () => {
    const plans = planModuleFiles(postModuleSchema)

    expect(plans).toHaveLength(8)
    expect(plans.map((p) => p.path)).toEqual([
      "modules/post/post.schema.ts",
      "modules/post/post.repository.ts",
      "modules/post/post.service.ts",
      "modules/post/post.routes.ts",
      "modules/post/post.frontend.ts",
      "modules/post/post.page.vue",
      "modules/post/post-panel.vue",
      "modules/post/post-workspace.ts",
    ])
  })

  it("keeps 6 files for excluded schemas (customer)", () => {
    const plans = planModuleFiles(customerModuleSchema)

    expect(plans).toHaveLength(6)
    expect(plans[5]?.path).toBe("modules/customer/customer.page.vue")
    expect(plans[5]?.reason).toContain("management page")
  })

  it("keeps 6 files for schemas without frontend metadata", () => {
    const plans = planModuleFiles(ticketModuleSchema)

    expect(plans).toHaveLength(6)
  })

  it("keeps 6 files for react frontend target even on standard CRUD schemas", () => {
    const plans = planModuleFiles(postModuleSchema, {
      frontendTarget: "react",
    })

    expect(plans).toHaveLength(6)
  })

  it("renders enterprise Main.vue with ElyCrudWorkspace for standard CRUD", () => {
    const files = renderModuleFiles(postModuleSchema)
    const mainFile = files.find((f) => f.path === "modules/post/post.page.vue")
    const frontendFile = files.find(
      (f) => f.path === "modules/post/post.frontend.ts",
    )

    expect(mainFile?.contents).toContain("ElyCrudWorkspace")
    expect(mainFile?.contents).toContain("PostRecord")
    expect(mainFile?.contents).toContain('from "./post.schema"')
    expect(mainFile?.contents).toContain('from "./post-workspace"')
    expect(mainFile?.contents).toContain("WORKSPACE_STATE_KEY")
    expect(mainFile?.contents).toContain("readInjectedValue")
    expect(mainFile?.contents).toContain("workspaceStateInjected?: boolean")
    expect(mainFile?.contents).toContain("resolvePostWorkspaceMainState")
    expect(mainFile?.contents).toContain("resolvedPostWorkspaceState")
    expect(mainFile?.contents).toContain('t("app.message.postModuleOffline")')
    expect(mainFile?.contents).not.toContain("enterprise-toolbar-pill")
    expect(mainFile?.contents).not.toContain("currentQuerySummary")
    expect(mainFile?.contents).not.toContain("loading: boolean")
    expect(mainFile?.contents).not.toContain("items: PostRecord[]")
    expect(mainFile?.contents).not.toContain("errorMessage: string")
    expect(mainFile?.contents).not.toContain("<ul>")
    expect(frontendFile?.contents).toContain(
      'surfaceKind: "standard-crud-enterprise"',
    )
    expect(frontendFile?.contents).toContain(
      'panelComponentPath: "modules/post/post-panel.vue"',
    )
    expect(frontendFile?.contents).toContain(
      'workspaceComponentPath: "modules/post/post-workspace.ts"',
    )
  })

  it("renders enterprise Panel.vue with ElyForm for standard CRUD", () => {
    const files = renderModuleFiles(postModuleSchema)
    const panelFile = files.find(
      (f) => f.path === "modules/post/post-panel.vue",
    )

    expect(panelFile?.contents).toContain("ElyForm")
    expect(panelFile?.contents).toContain("PostRecord")
    expect(panelFile?.contents).toContain('from "./post.schema"')
    expect(panelFile?.contents).toContain('from "./post-workspace"')
    expect(panelFile?.contents).toContain("WORKSPACE_STATE_KEY")
    expect(panelFile?.contents).toContain("workspaceStateInjected?: boolean")
    expect(panelFile?.contents).toContain("readInjectedValue")
    expect(panelFile?.contents).toContain("resolvedPanelMode")
    expect(panelFile?.contents).not.toContain("panelMode: ")
    expect(panelFile?.contents).not.toContain("selectedPost: PostRecord | null")
    expect(panelFile?.contents).not.toContain("formFields: ElyFormField[]")
    expect(panelFile?.contents).not.toContain("formValues: ElyFormValues")
    expect(panelFile?.contents).toContain("start-edit")
    expect(panelFile?.contents).toContain("open-create")
    expect(panelFile?.contents).toContain("submit-form")
    expect(panelFile?.contents).toContain("cancel-panel")
  })

  it("renders workspace composable with generated helpers", () => {
    const files = renderModuleFiles(postModuleSchema)
    const workspaceFile = files.find(
      (f) => f.path === "modules/post/post-workspace.ts",
    )

    expect(workspaceFile?.contents).toContain("const normalizeText =")
    expect(workspaceFile?.contents).toContain("const normalizeOptionalText =")
    expect(workspaceFile?.contents).toContain("const normalizeNumber =")
    expect(workspaceFile?.contents).toContain(
      'import type { FrontendWorkspaceStateContext } from "@elysian/frontend-vue"',
    )
    expect(workspaceFile?.contents).toContain('from "./post.schema"')
    expect(workspaceFile?.contents).toContain(
      "export interface PostWorkspaceMainInjectedState",
    )
    expect(workspaceFile?.contents).toContain(
      "export interface PostWorkspacePanelInjectedState",
    )
    expect(workspaceFile?.contents).toContain("createDefaultPostDraft")
    expect(workspaceFile?.contents).toContain("filterPostRecords")
    expect(workspaceFile?.contents).toContain("resolvePostSelection")
    expect(workspaceFile?.contents).toContain("resolvePostWorkspaceMainState")
    expect(workspaceFile?.contents).toContain("resolvePostWorkspacePanelState")
    expect(workspaceFile?.contents).toContain("readInjectedValue")
    expect(workspaceFile?.contents).toContain("normalizePostPayload")
    expect(workspaceFile?.contents).toContain("toPostEditDraft")
    expect(workspaceFile?.contents).toContain("PostRecord")
    expect(workspaceFile?.contents).toContain("normalizeNumber(values.sort, 0)")
  })

  it("normalizes optional text fields and numeric payloads for role workspace", () => {
    const files = renderModuleFiles(roleModuleSchema)
    const workspaceFile = files.find(
      (f) => f.path === "modules/role/role-workspace.ts",
    )

    expect(workspaceFile?.contents).toContain("normalizeOptionalText")
    expect(workspaceFile?.contents).toContain("normalizeNumber")
    expect(workspaceFile?.contents).toContain('from "./role.schema"')
    expect(workspaceFile?.contents).toContain('String(item.description ?? "")')
    expect(workspaceFile?.contents).toContain(
      "normalizeOptionalText(values.description)",
    )
    expect(workspaceFile?.contents).toContain(
      "normalizeNumber(values.dataScope, 0)",
    )
  })

  it("uses dictionary-specific permission prop names in generated vue surfaces", () => {
    const files = renderModuleFiles(dictionaryModuleSchema)
    const mainFile = files.find(
      (f) => f.path === "modules/dictionary/dictionary.page.vue",
    )
    const panelFile = files.find(
      (f) => f.path === "modules/dictionary/dictionary-panel.vue",
    )

    expect(mainFile?.contents).toContain("canViewDictionaries")
    expect(panelFile?.contents).toContain("canCreateDictionaryTypes")
    expect(panelFile?.contents).toContain("canUpdateDictionaryTypes")
    expect(panelFile?.contents).toContain("selectedDictionaryTypeItems")
    expect(panelFile?.contents).toContain("localizeDictionaryStatus")
  })

  it("renders notification panel with mark-read action instead of edit action", () => {
    const files = renderModuleFiles(notificationModuleSchema)
    const panelFile = files.find(
      (f) => f.path === "modules/notification/notification-panel.vue",
    )

    expect(panelFile?.contents).toContain(`(e: "mark-read"): void`)
    expect(panelFile?.contents).toContain(`emit('mark-read')`)
    expect(panelFile?.contents).not.toContain(
      `emit('start-edit', resolvedSelectedNotification)`,
    )
  })

  it("renders tenant and user panels with their extra runtime actions", () => {
    const tenantFiles = renderModuleFiles(tenantModuleSchema)
    const tenantPanel = tenantFiles.find(
      (f) => f.path === "modules/tenant/tenant-panel.vue",
    )
    const userFiles = renderModuleFiles(userModuleSchema)
    const userPanel = userFiles.find(
      (f) => f.path === "modules/user/user-panel.vue",
    )
    const userWorkspace = userFiles.find(
      (f) => f.path === "modules/user/user-workspace.ts",
    )

    expect(tenantPanel?.contents).toContain("isSuperAdmin: boolean")
    expect(tenantPanel?.contents).toContain(`(e: "toggle-status"): void`)
    expect(tenantPanel?.contents).toContain(`emit('toggle-status')`)
    expect(userPanel?.contents).toContain("canResetUserPasswords: boolean")
    expect(userPanel?.contents).toContain("passwordInput: string")
    expect(userPanel?.contents).toContain(
      `(e: "start-password-reset", user: UserRecord): void`,
    )
    expect(userPanel?.contents).toContain(`(e: "submit-password-reset"): void`)
    expect(userWorkspace?.contents).toContain(
      `userPanelMode: { value: "detail" | "create" | "edit" | "reset" }`,
    )
  })

  it("keeps simple list page for customer (excluded from enterprise template)", () => {
    const files = renderModuleFiles(customerModuleSchema)
    const pageFile = files.find(
      (f) => f.path === "modules/customer/customer.page.vue",
    )

    expect(pageFile?.contents).toContain("customerItems")
    expect(pageFile?.contents).not.toContain("ElyCrudWorkspace")
  })
})
