import { describe, expect, it } from "bun:test"

import type { ModuleSchema } from "@elysian/schema"
import { customerModuleSchema, productModuleSchema } from "@elysian/schema"

import { planModuleFiles, renderModuleFiles } from "./index"

const ticketModuleSchema: ModuleSchema = {
  name: "ticket",
  label: "Ticket",
  fields: [
    { key: "id", label: "ID", kind: "id", required: true },
    { key: "title", label: "Title", kind: "string", required: true },
    { key: "priority", label: "Priority", kind: "number", required: true },
    { key: "status", label: "Status", kind: "enum", required: true },
  ],
} as const

describe("planModuleFiles", () => {
  it("plans vue page output by default", () => {
    expect(planModuleFiles(customerModuleSchema)).toEqual([
      {
        path: "modules/customer/customer.schema.ts",
        reason:
          "Persist the module schema alongside generated module artifacts.",
        mergeStrategy: "replace-whole-file",
      },
      {
        path: "modules/customer/customer.repository.ts",
        reason: "Provide the persistence-facing module repository boundary.",
        mergeStrategy: "replace-whole-file",
      },
      {
        path: "modules/customer/customer.service.ts",
        reason: "Host the generated application service entry for the module.",
        mergeStrategy: "replace-whole-file",
      },
      {
        path: "modules/customer/customer.routes.ts",
        reason:
          "Expose the server-side route registration entry for the module.",
        mergeStrategy: "replace-whole-file",
      },
      {
        path: "modules/customer/customer.page.vue",
        reason:
          "Provide a generated management page implementation for the selected frontend target.",
        mergeStrategy: "replace-whole-file",
      },
    ])
  })
})

describe("renderModuleFiles", () => {
  it("renders customer artifacts with matching paths", () => {
    const files = renderModuleFiles(customerModuleSchema)

    expect(files).toHaveLength(5)
    expect(files[0]?.contents).toContain("@generated by elysian-generator")
    expect(files[0]?.contents).toContain(
      'import { customerModuleSchema as sourceModuleSchema } from "@elysian/schema"',
    )
    expect(files[0]?.contents).toContain("export interface CustomerRecord")
    expect(files[1]?.contents).toContain("export interface CustomerRepository")
    expect(files[1]?.contents).toContain(
      'import type { CustomerRecord, CustomerStatus } from "./customer.schema"',
    )
    expect(files[2]?.contents).toContain("createCustomerService")
    expect(files[3]?.contents).toContain('"/customers"')
    expect(files[4]?.path).toBe("modules/customer/customer.page.vue")
    expect(files[4]?.contents).toContain(
      'import type { CustomerRecord } from "./customer.schema"',
    )
    expect(files[4]?.contents).toContain("<template>")
  })

  it("renders react page output when requested", () => {
    const files = renderModuleFiles(customerModuleSchema, {
      frontendTarget: "react",
    })

    expect(files[4]?.path).toBe("modules/customer/customer.page.tsx")
    expect(files[4]?.contents).toContain("CustomerPage")
  })

  it("inlines schema artifacts when the source is an external schema file", () => {
    const files = renderModuleFiles(ticketModuleSchema, {
      schemaArtifactSource: "inline",
    })

    expect(files[0]?.contents).toContain(
      'import type { ModuleSchema } from "@elysian/schema"',
    )
    expect(files[0]?.contents).toContain(
      "export const ticketModuleSchema: ModuleSchema = {",
    )
    expect(files[0]?.contents).not.toContain(
      'import { ticketModuleSchema } from "@elysian/schema"',
    )
  })

  it("renders product routes without customer-specific status literals", () => {
    const files = renderModuleFiles(productModuleSchema)
    const routeFile = files.find((file) => file.path.endsWith(".routes.ts"))
    const repositoryFile = files.find((file) =>
      file.path.endsWith(".repository.ts"),
    )

    expect(routeFile?.contents).toContain("status: t.String({ minLength: 1 })")
    expect(routeFile?.contents).not.toContain('t.Literal("active")')
    expect(repositoryFile?.contents).toContain("sku: string")
    expect(repositoryFile?.contents).toContain("price: number")
  })

  it("uses the first meaningful string field when a schema has no name field", () => {
    const files = renderModuleFiles(ticketModuleSchema)

    expect(files[4]?.contents).toContain("item.title")
    expect(files[4]?.contents).not.toContain("item.name")
  })
})
