import { constants as fsConstants } from "node:fs"
import { access, readFile } from "node:fs/promises"
import { resolve } from "node:path"

import type { RenderedModuleFile } from "./core"

export type GeneratedConflictStrategy =
  | "skip"
  | "overwrite"
  | "overwrite-generated-only"
  | "fail"

export interface ResolvedGeneratedFileTarget {
  file: RenderedModuleFile
  absolutePath: string
  exists: boolean
  isManaged: boolean | null
  currentContents: string | null
  hasChanges: boolean
}

export const GENERATED_HEADER_MARKER = "@generated by elysian-generator"

const fileExists = async (targetPath: string) => {
  try {
    await access(targetPath, fsConstants.F_OK)
    return true
  } catch {
    return false
  }
}

const hasGeneratedHeader = (contents: string) =>
  contents.includes(GENERATED_HEADER_MARKER)

export const collectGeneratedFileTargets = async (
  renderedFiles: RenderedModuleFile[],
  outputDir: string,
): Promise<ResolvedGeneratedFileTarget[]> =>
  Promise.all(
    renderedFiles.map(async (file) => {
      const absolutePath = resolve(outputDir, file.path)
      const exists = await fileExists(absolutePath)
      const currentContents = exists
        ? await readFile(absolutePath, "utf8")
        : null

      return {
        file,
        absolutePath,
        exists,
        isManaged:
          currentContents === null ? null : hasGeneratedHeader(currentContents),
        currentContents,
        hasChanges: currentContents !== file.contents,
      }
    }),
  )
