import { describe, expect, it } from "bun:test"
import { mkdir, mkdtemp, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { dirname, join } from "node:path"

import type { ModuleSchema } from "@elysian/schema"
import { customerModuleSchema } from "@elysian/schema"

import { buildGenerationPreviewReport, previewModuleFiles } from "./preview"
import { renderModuleSqlPreview } from "./sql-preview"
import { writeModuleFiles } from "./write"

const ticketModuleSchema: ModuleSchema = {
  name: "ticket",
  label: "Ticket",
  fields: [
    { key: "id", label: "ID", kind: "id", required: true },
    { key: "title", label: "Title", kind: "string", required: true },
    {
      key: "status",
      label: "Status",
      kind: "enum",
      required: true,
      options: [
        { label: "Open", value: "open" },
        { label: "Closed", value: "closed" },
      ],
    },
    { key: "openedAt", label: "Opened At", kind: "datetime" },
  ],
}

describe("previewModuleFiles", () => {
  it("returns create actions for missing files", async () => {
    const directory = await mkdtemp(
      join(tmpdir(), "elysian-generator-preview-"),
    )
    const preview = await previewModuleFiles(customerModuleSchema, {
      outputDir: directory,
      frontendTarget: "vue",
    })

    expect(preview).toHaveLength(5)
    expect(preview.every((item) => item.plannedAction === "create")).toBe(true)
    expect(preview.every((item) => item.currentContents === null)).toBe(true)
  })

  it("returns overwrite actions for managed files with overwrite-generated-only", async () => {
    const directory = await mkdtemp(
      join(tmpdir(), "elysian-generator-preview-"),
    )

    await writeModuleFiles(customerModuleSchema, {
      outputDir: directory,
      frontendTarget: "vue",
    })

    const preview = await previewModuleFiles(customerModuleSchema, {
      outputDir: directory,
      frontendTarget: "vue",
      conflictStrategy: "overwrite-generated-only",
    })

    expect(preview.every((item) => item.plannedAction === "overwrite")).toBe(
      true,
    )
    expect(preview.every((item) => item.hasChanges === false)).toBe(true)
  })

  it("returns block actions for unmanaged files with overwrite-generated-only", async () => {
    const directory = await mkdtemp(
      join(tmpdir(), "elysian-generator-preview-"),
    )
    const unmanagedPath = join(directory, "modules/customer/customer.schema.ts")

    await mkdir(dirname(unmanagedPath), { recursive: true })
    await writeFile(unmanagedPath, "export const manual = true\n", "utf8")

    const preview = await previewModuleFiles(customerModuleSchema, {
      outputDir: directory,
      frontendTarget: "vue",
      conflictStrategy: "overwrite-generated-only",
    })
    const schemaPreview = preview.find(
      (item) => item.path === "modules/customer/customer.schema.ts",
    )

    expect(schemaPreview?.plannedAction).toBe("block")
    expect(schemaPreview?.isManaged).toBe(false)
    expect(schemaPreview?.hasChanges).toBe(true)
  })
})

describe("buildGenerationPreviewReport", () => {
  it("builds a report with file preview and sql preview", async () => {
    const directory = await mkdtemp(
      join(tmpdir(), "elysian-generator-preview-"),
    )
    const report = await buildGenerationPreviewReport(ticketModuleSchema, {
      outputDir: directory,
      frontendTarget: "vue",
      conflictStrategy: "fail",
    })

    expect(report.schemaName).toBe("ticket")
    expect(report.conflictStrategy).toBe("fail")
    expect(report.databaseChangePlan.operations[0]?.tableName).toBe("ticket")
    expect(report.databaseChangePlan.operations[0]?.columns[3]?.name).toBe(
      "opened_at",
    )
    expect(report.files[0]?.contents).toContain(
      "@generated by elysian-generator",
    )
    expect(report.sqlPreview.dialect).toBe("postgresql")
    expect(report.sqlPreview.contents).toContain("CREATE TABLE ticket (")
    expect(report.sqlPreview.contents).toContain("opened_at timestamptz")
    expect(report.sqlPreview.contents).toContain(
      "-- status options: open, closed",
    )
  })
})

describe("renderModuleSqlPreview", () => {
  it("renders a review-only SQL preview from schema fields", () => {
    const sqlPreview = renderModuleSqlPreview(ticketModuleSchema)

    expect(sqlPreview.contents).toContain(
      "-- Canonical migration ownership remains in packages/persistence.",
    )
    expect(sqlPreview.contents).toContain(
      "id uuid PRIMARY KEY DEFAULT gen_random_uuid()",
    )
    expect(sqlPreview.contents).toContain("title text NOT NULL")
  })
})
