import { randomUUID } from "node:crypto"
import { access, mkdir, rename, rm, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"

import type { ModuleSchema } from "@elysian/schema"

import type { GenerationTargetPreset } from "./conventions"
import {
  type FrontendTarget,
  type RenderedModuleFile,
  renderModuleFiles,
} from "./index"

export type WriteConflictStrategy =
  | "skip"
  | "overwrite"
  | "overwrite-generated-only"
  | "fail"

export interface WriteModuleFilesOptions {
  outputDir: string
  frontendTarget?: FrontendTarget
  schemaArtifactSource?: "package" | "inline"
  conflictStrategy?: WriteConflictStrategy
  writeManifest?: boolean
  targetPreset?: GenerationTargetPreset
}

export interface WrittenModuleFile extends RenderedModuleFile {
  absolutePath: string
  written: boolean
}

export interface GenerationManifest {
  schemaName: string
  frontendTarget: FrontendTarget
  generatedAt: string
  conflictStrategy: WriteConflictStrategy
  outputDir: string
  targetPreset: GenerationTargetPreset | "custom"
  files: Array<{
    path: string
    absolutePath: string
    written: boolean
    reason: string
    mergeStrategy: string
  }>
}

const GENERATED_HEADER_MARKER = "@generated by elysian-generator"

const hasGeneratedHeader = async (absolutePath: string) => {
  const existingContents = await Bun.file(absolutePath).text()
  return existingContents.includes(GENERATED_HEADER_MARKER)
}

const fileExists = async (absolutePath: string) => {
  try {
    await access(absolutePath)
    return true
  } catch {
    return false
  }
}

const buildTempPath = (absolutePath: string) =>
  `${absolutePath}.tmp-${process.pid}-${randomUUID()}`

const RETRYABLE_RENAME_ERROR_CODES = new Set(["EPERM", "EBUSY", "EACCES"])
const MAX_RENAME_RETRIES = 5

const getErrorCode = (error: unknown): string | null =>
  typeof error === "object" &&
  error !== null &&
  "code" in error &&
  typeof error.code === "string"
    ? error.code
    : null

const writeFileAtomically = async (absolutePath: string, contents: string) => {
  const tempPath = buildTempPath(absolutePath)

  await writeFile(tempPath, contents, "utf8")

  for (let attempt = 0; attempt <= MAX_RENAME_RETRIES; attempt += 1) {
    try {
      await rename(tempPath, absolutePath)
      return
    } catch (error) {
      const errorCode = getErrorCode(error)
      const canRetry =
        errorCode !== null &&
        RETRYABLE_RENAME_ERROR_CODES.has(errorCode) &&
        attempt < MAX_RENAME_RETRIES

      if (canRetry) {
        await Bun.sleep((attempt + 1) * 10)
        continue
      }

      await rm(tempPath, { force: true })
      throw error
    }
  }

  throw new Error(`Atomic write retries exhausted: ${absolutePath}`)
}

export const writeModuleFiles = async (
  schema: ModuleSchema,
  options: WriteModuleFilesOptions,
): Promise<WrittenModuleFile[]> => {
  const frontendTarget = options.frontendTarget ?? "vue"
  const conflictStrategy = options.conflictStrategy ?? "skip"
  const renderedFiles = renderModuleFiles(schema, {
    frontendTarget,
    schemaArtifactSource: options.schemaArtifactSource,
  })
  const filesToWrite = await Promise.all(
    renderedFiles.map(async (file) => {
      const absolutePath = resolve(options.outputDir, file.path)
      const exists = await fileExists(absolutePath)
      const isManaged =
        conflictStrategy === "overwrite-generated-only" && exists
          ? await hasGeneratedHeader(absolutePath)
          : undefined

      return {
        file,
        absolutePath,
        exists,
        isManaged,
      }
    }),
  )

  if (conflictStrategy === "fail") {
    const conflict = filesToWrite.find((entry) => entry.exists)
    if (conflict) {
      throw new Error(
        `Refusing to overwrite existing file: ${conflict.absolutePath}`,
      )
    }
  }

  if (conflictStrategy === "overwrite-generated-only") {
    const conflict = filesToWrite.find(
      (entry) => entry.exists && !entry.isManaged,
    )
    if (conflict) {
      throw new Error(
        `Refusing to overwrite unmanaged file with overwrite-generated-only strategy: ${conflict.absolutePath}`,
      )
    }
  }

  const results: WrittenModuleFile[] = []

  for (const entry of filesToWrite) {
    const { file, absolutePath, exists } = entry
    await mkdir(dirname(absolutePath), { recursive: true })

    if (exists && conflictStrategy === "skip") {
      results.push({
        ...file,
        absolutePath,
        written: false,
      })
      continue
    }

    await writeFileAtomically(absolutePath, file.contents)

    results.push({
      ...file,
      absolutePath,
      written: true,
    })
  }

  if (options.writeManifest !== false) {
    const manifestPath = resolve(
      options.outputDir,
      ".elysian-generator",
      `${schema.name}.${frontendTarget}.json`,
    )
    const manifest: GenerationManifest = {
      schemaName: schema.name,
      frontendTarget,
      generatedAt: new Date().toISOString(),
      conflictStrategy,
      outputDir: resolve(options.outputDir),
      targetPreset: options.targetPreset ?? "custom",
      files: results.map((file) => ({
        path: file.path,
        absolutePath: file.absolutePath,
        written: file.written,
        reason: file.reason,
        mergeStrategy: file.mergeStrategy,
      })),
    }

    await mkdir(dirname(manifestPath), { recursive: true })
    await writeFileAtomically(manifestPath, JSON.stringify(manifest, null, 2))
  }

  return results
}
