/**
 * @generated by elysian-generator
 * schema: role
 * path: modules/role/role.schema.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import { roleModuleSchema as sourceModuleSchema } from "@elysian/schema"
import type { ModuleSchema } from "@elysian/schema"

export type RoleStatus = "active" | "disabled"

export interface RoleRecord {
  id: string
  code: string
  name: string
  description: string
  status: RoleStatus
  isSystem: boolean
  dataScope: number
  createdAt: string
  updatedAt: string
}

export const roleModuleSchema: ModuleSchema = sourceModuleSchema

export const moduleSchema = roleModuleSchema
