/**
 * @generated by elysian-generator
 * schema: role
 * path: modules/role/role-workspace.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import type { FrontendWorkspaceStateContext } from "@elysian/frontend-vue"
import type { ElyFormField, ElyFormValues } from "@elysian/ui-enterprise-vue"
import type { ComputedRef } from "vue"
import { computed } from "vue"

import type { RoleRecord } from "./role.schema"

export interface RoleWorkspaceMainInjectedState {
  roleErrorMessage: { value: string }
  roleLoading: { value: boolean }
  tableItems: { value: RoleRecord[] }
}

export interface RoleWorkspacePanelInjectedState
  extends RoleWorkspaceMainInjectedState {
  formFields: { value: ElyFormField[] }
  formValues: { value: ElyFormValues }
  panelDescription: { value: string }
  panelTitle: { value: string }
  roleDetailErrorMessage: { value: string }
  roleDetailLoading: { value: boolean }
  rolePanelMode: { value: "detail" | "create" | "edit" }
  selectedRole: { value: RoleRecord | null }
  selectedRoleDetail?: {
    value: {
      permissionCodes?: string[]
      userIds?: string[]
      deptIds?: string[]
    } | null
  }
}

const resolveRoleWorkspaceState = <TState>(
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
): TState | null => {
  if (!enabled || context?.kind !== "role") {
    return null
  }

  return context.state as TState
}

export const resolveRoleWorkspaceMainState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) => resolveRoleWorkspaceState<RoleWorkspaceMainInjectedState>(context, enabled)

export const resolveRoleWorkspacePanelState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveRoleWorkspaceState<RoleWorkspacePanelInjectedState>(context, enabled)

export const readInjectedValue = <TValue>(
  state: ComputedRef<{ value: TValue } | null>,
  fallback: TValue,
) => computed(() => state.value?.value ?? fallback)

const normalizeText = (value: unknown) => String(value ?? "").trim()

const normalizeOptionalText = (value: unknown) => {
  const normalized = normalizeText(value)

  return normalized.length > 0 ? normalized : undefined
}

const normalizeNumber = (value: unknown, fallback = 0) => {
  const normalized =
    typeof value === "number" ? value : Number.parseInt(String(value ?? ""), 10)

  return Number.isFinite(normalized) ? normalized : fallback
}

const normalizeJsonInput = (
  value: unknown,
):
  | { status: "valid"; value: Record<string, unknown> | null }
  | { status: "invalid" } => {
  if (value === null || value === undefined) {
    return { status: "valid", value: null }
  }

  if (typeof value === "string") {
    const normalized = value.trim()

    if (normalized.length === 0) {
      return { status: "valid", value: null }
    }

    try {
      const parsed: unknown = JSON.parse(normalized)

      if (
        typeof parsed === "object" &&
        parsed !== null &&
        !Array.isArray(parsed)
      ) {
        return {
          status: "valid",
          value: parsed as Record<string, unknown>,
        }
      }

      return { status: "invalid" }
    } catch {
      return { status: "invalid" }
    }
  }

  if (typeof value === "object" && !Array.isArray(value)) {
    return {
      status: "valid",
      value: value as Record<string, unknown>,
    }
  }

  return { status: "invalid" }
}

const stringifyJsonValue = (value: unknown) => {
  if (value === null || value === undefined) {
    return ""
  }

  return JSON.stringify(value, null, 2)
}

export const createDefaultRoleDraft = () => ({
  code: "",
  name: "",
  description: "",
  status: "active",
  isSystem: false,
  dataScope: 0,
})

export const filterRoleRecords = (
  items: RoleRecord[],
  query: Record<string, unknown>,
): RoleRecord[] => {
  const code = String(query.code ?? "")
    .trim()
    .toLowerCase()
  const name = String(query.name ?? "")
    .trim()
    .toLowerCase()
  const description = String(query.description ?? "")
    .trim()
    .toLowerCase()

  return items.filter((item) => {
    if (
      code.length > 0 &&
      !String(item.code ?? "")
        .toLowerCase()
        .includes(code)
    )
      return false
    if (
      name.length > 0 &&
      !String(item.name ?? "")
        .toLowerCase()
        .includes(name)
    )
      return false
    if (
      description.length > 0 &&
      !String(item.description ?? "")
        .toLowerCase()
        .includes(description)
    )
      return false
    if (
      query.status !== undefined &&
      query.status !== null &&
      query.status !== "" &&
      item.status !== query.status
    )
      return false

    return true
  })
}

export const resolveRoleSelection = (
  items: Array<Pick<RoleRecord, "id">>,
  selectedId: string | null,
): string | null => {
  if (items.length === 0) return null

  if (selectedId && items.some((item) => item.id === selectedId)) {
    return selectedId
  }

  return items[0]?.id ?? null
}

export const normalizeRolePayload = (
  values: Record<string, unknown>,
):
  | { status: "valid"; payload: Record<string, unknown> }
  | { status: "invalid"; message: string } => {
  const codeValue = String(values.code ?? "").trim()

  if (codeValue.length === 0) {
    return { status: "invalid" as const, message: "Role code is required" }
  }

  const nameValue = String(values.name ?? "").trim()

  if (nameValue.length === 0) {
    return { status: "invalid" as const, message: "Role name is required" }
  }

  return {
    status: "valid" as const,
    payload: {
      code: codeValue,
      name: nameValue,
      description: normalizeOptionalText(values.description),
      status: values.status ?? "active",
      isSystem: values.isSystem ?? false,
      dataScope: normalizeNumber(values.dataScope, 0),
    },
  }
}

export const toRoleEditDraft = (
  record: RoleRecord,
): Record<string, unknown> => ({
  code: record.code ?? "",
  name: record.name ?? "",
  description: record.description ?? "",
  status: record.status ?? "active",
  isSystem: record.isSystem ?? false,
  dataScope: record.dataScope ?? 0,
})
