import { mkdir, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import {
  type FrontendTarget,
  isStandardCrudSchema,
  renderFrontendArtifactModule,
} from "@elysian/generator"
import {
  customerModuleSchema,
  departmentModuleSchema,
  dictionaryModuleSchema,
  fileModuleSchema,
  menuModuleSchema,
  notificationModuleSchema,
  operationLogModuleSchema,
  postModuleSchema,
  roleModuleSchema,
  settingModuleSchema,
  tenantModuleSchema,
  userModuleSchema,
  workflowModuleSchema,
} from "@elysian/schema"

const frontendTarget: FrontendTarget = "vue"

const moduleSchemas = [
  customerModuleSchema,
  departmentModuleSchema,
  dictionaryModuleSchema,
  fileModuleSchema,
  menuModuleSchema,
  notificationModuleSchema,
  operationLogModuleSchema,
  postModuleSchema,
  roleModuleSchema,
  settingModuleSchema,
  tenantModuleSchema,
  userModuleSchema,
  workflowModuleSchema,
]

const scriptDirectory = fileURLToPath(new URL(".", import.meta.url))
const outputDirectory = join(
  scriptDirectory,
  "../src/app/workspace-registry/generated",
)

const withGeneratedHeader = (schemaName: string, contents: string) => `/**
 * @generated by example-vue workspace artifact generator
 * schema: ${schemaName}
 * manual-edits: discouraged
 */

${contents}`

const main = async () => {
  await mkdir(outputDirectory, { recursive: true })

  const imports: string[] = []
  const exports: string[] = []
  const artifactNames: string[] = []
  const standardCrudArtifactNames: string[] = []

  for (const schema of moduleSchemas) {
    const artifact = renderFrontendArtifactModule(schema, frontendTarget)
    const outputPath = join(
      outputDirectory,
      `${schema.name}.frontend.generated.ts`,
    )

    await mkdir(dirname(outputPath), { recursive: true })
    await writeFile(
      outputPath,
      withGeneratedHeader(schema.name, artifact.contents),
      "utf8",
    )

    imports.push(
      `import { ${artifact.artifactName} } from "./${schema.name}.frontend.generated"`,
    )
    exports.push(`export { ${artifact.artifactName} }`)
    artifactNames.push(artifact.artifactName)

    if (isStandardCrudSchema(schema)) {
      standardCrudArtifactNames.push(artifact.artifactName)
    }
  }

  await writeFile(
    join(outputDirectory, "index.ts"),
    withGeneratedHeader(
      "workspace-registry-index",
      `${imports.join("\n")}

${exports.join("\n")}

export const generatedFrontendModuleArtifacts = [
${artifactNames.map((name) => `  ${name},`).join("\n")}
] as const

export const generatedStandardCrudFrontendModuleArtifacts = [
${standardCrudArtifactNames.map((name) => `  ${name},`).join("\n")}
] as const

export const generatedStandardCrudWorkspaceKinds = [
${standardCrudArtifactNames.map((name) => `  ${name}.kind,`).join("\n")}
] as const
`,
    ),
    "utf8",
  )
}

await main()
