import { mkdir, writeFile } from "node:fs/promises"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { renderModuleFiles } from "@elysian/generator"
import { isStandardCrudSchema } from "@elysian/generator"
import { registeredModuleSchemas } from "@elysian/schema"

const frontendTarget = "vue" as const

const moduleSchemas = registeredModuleSchemas.filter((schema) =>
  isStandardCrudSchema(schema),
)

const scriptDirectory = fileURLToPath(new URL(".", import.meta.url))
const srcDirectory = join(scriptDirectory, "../src")
const modulesOutputDirectory = join(srcDirectory, "modules")
const generatedIndexOutputPath = join(
  srcDirectory,
  "modules/generated/index.ts",
)

const isSurfaceFile = (path: string) =>
  path.endsWith(".schema.ts") ||
  path.endsWith(".page.vue") ||
  path.endsWith("-panel.vue") ||
  path.endsWith("-workspace.ts")

const toPascalCase = (value: string) =>
  value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((segment) => segment[0]?.toUpperCase() + segment.slice(1))
    .join("")

const toGeneratedImportPath = (modulePath: string) =>
  `../${modulePath.replace(/^modules\//, "")}`

const withGeneratedHeader = (contents: string) => `/**
 * @generated by example-vue standard CRUD surface generator
 * manual-edits: discouraged
 */

${contents}`

const runBiomeWrite = (targetPath: string) => {
  const result = Bun.spawnSync(
    [
      "bunx",
      "@biomejs/biome@1.9.4",
      "check",
      "--write",
      "--unsafe",
      targetPath,
    ],
    {
      cwd: join(scriptDirectory, ".."),
      stdout: "inherit",
      stderr: "inherit",
    },
  )

  if (result.exitCode !== 0) {
    throw new Error(`Biome write failed for ${targetPath}`)
  }
}

const renderGeneratedIndex = () => {
  const importLines: string[] = []
  const mainEntries: string[] = []
  const panelEntries: string[] = []

  for (const schema of moduleSchemas) {
    const moduleName = toPascalCase(schema.name)
    const workspaceKind = schema.frontend?.workspaceKind ?? schema.name
    const mainComponentPath = `modules/${schema.name}/${schema.name}.page.vue`
    const panelComponentPath = `modules/${schema.name}/${schema.name}-panel.vue`

    importLines.push(
      `const ${moduleName}WorkspaceMain = defineAsyncComponent(() => import(${JSON.stringify(
        toGeneratedImportPath(mainComponentPath),
      )}))`,
    )
    importLines.push(
      `const ${moduleName}WorkspacePanel = defineAsyncComponent(() => import(${JSON.stringify(
        toGeneratedImportPath(panelComponentPath),
      )}))`,
    )

    mainEntries.push(
      `  ${JSON.stringify(workspaceKind)}: ${moduleName}WorkspaceMain,`,
    )
    panelEntries.push(
      `  ${JSON.stringify(workspaceKind)}: ${moduleName}WorkspacePanel,`,
    )
  }

  return withGeneratedHeader(`import { defineAsyncComponent } from "vue"

${importLines.join("\n")}

export const generatedStandardCrudMainComponents = {
${mainEntries.join("\n")}
} as const

export const generatedStandardCrudPanelComponents = {
${panelEntries.join("\n")}
} as const
`)
}

const main = async () => {
  for (const schema of moduleSchemas) {
    const renderedFiles = renderModuleFiles(schema, {
      frontendTarget,
    }).filter((file) => isSurfaceFile(file.path))

    for (const file of renderedFiles) {
      const outputPath = join(srcDirectory, file.path)
      await mkdir(dirname(outputPath), { recursive: true })
      await writeFile(outputPath, file.contents, "utf8")
    }
  }

  await mkdir(dirname(generatedIndexOutputPath), { recursive: true })
  await writeFile(generatedIndexOutputPath, renderGeneratedIndex(), "utf8")
  runBiomeWrite(modulesOutputDirectory)
}

await main()
