import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

import { renderModuleFiles } from "@elysian/generator"
import {
  departmentModuleSchema,
  dictionaryModuleSchema,
  menuModuleSchema,
  notificationModuleSchema,
  postModuleSchema,
  roleModuleSchema,
  settingModuleSchema,
  tenantModuleSchema,
  userModuleSchema,
} from "@elysian/schema"

const frontendTarget = "vue" as const

const moduleSchemas = [
  departmentModuleSchema,
  dictionaryModuleSchema,
  menuModuleSchema,
  notificationModuleSchema,
  postModuleSchema,
  roleModuleSchema,
  settingModuleSchema,
  tenantModuleSchema,
  userModuleSchema,
]

const scriptDirectory = fileURLToPath(new URL(".", import.meta.url))
const appDirectory = join(scriptDirectory, "..")
const committedModulesDirectory = join(appDirectory, "src/modules")

const isSurfaceFile = (path: string) =>
  path.endsWith(".schema.ts") ||
  path.endsWith(".page.vue") ||
  path.endsWith("-panel.vue") ||
  path.endsWith("-workspace.ts")

const toPascalCase = (value: string) =>
  value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((segment) => segment[0]?.toUpperCase() + segment.slice(1))
    .join("")

const toGeneratedImportPath = (modulePath: string) =>
  `../${modulePath.replace(/^modules\//, "")}`

const withGeneratedHeader = (contents: string) => `/**
 * @generated by example-vue standard CRUD surface generator
 * manual-edits: discouraged
 */

${contents}`

const renderGeneratedIndex = () => {
  const importLines: string[] = []
  const mainEntries: string[] = []
  const panelEntries: string[] = []

  for (const schema of moduleSchemas) {
    const moduleName = toPascalCase(schema.name)
    const workspaceKind = schema.frontend?.workspaceKind ?? schema.name

    importLines.push(
      `import ${moduleName}WorkspaceMain from ${JSON.stringify(
        toGeneratedImportPath(`modules/${schema.name}/${schema.name}.page.vue`),
      )}`,
    )
    importLines.push(
      `import ${moduleName}WorkspacePanel from ${JSON.stringify(
        toGeneratedImportPath(
          `modules/${schema.name}/${schema.name}-panel.vue`,
        ),
      )}`,
    )
    mainEntries.push(
      `  ${JSON.stringify(workspaceKind)}: ${moduleName}WorkspaceMain,`,
    )
    panelEntries.push(
      `  ${JSON.stringify(workspaceKind)}: ${moduleName}WorkspacePanel,`,
    )
  }

  return withGeneratedHeader(`${importLines.join("\n")}

export const generatedStandardCrudMainComponents = {
${mainEntries.join("\n")}
} as const

export const generatedStandardCrudPanelComponents = {
${panelEntries.join("\n")}
} as const
`)
}

const runBiomeWrite = (targetPath: string) => {
  const result = Bun.spawnSync(
    [
      "bunx",
      "@biomejs/biome@1.9.4",
      "check",
      "--write",
      "--unsafe",
      targetPath,
    ],
    {
      cwd: appDirectory,
      stdout: "inherit",
      stderr: "inherit",
    },
  )

  if (result.exitCode !== 0) {
    throw new Error(`Biome write failed for ${targetPath}`)
  }
}

const main = async () => {
  const tempRoot = await mkdtemp(join(tmpdir(), "elysian-standard-crud-"))
  const tempModulesDirectory = join(tempRoot, "src/modules")

  try {
    for (const schema of moduleSchemas) {
      const renderedFiles = renderModuleFiles(schema, {
        frontendTarget,
      }).filter((file) => isSurfaceFile(file.path))

      for (const file of renderedFiles) {
        const outputPath = join(tempRoot, "src", file.path)
        await mkdir(dirname(outputPath), { recursive: true })
        await writeFile(outputPath, file.contents, "utf8")
      }
    }

    const generatedIndexOutputPath = join(
      tempModulesDirectory,
      "generated/index.ts",
    )
    await mkdir(dirname(generatedIndexOutputPath), { recursive: true })
    await writeFile(generatedIndexOutputPath, renderGeneratedIndex(), "utf8")
    runBiomeWrite(tempModulesDirectory)

    for (const schema of moduleSchemas) {
      const renderedFiles = renderModuleFiles(schema, {
        frontendTarget,
      }).filter((file) => isSurfaceFile(file.path))

      for (const file of renderedFiles) {
        const committedPath = join(appDirectory, "src", file.path)
        const tempPath = join(tempRoot, "src", file.path)
        const [committedContents, tempContents] = await Promise.all([
          readFile(committedPath, "utf8"),
          readFile(tempPath, "utf8"),
        ])

        if (committedContents !== tempContents) {
          throw new Error(`Generated surface drift detected: ${file.path}`)
        }
      }
    }

    const [committedIndexContents, tempIndexContents] = await Promise.all([
      readFile(join(committedModulesDirectory, "generated/index.ts"), "utf8"),
      readFile(join(tempModulesDirectory, "generated/index.ts"), "utf8"),
    ])

    if (committedIndexContents !== tempIndexContents) {
      throw new Error("Generated standard CRUD index drift detected")
    }
  } finally {
    await rm(tempRoot, { recursive: true, force: true })
  }
}

await main()
