import type { DefaultAuthSeedConfig, DefaultAuthSeedSpec } from "./seed-spec"

export const defaultAuthSeedIds = {
  roles: {
    admin: "00000000-0000-0000-0000-000000000001",
    operator: "00000000-0000-0000-0000-000000000002",
  },
  permissions: {
    systemUserList: "00000000-0000-0000-0000-000000000101",
    systemUserCreate: "00000000-0000-0000-0000-000000000102",
    systemUserUpdate: "00000000-0000-0000-0000-000000000103",
    systemUserResetPassword: "00000000-0000-0000-0000-000000000104",
    systemRoleList: "00000000-0000-0000-0000-000000000111",
    systemRoleCreate: "00000000-0000-0000-0000-000000000112",
    systemRoleUpdate: "00000000-0000-0000-0000-000000000113",
    systemMenuList: "00000000-0000-0000-0000-000000000121",
    systemMenuUpdate: "00000000-0000-0000-0000-000000000122",
    systemDepartmentList: "00000000-0000-0000-0000-000000000131",
    systemDepartmentCreate: "00000000-0000-0000-0000-000000000132",
    systemDepartmentUpdate: "00000000-0000-0000-0000-000000000133",
    systemPostList: "00000000-0000-0000-0000-000000000134",
    systemPostCreate: "00000000-0000-0000-0000-000000000135",
    systemPostUpdate: "00000000-0000-0000-0000-000000000136",
    systemDictionaryList: "00000000-0000-0000-0000-000000000141",
    systemDictionaryCreate: "00000000-0000-0000-0000-000000000142",
    systemDictionaryUpdate: "00000000-0000-0000-0000-000000000143",
    systemSettingList: "00000000-0000-0000-0000-000000000151",
    systemSettingCreate: "00000000-0000-0000-0000-000000000152",
    systemSettingUpdate: "00000000-0000-0000-0000-000000000153",
    systemOperationLogList: "00000000-0000-0000-0000-000000000161",
    systemOperationLogExport: "00000000-0000-0000-0000-000000000162",
    systemFileList: "00000000-0000-0000-0000-000000000171",
    systemFileUpload: "00000000-0000-0000-0000-000000000172",
    systemFileDownload: "00000000-0000-0000-0000-000000000173",
    systemFileDelete: "00000000-0000-0000-0000-000000000174",
    systemNotificationList: "00000000-0000-0000-0000-000000000181",
    systemNotificationCreate: "00000000-0000-0000-0000-000000000182",
    systemNotificationUpdate: "00000000-0000-0000-0000-000000000183",
    systemTenantList: "00000000-0000-0000-0000-000000000191",
    systemTenantCreate: "00000000-0000-0000-0000-000000000192",
    systemTenantUpdate: "00000000-0000-0000-0000-000000000193",
    workflowDefinitionList: "00000000-0000-0000-0000-000000000194",
    workflowDefinitionCreate: "00000000-0000-0000-0000-000000000195",
    workflowDefinitionUpdate: "00000000-0000-0000-0000-000000000196",
    workflowInstanceList: "00000000-0000-0000-0000-000000000197",
    workflowInstanceStart: "00000000-0000-0000-0000-000000000198",
    workflowInstanceCancel: "00000000-0000-0000-0000-000000000199",
    workflowTaskList: "00000000-0000-0000-0000-0000000001a0",
    workflowTaskComplete: "00000000-0000-0000-0000-0000000001a1",
    workflowTaskClaim: "00000000-0000-0000-0000-0000000001a2",
    customerList: "00000000-0000-0000-0000-000000000201",
    customerCreate: "00000000-0000-0000-0000-000000000202",
    customerUpdate: "00000000-0000-0000-0000-000000000203",
    customerDelete: "00000000-0000-0000-0000-000000000204",
  },
  menus: {
    systemRoot: "00000000-0000-0000-0000-000000000301",
    systemUsers: "00000000-0000-0000-0000-000000000302",
    systemRoles: "00000000-0000-0000-0000-000000000303",
    systemMenus: "00000000-0000-0000-0000-000000000304",
    systemDepartments: "00000000-0000-0000-0000-000000000305",
    systemPosts: "00000000-0000-0000-0000-000000000316",
    systemDictionaries: "00000000-0000-0000-0000-000000000306",
    systemSettings: "00000000-0000-0000-0000-000000000307",
    systemOperationLogs: "00000000-0000-0000-0000-000000000308",
    systemFiles: "00000000-0000-0000-0000-000000000309",
    customerRoot: "00000000-0000-0000-0000-000000000310",
    customerList: "00000000-0000-0000-0000-000000000311",
    systemNotifications: "00000000-0000-0000-0000-000000000312",
    systemTenants: "00000000-0000-0000-0000-000000000313",
    workflowRoot: "00000000-0000-0000-0000-000000000314",
    workflowDefinitions: "00000000-0000-0000-0000-000000000315",
  },
  dictionaryTypes: {
    customerStatus: "00000000-0000-0000-0000-000000000501",
  },
  dictionaryItems: {
    customerStatusActive: "00000000-0000-0000-0000-000000000601",
    customerStatusInactive: "00000000-0000-0000-0000-000000000602",
  },
  users: {
    admin: "00000000-0000-0000-0000-000000000401",
  },
} as const

export const defaultWorkflowSeedIds = {
  expenseApprovalV1: "00000000-0000-0000-0000-000000000701",
  expenseApprovalV2: "00000000-0000-0000-0000-000000000702",
  expenseApprovalConditionV1: "00000000-0000-0000-0000-000000000703",
} as const

export const defaultAuthSeedConfig: DefaultAuthSeedConfig = {
  adminUsername: "admin",
  adminPassword: ["admin", "123"].join(""),
  adminDisplayName: "Administrator",
}

export const defaultAuthSeedBlueprint = {
  roles: [
    {
      id: defaultAuthSeedIds.roles.admin,
      code: "admin",
      name: "Admin",
      description: "System administrator with full platform access",
      status: "active",
      isSystem: true,
    },
    {
      id: defaultAuthSeedIds.roles.operator,
      code: "operator",
      name: "Operator",
      description: "Limited platform operator role",
      status: "active",
      isSystem: true,
    },
  ],
  permissions: [
    {
      id: defaultAuthSeedIds.permissions.systemUserList,
      code: "system:user:list",
      module: "system",
      resource: "user",
      action: "list",
      name: "List system users",
      description: "View system user list",
    },
    {
      id: defaultAuthSeedIds.permissions.systemUserCreate,
      code: "system:user:create",
      module: "system",
      resource: "user",
      action: "create",
      name: "Create system user",
      description: "Create system user records",
    },
    {
      id: defaultAuthSeedIds.permissions.systemUserUpdate,
      code: "system:user:update",
      module: "system",
      resource: "user",
      action: "update",
      name: "Update system user",
      description: "Update system user records",
    },
    {
      id: defaultAuthSeedIds.permissions.systemUserResetPassword,
      code: "system:user:reset-password",
      module: "system",
      resource: "user",
      action: "reset-password",
      name: "Reset system user password",
      description: "Reset system user passwords",
    },
    {
      id: defaultAuthSeedIds.permissions.systemRoleList,
      code: "system:role:list",
      module: "system",
      resource: "role",
      action: "list",
      name: "List system roles",
      description: "View system role list",
    },
    {
      id: defaultAuthSeedIds.permissions.systemRoleCreate,
      code: "system:role:create",
      module: "system",
      resource: "role",
      action: "create",
      name: "Create system role",
      description: "Create system roles",
    },
    {
      id: defaultAuthSeedIds.permissions.systemRoleUpdate,
      code: "system:role:update",
      module: "system",
      resource: "role",
      action: "update",
      name: "Update system role",
      description: "Update system roles and assignments",
    },
    {
      id: defaultAuthSeedIds.permissions.systemMenuList,
      code: "system:menu:list",
      module: "system",
      resource: "menu",
      action: "list",
      name: "List system menus",
      description: "View system menu tree",
    },
    {
      id: defaultAuthSeedIds.permissions.systemMenuUpdate,
      code: "system:menu:update",
      module: "system",
      resource: "menu",
      action: "update",
      name: "Update system menus",
      description: "Create and update system menus",
    },
    {
      id: defaultAuthSeedIds.permissions.systemDepartmentList,
      code: "system:department:list",
      module: "system",
      resource: "department",
      action: "list",
      name: "List system departments",
      description: "View system department tree",
    },
    {
      id: defaultAuthSeedIds.permissions.systemDepartmentCreate,
      code: "system:department:create",
      module: "system",
      resource: "department",
      action: "create",
      name: "Create system department",
      description: "Create system departments",
    },
    {
      id: defaultAuthSeedIds.permissions.systemDepartmentUpdate,
      code: "system:department:update",
      module: "system",
      resource: "department",
      action: "update",
      name: "Update system department",
      description: "Update system departments and user assignments",
    },
    {
      id: defaultAuthSeedIds.permissions.systemPostList,
      code: "system:post:list",
      module: "system",
      resource: "post",
      action: "list",
      name: "List system posts",
      description: "View system post list",
    },
    {
      id: defaultAuthSeedIds.permissions.systemPostCreate,
      code: "system:post:create",
      module: "system",
      resource: "post",
      action: "create",
      name: "Create system post",
      description: "Create system post records",
    },
    {
      id: defaultAuthSeedIds.permissions.systemPostUpdate,
      code: "system:post:update",
      module: "system",
      resource: "post",
      action: "update",
      name: "Update system post",
      description: "Update system post records",
    },
    {
      id: defaultAuthSeedIds.permissions.systemDictionaryList,
      code: "system:dictionary:list",
      module: "system",
      resource: "dictionary",
      action: "list",
      name: "List system dictionaries",
      description: "View dictionary types and items",
    },
    {
      id: defaultAuthSeedIds.permissions.systemDictionaryCreate,
      code: "system:dictionary:create",
      module: "system",
      resource: "dictionary",
      action: "create",
      name: "Create system dictionaries",
      description: "Create dictionary types and items",
    },
    {
      id: defaultAuthSeedIds.permissions.systemDictionaryUpdate,
      code: "system:dictionary:update",
      module: "system",
      resource: "dictionary",
      action: "update",
      name: "Update system dictionaries",
      description: "Update dictionary types and items",
    },
    {
      id: defaultAuthSeedIds.permissions.systemSettingList,
      code: "system:setting:list",
      module: "system",
      resource: "setting",
      action: "list",
      name: "List system settings",
      description: "View system settings",
    },
    {
      id: defaultAuthSeedIds.permissions.systemSettingCreate,
      code: "system:setting:create",
      module: "system",
      resource: "setting",
      action: "create",
      name: "Create system settings",
      description: "Create system settings",
    },
    {
      id: defaultAuthSeedIds.permissions.systemSettingUpdate,
      code: "system:setting:update",
      module: "system",
      resource: "setting",
      action: "update",
      name: "Update system settings",
      description: "Update system settings",
    },
    {
      id: defaultAuthSeedIds.permissions.systemOperationLogList,
      code: "system:operation-log:list",
      module: "system",
      resource: "operation-log",
      action: "list",
      name: "List operation logs",
      description: "View and filter operation logs",
    },
    {
      id: defaultAuthSeedIds.permissions.systemOperationLogExport,
      code: "system:operation-log:export",
      module: "system",
      resource: "operation-log",
      action: "export",
      name: "Export operation logs",
      description: "Export operation logs as CSV",
    },
    {
      id: defaultAuthSeedIds.permissions.systemFileList,
      code: "system:file:list",
      module: "system",
      resource: "file",
      action: "list",
      name: "List files",
      description: "View uploaded file records",
    },
    {
      id: defaultAuthSeedIds.permissions.systemFileUpload,
      code: "system:file:upload",
      module: "system",
      resource: "file",
      action: "upload",
      name: "Upload files",
      description: "Upload files into platform storage",
    },
    {
      id: defaultAuthSeedIds.permissions.systemFileDownload,
      code: "system:file:download",
      module: "system",
      resource: "file",
      action: "download",
      name: "Download files",
      description: "Download uploaded files",
    },
    {
      id: defaultAuthSeedIds.permissions.systemFileDelete,
      code: "system:file:delete",
      module: "system",
      resource: "file",
      action: "delete",
      name: "Delete files",
      description: "Delete uploaded files",
    },
    {
      id: defaultAuthSeedIds.permissions.systemNotificationList,
      code: "system:notification:list",
      module: "system",
      resource: "notification",
      action: "list",
      name: "List notifications",
      description: "View station notifications",
    },
    {
      id: defaultAuthSeedIds.permissions.systemNotificationCreate,
      code: "system:notification:create",
      module: "system",
      resource: "notification",
      action: "create",
      name: "Create notifications",
      description: "Create station notifications",
    },
    {
      id: defaultAuthSeedIds.permissions.systemNotificationUpdate,
      code: "system:notification:update",
      module: "system",
      resource: "notification",
      action: "update",
      name: "Update notifications",
      description: "Mark notifications as read",
    },
    {
      id: defaultAuthSeedIds.permissions.systemTenantList,
      code: "system:tenant:list",
      module: "system",
      resource: "tenant",
      action: "list",
      name: "List tenants",
      description: "View tenant records",
    },
    {
      id: defaultAuthSeedIds.permissions.systemTenantCreate,
      code: "system:tenant:create",
      module: "system",
      resource: "tenant",
      action: "create",
      name: "Create tenant",
      description: "Create tenant records",
    },
    {
      id: defaultAuthSeedIds.permissions.systemTenantUpdate,
      code: "system:tenant:update",
      module: "system",
      resource: "tenant",
      action: "update",
      name: "Update tenant",
      description: "Update tenant records",
    },
    {
      id: defaultAuthSeedIds.permissions.workflowDefinitionList,
      code: "workflow:definition:list",
      module: "workflow",
      resource: "definition",
      action: "list",
      name: "List workflow definitions",
      description: "View workflow definitions",
    },
    {
      id: defaultAuthSeedIds.permissions.workflowDefinitionCreate,
      code: "workflow:definition:create",
      module: "workflow",
      resource: "definition",
      action: "create",
      name: "Create workflow definition",
      description: "Create workflow definitions",
    },
    {
      id: defaultAuthSeedIds.permissions.workflowDefinitionUpdate,
      code: "workflow:definition:update",
      module: "workflow",
      resource: "definition",
      action: "update",
      name: "Update workflow definition",
      description: "Publish new workflow definition versions",
    },
    {
      id: defaultAuthSeedIds.permissions.workflowInstanceList,
      code: "workflow:instance:list",
      module: "workflow",
      resource: "instance",
      action: "list",
      name: "List workflow instances",
      description: "View workflow instances and instance detail",
    },
    {
      id: defaultAuthSeedIds.permissions.workflowInstanceStart,
      code: "workflow:instance:start",
      module: "workflow",
      resource: "instance",
      action: "start",
      name: "Start workflow instance",
      description: "Start workflow instances from active definitions",
    },
    {
      id: defaultAuthSeedIds.permissions.workflowInstanceCancel,
      code: "workflow:instance:cancel",
      module: "workflow",
      resource: "instance",
      action: "cancel",
      name: "Cancel workflow instance",
      description: "Cancel running workflow instances",
    },
    {
      id: defaultAuthSeedIds.permissions.workflowTaskList,
      code: "workflow:task:list",
      module: "workflow",
      resource: "task",
      action: "list",
      name: "List workflow tasks",
      description: "View workflow todo and done task lists",
    },
    {
      id: defaultAuthSeedIds.permissions.workflowTaskClaim,
      code: "workflow:task:claim",
      module: "workflow",
      resource: "task",
      action: "claim",
      name: "Claim workflow task",
      description: "Claim workflow tasks for the current user",
    },
    {
      id: defaultAuthSeedIds.permissions.workflowTaskComplete,
      code: "workflow:task:complete",
      module: "workflow",
      resource: "task",
      action: "complete",
      name: "Complete workflow task",
      description: "Approve or reject workflow tasks",
    },
    {
      id: defaultAuthSeedIds.permissions.customerList,
      code: "customer:customer:list",
      module: "customer",
      resource: "customer",
      action: "list",
      name: "List customers",
      description: "View customer list",
    },
    {
      id: defaultAuthSeedIds.permissions.customerCreate,
      code: "customer:customer:create",
      module: "customer",
      resource: "customer",
      action: "create",
      name: "Create customer",
      description: "Create customer records",
    },
    {
      id: defaultAuthSeedIds.permissions.customerUpdate,
      code: "customer:customer:update",
      module: "customer",
      resource: "customer",
      action: "update",
      name: "Update customer",
      description: "Update customer records",
    },
    {
      id: defaultAuthSeedIds.permissions.customerDelete,
      code: "customer:customer:delete",
      module: "customer",
      resource: "customer",
      action: "delete",
      name: "Delete customer",
      description: "Delete customer records",
    },
  ],
  menus: [
    {
      id: defaultAuthSeedIds.menus.systemRoot,
      parentId: null,
      type: "directory",
      code: "system-root",
      name: "System",
      path: "/system",
      component: null,
      icon: "settings",
      sort: 10,
      isVisible: true,
      status: "active",
      permissionCode: null,
    },
    {
      id: defaultAuthSeedIds.menus.systemUsers,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-users",
      name: "Users",
      path: "/system/users",
      component: "system/users/index",
      icon: "users",
      sort: 11,
      isVisible: true,
      status: "active",
      permissionCode: "system:user:list",
    },
    {
      id: defaultAuthSeedIds.menus.systemRoles,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-roles",
      name: "Roles",
      path: "/system/roles",
      component: "system/roles/index",
      icon: "shield",
      sort: 12,
      isVisible: true,
      status: "active",
      permissionCode: "system:role:list",
    },
    {
      id: defaultAuthSeedIds.menus.systemMenus,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-menus",
      name: "Menus",
      path: "/system/menus",
      component: "system/menus/index",
      icon: "menu",
      sort: 13,
      isVisible: true,
      status: "active",
      permissionCode: "system:menu:list",
    },
    {
      id: defaultAuthSeedIds.menus.systemDepartments,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-departments",
      name: "Departments",
      path: "/system/departments",
      component: "system/departments/index",
      icon: "apartment",
      sort: 14,
      isVisible: true,
      status: "active",
      permissionCode: "system:department:list",
    },
    {
      id: defaultAuthSeedIds.menus.systemPosts,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-posts",
      name: "Posts",
      path: "/system/posts",
      component: "system/posts/index",
      icon: "idcard",
      sort: 15,
      isVisible: true,
      status: "active",
      permissionCode: "system:post:list",
    },
    {
      id: defaultAuthSeedIds.menus.systemDictionaries,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-dictionaries",
      name: "Dictionaries",
      path: "/system/dictionaries",
      component: "system/dictionaries/index",
      icon: "book",
      sort: 16,
      isVisible: true,
      status: "active",
      permissionCode: "system:dictionary:list",
    },
    {
      id: defaultAuthSeedIds.menus.systemSettings,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-settings",
      name: "Settings",
      path: "/system/settings",
      component: "system/settings/index",
      icon: "tool",
      sort: 17,
      isVisible: true,
      status: "active",
      permissionCode: "system:setting:list",
    },
    {
      id: defaultAuthSeedIds.menus.systemOperationLogs,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-operation-logs",
      name: "Operation Logs",
      path: "/system/operation-logs",
      component: "system/operation-logs/index",
      icon: "file",
      sort: 18,
      isVisible: true,
      status: "active",
      permissionCode: "system:operation-log:list",
    },
    {
      id: defaultAuthSeedIds.menus.systemFiles,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-files",
      name: "Files",
      path: "/system/files",
      component: "system/files/index",
      icon: "attachment",
      sort: 19,
      isVisible: true,
      status: "active",
      permissionCode: "system:file:list",
    },
    {
      id: defaultAuthSeedIds.menus.systemNotifications,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-notifications",
      name: "Notifications",
      path: "/system/notifications",
      component: "system/notifications/index",
      icon: "notification",
      sort: 20,
      isVisible: true,
      status: "active",
      permissionCode: "system:notification:list",
    },
    {
      id: defaultAuthSeedIds.menus.systemTenants,
      parentId: defaultAuthSeedIds.menus.systemRoot,
      type: "menu",
      code: "system-tenants",
      name: "Tenants",
      path: "/system/tenants",
      component: "system/tenants/index",
      icon: "cluster",
      sort: 21,
      isVisible: true,
      status: "active",
      permissionCode: "system:tenant:list",
    },
    {
      id: defaultAuthSeedIds.menus.workflowRoot,
      parentId: null,
      type: "directory",
      code: "workflow-root",
      name: "Workflow",
      path: "/workflow",
      component: null,
      icon: "share",
      sort: 22,
      isVisible: true,
      status: "active",
      permissionCode: null,
    },
    {
      id: defaultAuthSeedIds.menus.workflowDefinitions,
      parentId: defaultAuthSeedIds.menus.workflowRoot,
      type: "menu",
      code: "workflow-definitions",
      name: "Definitions",
      path: "/workflow/definitions",
      component: "workflow/definitions/index",
      icon: "tree-square-dot",
      sort: 23,
      isVisible: true,
      status: "active",
      permissionCode: "workflow:definition:list",
    },
    {
      id: defaultAuthSeedIds.menus.customerRoot,
      parentId: null,
      type: "directory",
      code: "customer-root",
      name: "Customer",
      path: "/customer",
      component: null,
      icon: "briefcase",
      sort: 24,
      isVisible: true,
      status: "active",
      permissionCode: null,
    },
    {
      id: defaultAuthSeedIds.menus.customerList,
      parentId: defaultAuthSeedIds.menus.customerRoot,
      type: "menu",
      code: "customer-list",
      name: "Customers",
      path: "/customers",
      component: "customer/index",
      icon: "briefcase",
      sort: 25,
      isVisible: true,
      status: "active",
      permissionCode: "customer:customer:list",
    },
  ],
  dictionaryTypes: [
    {
      id: defaultAuthSeedIds.dictionaryTypes.customerStatus,
      code: "customer_status",
      name: "Customer Status",
      description: "Status options for customer records",
      status: "active",
    },
  ],
  dictionaryItems: [
    {
      id: defaultAuthSeedIds.dictionaryItems.customerStatusActive,
      typeId: defaultAuthSeedIds.dictionaryTypes.customerStatus,
      value: "active",
      label: "active",
      sort: 10,
      isDefault: true,
      status: "active",
    },
    {
      id: defaultAuthSeedIds.dictionaryItems.customerStatusInactive,
      typeId: defaultAuthSeedIds.dictionaryTypes.customerStatus,
      value: "inactive",
      label: "inactive",
      sort: 20,
      isDefault: false,
      status: "active",
    },
  ],
} satisfies Pick<
  DefaultAuthSeedSpec,
  "roles" | "permissions" | "menus" | "dictionaryTypes" | "dictionaryItems"
>
