/**
 * @generated by elysian-generator
 * schema: notification
 * path: modules/notification/notification.schema.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import { notificationModuleSchema as sourceModuleSchema } from "@elysian/schema"
import type { ModuleSchema } from "@elysian/schema"

export type NotificationLevel = "info" | "success" | "warning" | "error"

export type NotificationStatus = "unread" | "read"

export interface NotificationRecord {
  id: string
  recipientUserId: string
  title: string
  content: string
  level: NotificationLevel
  status: NotificationStatus
  createdByUserId: string
  readAt: string
  createdAt: string
}

export const notificationModuleSchema: ModuleSchema = sourceModuleSchema

export const moduleSchema = notificationModuleSchema
