/**
 * @generated by elysian-generator
 * schema: notification
 * path: modules/notification/notification-workspace.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import type { FrontendWorkspaceStateContext } from "@elysian/frontend-vue"
import type { ElyFormField, ElyFormValues } from "@elysian/ui-enterprise-vue"
import type { ComputedRef } from "vue"
import { computed } from "vue"

import type { NotificationRecord } from "./notification.schema"

export interface NotificationWorkspaceMainInjectedState {
  notificationErrorMessage: { value: string }
  notificationLoading: { value: boolean }
  tableItems: { value: NotificationRecord[] }
}

export interface NotificationWorkspacePanelInjectedState
  extends NotificationWorkspaceMainInjectedState {
  formFields: { value: ElyFormField[] }
  formValues: { value: ElyFormValues }
  panelDescription: { value: string }
  panelTitle: { value: string }
  notificationDetailErrorMessage: { value: string }
  notificationDetailLoading: { value: boolean }
  notificationPanelMode: { value: "detail" | "create" }
  selectedNotification: { value: NotificationRecord | null }
}

const resolveNotificationWorkspaceState = <TState>(
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
): TState | null => {
  if (!enabled || context?.kind !== "notification") {
    return null
  }

  return context.state as TState
}

export const resolveNotificationWorkspaceMainState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveNotificationWorkspaceState<NotificationWorkspaceMainInjectedState>(
    context,
    enabled,
  )

export const resolveNotificationWorkspacePanelState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveNotificationWorkspaceState<NotificationWorkspacePanelInjectedState>(
    context,
    enabled,
  )

export const readInjectedValue = <TValue>(
  state: ComputedRef<{ value: TValue } | null>,
  fallback: TValue,
) => computed(() => state.value?.value ?? fallback)

const normalizeText = (value: unknown) => String(value ?? "").trim()

const normalizeOptionalText = (value: unknown) => {
  const normalized = normalizeText(value)

  return normalized.length > 0 ? normalized : undefined
}

const normalizeNumber = (value: unknown, fallback = 0) => {
  const normalized =
    typeof value === "number" ? value : Number.parseInt(String(value ?? ""), 10)

  return Number.isFinite(normalized) ? normalized : fallback
}

export const createDefaultNotificationDraft = () => ({
  recipientUserId: "",
  title: "",
  content: "",
  level: "info",
  status: "unread",
  createdByUserId: "",
  readAt: "",
})

export const filterNotificationRecords = (
  items: NotificationRecord[],
  query: Record<string, unknown>,
): NotificationRecord[] => {
  const title = String(query.title ?? "")
    .trim()
    .toLowerCase()
  const content = String(query.content ?? "")
    .trim()
    .toLowerCase()

  return items.filter((item) => {
    if (
      title.length > 0 &&
      !String(item.title ?? "")
        .toLowerCase()
        .includes(title)
    )
      return false
    if (
      content.length > 0 &&
      !String(item.content ?? "")
        .toLowerCase()
        .includes(content)
    )
      return false
    if (
      query.level !== undefined &&
      query.level !== null &&
      query.level !== "" &&
      item.level !== query.level
    )
      return false
    if (
      query.status !== undefined &&
      query.status !== null &&
      query.status !== "" &&
      item.status !== query.status
    )
      return false

    return true
  })
}

export const resolveNotificationSelection = (
  items: Array<Pick<NotificationRecord, "id">>,
  selectedId: string | null,
): string | null => {
  if (items.length === 0) return null

  if (selectedId && items.some((item) => item.id === selectedId)) {
    return selectedId
  }

  return items[0]?.id ?? null
}

export const normalizeNotificationPayload = (
  values: Record<string, unknown>,
):
  | { status: "valid"; payload: Record<string, unknown> }
  | { status: "invalid"; message: string } => {
  const recipientUserIdValue = String(values.recipientUserId ?? "").trim()

  if (recipientUserIdValue.length === 0) {
    return {
      status: "invalid" as const,
      message: "Notification recipientUserId is required",
    }
  }

  const titleValue = String(values.title ?? "").trim()

  if (titleValue.length === 0) {
    return {
      status: "invalid" as const,
      message: "Notification title is required",
    }
  }

  const contentValue = String(values.content ?? "").trim()

  if (contentValue.length === 0) {
    return {
      status: "invalid" as const,
      message: "Notification content is required",
    }
  }

  return {
    status: "valid" as const,
    payload: {
      recipientUserId: recipientUserIdValue,
      title: titleValue,
      content: contentValue,
      level: values.level ?? "info",
      status: values.status ?? "unread",
      createdByUserId: normalizeOptionalText(values.createdByUserId),
      readAt: normalizeText(values.readAt),
    },
  }
}

export const toNotificationEditDraft = (
  record: NotificationRecord,
): Record<string, unknown> => ({
  recipientUserId: record.recipientUserId ?? "",
  title: record.title ?? "",
  content: record.content ?? "",
  level: record.level ?? "info",
  status: record.status ?? "unread",
  createdByUserId: record.createdByUserId ?? "",
  readAt: record.readAt ?? "",
})
