<script setup lang="ts">
import GeneratorPreviewWorkspaceCurrentResultPanel from "./GeneratorPreviewWorkspaceCurrentResultPanel.vue"
import GeneratorPreviewWorkspaceDraftStartPanel from "./GeneratorPreviewWorkspaceDraftStartPanel.vue"
import GeneratorPreviewWorkspaceResultListSection from "./GeneratorPreviewWorkspaceResultListSection.vue"
import type {
  GeneratorPreviewWorkspaceMainEmit,
  GeneratorPreviewWorkspaceMainProps,
} from "./use-generator-preview-workspace-main-state"
import { useGeneratorPreviewWorkspaceMainState } from "./use-generator-preview-workspace-main-state"

const props = defineProps<GeneratorPreviewWorkspaceMainProps>()
const emit = defineEmits<GeneratorPreviewWorkspaceMainEmit>()

const {
  canPatchDraftMeta,
  canSubmitReject,
  confirmationChecklist,
  cancelApplyConfirmation,
  cancelRejectConfirmation,
  blockedFileCount,
  blockerReasonMessages,
  configPrimaryActionLabel,
  configErrorRecoverySteps,
  conflictStrategyCards,
  currentStateMessage,
  draftModuleLabel,
  draftModuleName,
  draftSourceMode,
  draftSourceModeOptions,
  draftSummaryFacts,
  filteredReferenceSchemaOptions,
  frontendOptionCards,
  firstBlockedFilePath,
  handleApplyPreview,
  handleConflictStrategyChange,
  handleConfirmPreview,
  handleDraftSourceModeChange,
  handleFileSelection,
  handleFrontendChange,
  handleLoadReferenceSchemaDraft,
  handleLoadSchemaTemplate,
  handleManualSchemaDraftInput,
  handleModuleLabelInput,
  handleModuleNameInput,
  handleQueryInput,
  handleRecentSessionChange,
  handleReferenceSchemaQueryInput,
  handleRefreshPreview,
  handleRestoreCurrentResult,
  handleReviewCommentInput,
  handleReviewPreview,
  handleSchemaEditorToggle,
  hasCurrentResult,
  hasRecentSessions,
  hiddenReferenceSchemaCount,
  isApplyConfirming,
  isRejectConfirming,
  operationProgressMessage,
  referenceSchemaQuery,
  recoveryStatusMessage,
  rejectCommentRequired,
  resultErrorRecoverySteps,
  resultPrimaryActionLabel,
  reviewComment,
  schemaEditorFacts,
  schemaTemplates,
  selectedTemplateId,
  showApplyAction,
  showConfirmAction,
  showFileList,
  showFileTools,
  showReviewActions,
  showReviewCommentInput,
  showSchemaEditor,
  statusFacts,
} = useGeneratorPreviewWorkspaceMainState(props, emit)
</script>

<template>
  <GeneratorPreviewWorkspaceDraftStartPanel
    :t="t"
    :loading="loading"
    :review-loading="reviewLoading"
    :apply-loading="applyLoading"
    :error-message="errorMessage"
    :selected-schema-name="selectedSchemaName"
    :selected-frontend-target="selectedFrontendTarget"
    :selected-conflict-strategy="selectedConflictStrategy"
    :manual-schema-draft="manualSchemaDraft"
    :manual-schema-draft-error="manualSchemaDraftError"
    :manual-schema-draft-error-details="manualSchemaDraftErrorDetails"
    :manual-schema-draft-error-suggestion="manualSchemaDraftErrorSuggestion"
    :draft-module-name="draftModuleName"
    :draft-module-label="draftModuleLabel"
    :can-patch-draft-meta="canPatchDraftMeta"
    :draft-source-mode="draftSourceMode"
    :selected-template-id="selectedTemplateId"
    :reference-schema-query="referenceSchemaQuery"
    :filtered-reference-schema-options="filteredReferenceSchemaOptions"
    :hidden-reference-schema-count="hiddenReferenceSchemaCount"
    :frontend-option-cards="frontendOptionCards"
    :conflict-strategy-cards="conflictStrategyCards"
    :draft-source-mode-options="draftSourceModeOptions"
    :schema-templates="schemaTemplates"
    :config-primary-action-label="configPrimaryActionLabel"
    :config-error-recovery-steps="configErrorRecoverySteps"
    :show-schema-editor="showSchemaEditor"
    :schema-editor-facts="schemaEditorFacts"
    :draft-summary-facts="draftSummaryFacts"
    @module-name-input="handleModuleNameInput"
    @module-label-input="handleModuleLabelInput"
    @draft-source-mode-change="handleDraftSourceModeChange"
    @load-schema-template="handleLoadSchemaTemplate"
    @reference-schema-query-input="handleReferenceSchemaQueryInput"
    @load-reference-schema-draft="handleLoadReferenceSchemaDraft"
    @frontend-change="handleFrontendChange"
    @conflict-strategy-change="handleConflictStrategyChange"
    @refresh-preview="handleRefreshPreview"
    @schema-editor-toggle="handleSchemaEditorToggle"
    @manual-schema-draft-input="handleManualSchemaDraftInput"
  />

  <GeneratorPreviewWorkspaceCurrentResultPanel
    :t="t"
    :loading="loading"
    :review-loading="reviewLoading"
    :apply-loading="applyLoading"
    :has-current-result="hasCurrentResult"
    :has-recent-sessions="hasRecentSessions"
    :recent-session-options="recentSessionOptions"
    :selected-recent-session-id="selectedRecentSessionId"
    :status-facts="statusFacts"
    :current-state-message="currentStateMessage"
    :operation-progress-message="operationProgressMessage"
    :blocked-file-count="blockedFileCount"
    :blocker-reason-messages="blockerReasonMessages"
    :first-blocked-file-path="firstBlockedFilePath"
    :recovery-status-message="recoveryStatusMessage"
    :result-error-recovery-steps="resultErrorRecoverySteps"
    :confirmation-checklist="confirmationChecklist"
    :show-review-comment-input="showReviewCommentInput"
    :review-comment="reviewComment"
    :reject-comment-required="rejectCommentRequired"
    :review-evidence="reviewEvidence"
    :apply-evidence="applyEvidence"
    :show-review-actions="showReviewActions"
    :is-reject-confirming="isRejectConfirming"
    :can-reject="canReject"
    :can-submit-reject="canSubmitReject"
    :can-approve="canApprove"
    :show-confirm-action="showConfirmAction"
    :can-confirm="canConfirm"
    :show-apply-action="showApplyAction"
    :is-apply-confirming="isApplyConfirming"
    :can-apply="canApply"
    :result-primary-action-label="resultPrimaryActionLabel"
    @recent-session-change="handleRecentSessionChange"
    @restore-current-result="handleRestoreCurrentResult"
    @refresh-preview="handleRefreshPreview"
    @review-comment-input="handleReviewCommentInput"
    @cancel-reject-confirm="cancelRejectConfirmation"
    @review-preview="handleReviewPreview"
    @cancel-apply-confirm="cancelApplyConfirmation"
    @confirm-preview="handleConfirmPreview"
    @apply-preview="handleApplyPreview"
    @select-file="handleFileSelection"
  />

  <GeneratorPreviewWorkspaceResultListSection
    v-if="showFileList"
    :t="t"
    :loading="loading"
    :show-file-tools="showFileTools"
    :query="query"
    :files="files"
    :selected-file-path="selectedFilePath"
    @query-input="handleQueryInput"
    @select-file="handleFileSelection"
  />
</template>
