/**
 * @generated by elysian-generator
 * schema: user
 * path: modules/user/user.page.vue
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

<script setup lang="ts">
import {
  ElyCrudWorkspace,
  type ElyCrudWorkspaceProps,
  ElyPagination,
  type ElyQueryField,
  type ElyQueryValues,
  type ElyTableAction,
  type ElyTableColumn,
  useElyPagination,
} from "@elysian/ui-enterprise-vue"
import { computed, inject, ref } from "vue"

import { WORKSPACE_STATE_KEY } from "@elysian/frontend-vue"
import {
  readInjectedValue,
  resolveUserWorkspaceMainState,
} from "./user-workspace"
import type { UserRecord } from "./user.schema"

type UserWorkspaceTranslation = (
  key: string,
  params?: Record<string, unknown>,
) => string

interface UserWorkspaceMainProps {
  t: UserWorkspaceTranslation
  moduleReady: boolean
  authModuleReady: boolean
  isAuthenticated: boolean
  canEnterWorkspace: boolean
  canViewUsers: boolean
  canCreateUsers: boolean
  canUpdateUsers: boolean
  canDeleteUsers: boolean
  canExportUsers: boolean
  queryFields: ElyQueryField[]
  tableColumns: ElyTableColumn[]
  itemCountLabel: string
  emptyTitle: string
  emptyDescription: string
  copy: ElyCrudWorkspaceProps["copy"]
  workspaceStateInjected?: boolean
}

const props = defineProps<UserWorkspaceMainProps>()

const emit = defineEmits<{
  (e: "action", key: string, row: UserRecord): void
  (e: "search", values: ElyQueryValues): void
  (e: "reset"): void
  (e: "row-click", row: UserRecord): void
  (e: "page-change", page: number, pageSize: number): void
  (e: "export", query: ElyQueryValues): void
}>()

const activeQuery = ref<ElyQueryValues>({})

const hasActiveQuery = computed(() => {
  const q = activeQuery.value
  return Object.keys(q).some((k) => {
    const v = q[k]
    if (v === undefined || v === "") return false
    if (Array.isArray(v)) return v.length > 0
    return true
  })
})

const injectedWorkspaceState = inject(
  WORKSPACE_STATE_KEY,
  computed(() => null),
)

const resolvedUserWorkspaceState = computed(() =>
  resolveUserWorkspaceMainState(
    injectedWorkspaceState.value,
    Boolean(props.workspaceStateInjected),
  ),
)

const resolvedLoading = readInjectedValue(
  computed(() => resolvedUserWorkspaceState.value?.userLoading ?? null),
  false,
)
const resolvedErrorMessage = readInjectedValue(
  computed(() => resolvedUserWorkspaceState.value?.userErrorMessage ?? null),
  "",
)
const resolvedItems = readInjectedValue(
  computed(() => resolvedUserWorkspaceState.value?.tableItems ?? null),
  [] as UserRecord[],
)

const {
  currentPage,
  pageSize,
  pageSizeOptions,
  totalPages,
  paginatedItems,
  paginationSummary,
  goPreviousPage,
  goNextPage,
  updatePageSize,
} = useElyPagination(resolvedItems, { t: props.t })

const resolvedStatus = computed(() => {
  if (!props.moduleReady) return "module-offline"
  if (props.authModuleReady && !props.isAuthenticated)
    return "not-authenticated"
  if (props.canEnterWorkspace && !props.canViewUsers) return "no-permission"
  if (resolvedErrorMessage.value) return "error"
  return "ready"
})

const resolvedStatusMessage = computed(() => {
  if (resolvedStatus.value === "module-offline") {
    return props.t("app.message.userModuleOffline")
  }
  if (resolvedStatus.value === "not-authenticated") {
    return props.t("app.message.userSignInToLoad")
  }
  if (resolvedStatus.value === "no-permission") {
    return props.t("app.message.userNoListPermission")
  }
  return resolvedErrorMessage.value
})

const resolvedTableActions = computed<ElyTableAction[]>(() => {
  const actions: ElyTableAction[] = []

  if (props.canUpdateUsers) {
    actions.push({
      key: "edit",
      label: props.t("app.user.action.edit"),
    })
  }

  if (props.canDeleteUsers) {
    actions.push({
      key: "delete",
      label: props.t("app.user.action.delete"),
      tone: "danger",
    })
  }

  return actions
})

const handleAction = (key: string, row: Record<string, unknown>) => {
  const rowId = String(row.id ?? "")
  const record = resolvedItems.value.find((item) => item.id === rowId)

  if (record) {
    emit("action", key, record)
  }
}

const handleCreate = () => {
  emit("action", "create", {} as UserRecord)
}

const exportConfirmVisible = ref(false)

const exportScopeSummary = computed(() =>
  props.t("app.user.exportScopeSummary", {
    count: resolvedItems.value.length,
    filtered: hasActiveQuery.value ? "1" : "0",
  }),
)

const requestExport = () => {
  exportConfirmVisible.value = true
}

const confirmExport = () => {
  exportConfirmVisible.value = false
  emit("export", activeQuery.value)
}

const cancelExport = () => {
  exportConfirmVisible.value = false
}

const handleSearch = (values: ElyQueryValues) => {
  activeQuery.value = values
  emit("search", values)
}

const handleReset = () => {
  activeQuery.value = {}
  emit("reset")
}
</script>

<template>
  <ElyCrudWorkspace
    :status="resolvedStatus"
    :status-message="resolvedStatusMessage"
    :eyebrow="t('app.user.workspaceEyebrow')"
    :title="t('app.user.workspaceTitle')"
    :description="''"
    :query-fields="queryFields"
    :query-loading="resolvedLoading"
    :table-columns="tableColumns"
    :items="paginatedItems"
    :table-loading="resolvedLoading"
    :table-actions="resolvedTableActions"
    :item-count-label="itemCountLabel"
    :empty-title="emptyTitle"
    :empty-description="emptyDescription"
    :has-active-query="hasActiveQuery"
    :can-create="canCreateUsers"
    :copy="copy"
    @action="handleAction"
    @search="handleSearch"
    @reset="handleReset"
    @row-click="emit('row-click', $event as UserRecord)"
  >
    <template #toolbar>
      <button
        v-if="canExportUsers"
        type="button"
        class="enterprise-button enterprise-button-ghost"
        :disabled="resolvedLoading"
        @click="requestExport"
      >
        {{ t("app.user.action.export") }}
      </button>
      <div v-if="exportConfirmVisible" class="enterprise-export-confirm">
        <span>{{ exportScopeSummary }}</span>
        <button type="button" class="enterprise-button" @click="confirmExport">
          {{ t("app.user.confirmExport") }}
        </button>
        <button type="button" class="enterprise-button enterprise-button-ghost" @click="cancelExport">
          {{ t("app.user.cancelExport") }}
        </button>
      </div>
      <button
        v-if="canCreateUsers"
        type="button"
        class="enterprise-button"
        :disabled="resolvedLoading"
        @click="handleCreate"
      >
        {{ t("app.user.action.create") }}
      </button>
    </template>
    <template #footer>
      <ElyPagination
        :summary="paginationSummary"
        :page-size="pageSize"
        :page-size-options="pageSizeOptions"
        :current-page="currentPage"
        :total-pages="totalPages"
        :previous-label="t('app.pagination.previous')"
        :next-label="t('app.pagination.next')"
        :page-size-label="t('app.pagination.pageSize')"
        @previous="goPreviousPage"
        @next="goNextPage"
        @update-page-size="updatePageSize"
      />
    </template>
  </ElyCrudWorkspace>
</template>
