/**
 * @generated by elysian-generator
 * schema: user
 * path: modules/user/user-workspace.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import type { FrontendWorkspaceStateContext } from "@elysian/frontend-vue"
import type { ElyFormField, ElyFormValues } from "@elysian/ui-enterprise-vue"
import type { ComputedRef } from "vue"
import { computed } from "vue"

import type { UserRecord } from "./user.schema"

export interface UserWorkspaceMainInjectedState {
  userErrorMessage: { value: string }
  userLoading: { value: boolean }
  tableItems: { value: UserRecord[] }
}

export interface UserWorkspacePanelInjectedState
  extends UserWorkspaceMainInjectedState {
  formFields: { value: ElyFormField[] }
  formValues: { value: ElyFormValues }
  panelDescription: { value: string }
  panelTitle: { value: string }
  userDetailErrorMessage: { value: string }
  userDetailLoading: { value: boolean }
  userPanelMode: { value: "detail" | "create" | "edit" | "reset" }
  selectedUser: { value: UserRecord | null }
}

const resolveUserWorkspaceState = <TState>(
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
): TState | null => {
  if (!enabled || context?.kind !== "user") {
    return null
  }

  return context.state as TState
}

export const resolveUserWorkspaceMainState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) => resolveUserWorkspaceState<UserWorkspaceMainInjectedState>(context, enabled)

export const resolveUserWorkspacePanelState = (
  context: FrontendWorkspaceStateContext | null,
  enabled: boolean,
) =>
  resolveUserWorkspaceState<UserWorkspacePanelInjectedState>(context, enabled)

export const readInjectedValue = <TValue>(
  state: ComputedRef<{ value: TValue } | null>,
  fallback: TValue,
) => computed(() => state.value?.value ?? fallback)

const normalizeText = (value: unknown) => String(value ?? "").trim()

const normalizeOptionalText = (value: unknown) => {
  const normalized = normalizeText(value)

  return normalized.length > 0 ? normalized : undefined
}

const normalizeNumber = (value: unknown, fallback = 0) => {
  const normalized =
    typeof value === "number" ? value : Number.parseInt(String(value ?? ""), 10)

  return Number.isFinite(normalized) ? normalized : fallback
}

const normalizeJsonInput = (
  value: unknown,
):
  | { status: "valid"; value: Record<string, unknown> | null }
  | { status: "invalid" } => {
  if (value === null || value === undefined) {
    return { status: "valid", value: null }
  }

  if (typeof value === "string") {
    const normalized = value.trim()

    if (normalized.length === 0) {
      return { status: "valid", value: null }
    }

    try {
      const parsed: unknown = JSON.parse(normalized)

      if (
        typeof parsed === "object" &&
        parsed !== null &&
        !Array.isArray(parsed)
      ) {
        return {
          status: "valid",
          value: parsed as Record<string, unknown>,
        }
      }

      return { status: "invalid" }
    } catch {
      return { status: "invalid" }
    }
  }

  if (typeof value === "object" && !Array.isArray(value)) {
    return {
      status: "valid",
      value: value as Record<string, unknown>,
    }
  }

  return { status: "invalid" }
}

const stringifyJsonValue = (value: unknown) => {
  if (value === null || value === undefined) {
    return ""
  }

  return JSON.stringify(value, null, 2)
}

export const createDefaultUserDraft = () => ({
  username: "",
  displayName: "",
  email: "",
  phone: "",
  status: "active",
  isSuperAdmin: false,
  lastLoginAt: "",
})

export const filterUserRecords = (
  items: UserRecord[],
  query: Record<string, unknown>,
): UserRecord[] => {
  const username = String(query.username ?? "")
    .trim()
    .toLowerCase()
  const displayName = String(query.displayName ?? "")
    .trim()
    .toLowerCase()
  const email = String(query.email ?? "")
    .trim()
    .toLowerCase()
  const phone = String(query.phone ?? "")
    .trim()
    .toLowerCase()

  return items.filter((item) => {
    if (
      username.length > 0 &&
      !String(item.username ?? "")
        .toLowerCase()
        .includes(username)
    )
      return false
    if (
      displayName.length > 0 &&
      !String(item.displayName ?? "")
        .toLowerCase()
        .includes(displayName)
    )
      return false
    if (
      email.length > 0 &&
      !String(item.email ?? "")
        .toLowerCase()
        .includes(email)
    )
      return false
    if (
      phone.length > 0 &&
      !String(item.phone ?? "")
        .toLowerCase()
        .includes(phone)
    )
      return false
    if (
      query.status !== undefined &&
      query.status !== null &&
      query.status !== "" &&
      item.status !== query.status
    )
      return false

    return true
  })
}

export const resolveUserSelection = (
  items: Array<Pick<UserRecord, "id">>,
  selectedId: string | null,
): string | null => {
  if (items.length === 0) return null

  if (selectedId && items.some((item) => item.id === selectedId)) {
    return selectedId
  }

  return items[0]?.id ?? null
}

export const normalizeUserPayload = (
  values: Record<string, unknown>,
):
  | { status: "valid"; payload: Record<string, unknown> }
  | { status: "invalid"; message: string } => {
  const usernameValue = String(values.username ?? "").trim()

  if (usernameValue.length === 0) {
    return { status: "invalid" as const, message: "User username is required" }
  }

  const displayNameValue = String(values.displayName ?? "").trim()

  if (displayNameValue.length === 0) {
    return {
      status: "invalid" as const,
      message: "User displayName is required",
    }
  }

  return {
    status: "valid" as const,
    payload: {
      username: usernameValue,
      displayName: displayNameValue,
      email: normalizeOptionalText(values.email),
      phone: normalizeOptionalText(values.phone),
      status: values.status ?? "active",
      isSuperAdmin: values.isSuperAdmin ?? false,
      lastLoginAt: normalizeText(values.lastLoginAt),
    },
  }
}

export const toUserEditDraft = (
  record: UserRecord,
): Record<string, unknown> => ({
  username: record.username ?? "",
  displayName: record.displayName ?? "",
  email: record.email ?? "",
  phone: record.phone ?? "",
  status: record.status ?? "active",
  isSuperAdmin: record.isSuperAdmin ?? false,
  lastLoginAt: record.lastLoginAt ?? "",
})
