/**
 * @generated by elysian-generator
 * schema: user
 * path: modules/user/user.page.vue
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

<script setup lang="ts">
import {
  ElyCrudWorkbench,
  type ElyCrudWorkspaceCopy,
  type ElyTableColumn,
} from "@elysian/ui-enterprise-vue"
import { computed, inject } from "vue"

import { WORKSPACE_STATE_KEY } from "@elysian/frontend-vue"
import {
  readInjectedValue,
  resolveUserWorkspaceMainState,
} from "./user-workspace"
import type { UserRecord } from "./user.schema"

type UserWorkspaceTranslation = (
  key: string,
  params?: Record<string, unknown>,
) => string

interface UserWorkspaceMainProps {
  t: UserWorkspaceTranslation
  tableColumns: ElyTableColumn[]
  emptyTitle: string
  emptyDescription: string
  copy: ElyCrudWorkspaceCopy
  workspaceStateInjected?: boolean
}

const props = defineProps<UserWorkspaceMainProps>()

const emit = defineEmits<{
  (e: "row-click", row: UserRecord): void
  (e: "search", value: string): void
}>()

const injectedWorkspaceState = inject(
  WORKSPACE_STATE_KEY,
  computed(() => null),
)

const resolvedUserWorkspaceState = computed(() =>
  resolveUserWorkspaceMainState(
    injectedWorkspaceState.value,
    Boolean(props.workspaceStateInjected),
  ),
)

const resolvedLoading = readInjectedValue(
  computed(() => resolvedUserWorkspaceState.value?.userLoading ?? null),
  false,
)
const resolvedItems = readInjectedValue(
  computed(() => resolvedUserWorkspaceState.value?.tableItems ?? null),
  [] as UserRecord[],
)

const panelTitle = computed(() => props.t("app.user.workspaceTitle"))

const handleSearch = (value: string) => {
  emit("search", value)
}

const handleRowClick = (row: Record<string, unknown>) => {
  const rowId = String(row.id ?? "")
  const user = resolvedItems.value.find(
    (item: UserRecord) => item.id === rowId,
  )
  if (user) {
    emit("row-click", user)
  }
}
</script>

<template>
  <ElyCrudWorkbench
    :title="panelTitle"
    :table-columns="tableColumns"
    :items="resolvedItems"
    :table-loading="resolvedLoading"
    :table-actions="[]"
    :search-placeholder="t('app.user.searchPlaceholder', '搜索用户...')"
    :empty-title="emptyTitle"
    :empty-description="emptyDescription"
    :copy="copy"
    row-key="id"
    @search="handleSearch"
    @row-click="handleRowClick"
  />
</template>
