/**
 * @generated by elysian-generator
 * schema: user
 * path: modules/user/user.schema.ts
 * merge-strategy: replace-whole-file
 * manual-edits: discouraged
 */

import { userModuleSchema as sourceModuleSchema } from "@elysian/schema"
import type { ModuleSchema } from "@elysian/schema"

export type UserStatus = "active" | "disabled"

export interface UserRecord {
  id: string
  username: string
  displayName: string
  email: string
  phone: string
  status: UserStatus
  isSuperAdmin: boolean
  lastLoginAt: string
  createdAt: string
  updatedAt: string
}

export const userModuleSchema: ModuleSchema = sourceModuleSchema

export const moduleSchema = userModuleSchema
